// SPDX-License-Identifier: GPL-3.0-only

//! Mindustry-Godot's SpacetimeDB client facade (`mind-stdb`), the Rust
//! replacement for the legacy C# `sstdbsdk`.
//!
//! Plan `01_PLATFORM_STDB_IMPLEMENTATION_PLAN.md` owns the surface:
//! connector lifecycle (§3.4), subscription waves (§3.6), typed binders (§3.5)
//! and the ordered command relay (§3.8). Invariants:
//!
//! - No `godot` dependency (gdext wraps this crate, never the reverse).
//! - No `tokio` type in the public API (OD-R4): the SDK owns its transport
//!   runtime internally; `pump()` polls it with `frame_tick()`.
//! - The game boots and plays single-player with [`StdbMode::Offline`] and no
//!   server running (§3.12 invariant 8).
//!
//! Generated bindings live in [`module_bindings`] (checked in, never hand-edited;
//! regenerate with `server/build.sh`, drift gate `server/build.sh --check`).

pub mod binder;
pub mod config;
pub mod connector;
pub mod identity;
// Generated by `spacetime generate` (authoritative formatting; never hand-edit).
#[rustfmt::skip]
pub mod module_bindings;
pub mod protocol;
pub mod token;
pub mod waves;

pub use binder::{BinderHandle, RowChange, TableBinder};
pub use config::{Backoff, ConnectPolicy, ConnectionConfig, StdbMode};
pub use connector::{Connector, ConnectorError, ConnectorEvent, ConnectorState};
pub use identity::{LocalIdentity, is_player_arg, parse_player_suffix, parse_player_suffix_from};
pub use protocol::{CLIENT_BUILD, PROTOCOL_VERSION, ProtocolError, check_protocol};
pub use token::{FileTokenStore, TokenStore, token_key};
pub use waves::WaveName;

/// Version of the `mind-stdb` crate, taken from `Cargo.toml`.
pub const MIND_VERSION: &str = env!("CARGO_PKG_VERSION");
