// Ported from Mindustry (https://github.com/Anuken/Mindustry) — GPL-3.0.
// SPDX-License-Identifier: GPL-3.0-only

//! Class-ID file tooling (`classids.properties` → `entity_class_ids.toml` +
//! `class_ids.rs`, plan 04 §3.5/§6.4).
//!
//! Append-only discipline (`annotations/AGENTS.md` IDs section): existing
//! names keep their ID; new defs get `max+1` in sorted-name order; keys are
//! then re-sorted. `class_ids.rs` is regenerated by
//! `mind-headless io check-class-ids --update` and committed; the check mode
//! is the drift gate. The TOML reader is a deliberately tiny strict parser for
//! the `[ids]` + `"Name" = N` shape (no TOML dependency in `mind-core`).

use super::super::IoError;
use super::EntityDefMeta;

/// Parsed `entity_class_ids.toml` (sorted by name).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ClassIdFile {
    /// `(name, id)` entries, sorted by name.
    pub entries: Vec<(String, u8)>,
}

impl ClassIdFile {
    /// Parses the strict `[ids]` shape. Any other content is an error — the
    /// file is tool-owned.
    pub fn parse(text: &str) -> Result<Self, IoError> {
        let mut entries = Vec::new();
        let mut seen_header = false;
        for (line_number, raw) in text.lines().enumerate() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if line == "[ids]" {
                if seen_header {
                    return Err(parse_error(line_number, "duplicate [ids] header"));
                }
                seen_header = true;
                continue;
            }
            if !seen_header {
                return Err(parse_error(line_number, "entry before [ids] header"));
            }
            let Some((name, id)) = parse_entry(line) else {
                return Err(parse_error(line_number, "malformed entry"));
            };
            entries.push((name, id));
        }
        if !seen_header {
            return Err(IoError::corrupt(
                "class ids file is missing the [ids] header",
            ));
        }
        // Canonical order is sorted-by-name.
        entries.sort_by(|a, b| a.0.cmp(&b.0));
        // Uniqueness of names and ids.
        for window in entries.windows(2) {
            if window[0].0 == window[1].0 {
                return Err(IoError::corrupt(format!(
                    "duplicate entity def name `{}` in class ids",
                    window[0].0
                )));
            }
        }
        let mut ids = entries.iter().map(|(_, id)| *id).collect::<Vec<_>>();
        ids.sort_unstable();
        for window in ids.windows(2) {
            if window[0] == window[1] {
                return Err(IoError::corrupt(format!(
                    "duplicate entity class id {} in class ids",
                    window[0]
                )));
            }
        }
        Ok(Self { entries })
    }

    /// The id for a def name.
    pub fn id_of(&self, name: &str) -> Option<u8> {
        self.entries
            .iter()
            .find_map(|(n, id)| (n == name).then_some(*id))
    }

    /// Renders the TOML file (canonical form with header comment).
    pub fn render_toml(&self) -> String {
        let mut out = String::from(
            "# Maps entity def names to class IDs. Append-only; regenerated by tooling.\n\
             # Mirrors `annotations/src/main/resources/classids.properties` (bare def names).\n\n\
             [ids]\n",
        );
        for (name, id) in &self.entries {
            out.push_str(&format!("\"{name}\" = {id}\n"));
        }
        out
    }

    /// Renders the generated `class_ids.rs` constants file.
    pub fn render_rs(&self) -> String {
        let mut out = String::from(
            "// GENERATED from `client/rust/mind-core/entity_class_ids.toml` by\n\
             // `mind-headless io check-class-ids --update` — do not hand-edit.\n\
             // Append-only (mirrors `classids.properties`); never renumber.\n\
             #![allow(dead_code)]\n\n",
        );
        for (name, id) in &self.entries {
            out.push_str(&format!(
                "/// Class ID of `{name}`.\npub const {}: u8 = {id};\n",
                screaming_snake(name)
            ));
        }
        out
    }

    /// Validates registry defs against the file (check mode problems).
    pub fn problems(&self, defs: &[EntityDefMeta]) -> Vec<String> {
        let mut problems = Vec::new();
        for def in defs {
            match self.id_of(def.name) {
                None => problems.push(format!(
                    "entity def `{}` (class id {}) is missing from entity_class_ids.toml",
                    def.name, def.class_id
                )),
                Some(id) if id != def.class_id => problems.push(format!(
                    "entity def `{}` has class id {} but entity_class_ids.toml says {} (renumbering is forbidden)",
                    def.name, def.class_id, id
                )),
                Some(_) => {}
            }
        }
        problems
    }

    /// Appends missing defs at `max+1` in sorted-name order (upstream
    /// `EntityProcess` rule), returning the updated file.
    pub fn with_new_defs(&self, defs: &[EntityDefMeta]) -> Self {
        let mut new_names: Vec<&str> = defs
            .iter()
            .map(|def| def.name)
            .filter(|name| self.id_of(name).is_none())
            .collect();
        new_names.sort_unstable();
        new_names.dedup();
        let mut entries = self.entries.clone();
        let mut next = entries.iter().map(|(_, id)| *id).max().unwrap_or(0);
        if !entries.is_empty() {
            next = next.saturating_add(1);
        }
        for name in new_names {
            entries.push((name.to_owned(), next));
            next = next.saturating_add(1);
        }
        entries.sort_by(|a, b| a.0.cmp(&b.0));
        Self { entries }
    }
}

fn parse_error(line_number: usize, message: &str) -> IoError {
    IoError::corrupt(format!(
        "entity_class_ids.toml line {}: {message}",
        line_number + 1
    ))
}

fn parse_entry(line: &str) -> Option<(String, u8)> {
    let (name, value) = line.split_once('=')?;
    let name = name.trim();
    let name = name.strip_prefix('"')?.strip_suffix('"')?;
    let id: u8 = value.trim().parse().ok()?;
    Some((name.to_owned(), id))
}

/// `BuildingComp` → `BUILDING_COMP` (must match the `mind-derive` conversion).
pub fn screaming_snake(name: &str) -> String {
    let mut out = String::new();
    for (index, ch) in name.chars().enumerate() {
        if ch.is_ascii_uppercase() && index > 0 {
            out.push('_');
        }
        out.push(ch);
    }
    out.to_uppercase()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::io::entity::{FieldDesc, SyncFieldMeta};

    const SAMPLE: &str = "# comment\n\n[ids]\n\"BuildingComp\" = 6\n\"alpha\" = 0\n\"block\" = 2\n";

    fn meta(name: &'static str, class_id: u8) -> EntityDefMeta {
        EntityDefMeta {
            name,
            class_id,
            serialize: true,
            sync: true,
            fields: &[] as &[FieldDesc],
            sync_fields: &[] as &[SyncFieldMeta],
        }
    }

    /// `io::entity` class-ID append-only test (plan 04 §7a).
    #[test]
    fn class_ids_append_only() {
        let file = ClassIdFile::parse(SAMPLE).unwrap();
        assert_eq!(file.id_of("BuildingComp"), Some(6));
        assert_eq!(file.id_of("alpha"), Some(0));
        // Sorted on parse.
        assert_eq!(file.entries[0].0, "BuildingComp");

        // Existing names keep ids; new defs get max+1 in sorted-name order.
        let updated = file.with_new_defs(&[meta("zebra", 0), meta("apple", 0)]);
        assert_eq!(updated.id_of("BuildingComp"), Some(6));
        assert_eq!(updated.id_of("apple"), Some(7));
        assert_eq!(updated.id_of("zebra"), Some(8));

        // Duplicate names and ids are rejected.
        assert!(ClassIdFile::parse("[ids]\n\"a\" = 1\n\"a\" = 2\n").is_err());
        assert!(ClassIdFile::parse("[ids]\n\"a\" = 1\n\"b\" = 1\n").is_err());

        // Registry problems surface.
        let problems = file.problems(&[meta("BuildingComp", 7), meta("Missing", 0)]);
        assert_eq!(problems.len(), 2);
        assert!(problems[0].contains("renumbering is forbidden"));
        assert!(problems[1].contains("missing"));
        assert!(file.problems(&[meta("BuildingComp", 6)]).is_empty());
    }

    #[test]
    fn render_roundtrip_and_screaming_snake() {
        let file = ClassIdFile::parse(SAMPLE).unwrap();
        let rendered = file.render_toml();
        let reparsed = ClassIdFile::parse(&rendered).unwrap();
        assert_eq!(file, reparsed);
        assert_eq!(screaming_snake("BuildingComp"), "BUILDING_COMP");
        assert_eq!(screaming_snake("alpha"), "ALPHA");
        let rs = file.render_rs();
        assert!(rs.contains("pub const BUILDING_COMP: u8 = 6;"));
        assert!(rs.contains("pub const ALPHA: u8 = 0;"));
    }
}
