// SPDX-License-Identifier: GPL-3.0-only

//! Migration trim rules shared by `mind-tools migrate` and the
//! `mind-headless assets migrate-check` verifier (plan 03 M0).
//!
//! The rules mirror `core/assets/AGENTS.md` + `core/assets-raw/AGENTS.md`:
//! generated files are never vendored — they are regenerated by
//! `mind-tools pack` (or, for `logicids.dat`/`version.properties`/
//! `basepartnames`, dropped entirely per plan 03 §2.3 A4 and §M0 trim list).

/// Returns true when `rel` (a `/`-normalized path relative to `core/assets`
/// or `core/assets-raw`) must be excluded from migration and from manifest
/// verification.
pub fn trim_exclude(rel: &str, is_dir: bool) -> bool {
    // Upstream documentation files describe the Java pipeline; this repo keeps
    // its own docs (assets/ASSET_PROVENANCE.md points at them).
    if rel == "AGENTS.md" {
        return true;
    }
    if is_dir {
        return matches!(
            rel,
            // generated pack outputs (atlas pages live beside loose textures)
            "sprites/fallback"
            // generated bundle scratch
            | "bundles/output"
            // Arc asset-manager cache
            | "cache"
            // assets-raw staging area recreated by every pack run
            | "sprites_out"
            // fontgen working dirs (regenerated by the upstream icon pipeline)
            | "fontgen/out"
            | "fontgen/icons"
            | "fontgen/icon_parts"
        );
    }
    let file = rel.rsplit('/').next().unwrap_or(rel);
    if matches!(
        rel,
        // Anuken-only generated logic ID map (plan 03 §2.3 A4)
        "logicids.dat"
        // regenerated by every pack
        | "version.properties"
        | "locales"
        | "basepartnames"
        | "sprites/block_colors.png"
        // generated at pack time by mind-tools ids (M4)
        | "sounds.index.json"
        | "icons/icon_codes.json"
        | "shaders/shader.index.json"
    ) {
        return true;
    }
    // Generated atlas manifests/pages under sprites/ (upstream `sprites.aatls`
    // and `sprites.png`, `sprites2.png`, ...; loose textures keep their names).
    if file == "sprites.aatls" || file == "sprites.atlas.json" {
        return true;
    }
    if let Some(parent) = rel.strip_prefix("sprites/")
        && !parent.contains('/')
        && is_generated_page(file)
    {
        return true;
    }
    // `assets/shaders/godot/` copies are produced by `mind-tools shaders build`.
    if rel.starts_with("shaders/godot/") {
        return true;
    }
    false
}

/// `sprites.png`, `sprites2.png`, ... — generated atlas page file names.
fn is_generated_page(file: &str) -> bool {
    let Some(stem) = file.strip_prefix("sprites") else {
        return false;
    };
    let Some(digits) = stem.strip_suffix(".png") else {
        return false;
    };
    digits.bytes().all(|b| b.is_ascii_digit())
}

/// Files that must never exist in the migrated/vendored tree (checked by
/// `migrate-check`; upstream-generated or Anuken-only).
pub const FORBIDDEN_GENERATED: &[&str] = &[
    "logicids.dat",
    "version.properties",
    "locales",
    "basepartnames",
    "sprites/sprites.aatls",
    "sprites/block_colors.png",
];

/// Migration manifest covering both vendored trees
/// (`build/assets/migration_manifest.json`).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct MigrationManifest {
    /// Manifest format version.
    pub format: u32,
    /// Upstream commit the trees were migrated from (`unknown` when the source
    /// is not a git checkout).
    pub upstream_commit: String,
    /// `assets/` tree hashes (excluding `ASSET_PROVENANCE.md`).
    pub assets: crate::manifest::TreeManifest,
    /// `assets-raw/` tree hashes.
    pub assets_raw: crate::manifest::TreeManifest,
}

impl MigrationManifest {
    /// Builds the manifest over a migrated repo root (`to`).
    pub fn build(to: &std::path::Path, upstream_commit: String) -> crate::error::Result<Self> {
        let assets = crate::manifest::TreeManifest::build(
            &to.join("assets"),
            "assets",
            Some(upstream_commit.clone()),
            |p, d| trim_exclude(p, d) || p == "ASSET_PROVENANCE.md",
        )?;
        let assets_raw = crate::manifest::TreeManifest::build(
            &to.join("assets-raw"),
            "assets-raw",
            None,
            trim_exclude,
        )?;
        Ok(Self {
            format: 1,
            upstream_commit,
            assets,
            assets_raw,
        })
    }

    /// Total migrated file count.
    pub fn file_count(&self) -> usize {
        self.assets.files.len() + self.assets_raw.files.len()
    }

    /// Combined sha256 over both trees (recorded in `ASSET_PROVENANCE.md`).
    pub fn tree_hash(&self) -> String {
        let mut files = self.assets.files.clone();
        files.extend(self.assets_raw.files.iter().cloned());
        crate::manifest::combined_hash(&files)
    }

    /// Writes pretty JSON.
    pub fn write(&self, path: &std::path::Path) -> crate::error::Result<()> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, format!("{}\n", serde_json::to_string_pretty(self)?))?;
        Ok(())
    }

    /// Reads a manifest written by [`MigrationManifest::write`].
    pub fn read(path: &std::path::Path) -> crate::error::Result<Self> {
        let text = std::fs::read_to_string(path)?;
        Ok(serde_json::from_str(&text)?)
    }

    /// Verifies a repo root against this manifest: per-file drift plus
    /// forbidden generated files. Returns human-readable problems, sorted.
    pub fn verify(&self, to: &std::path::Path) -> crate::error::Result<Vec<String>> {
        let mut problems = self.assets.verify(&to.join("assets"), |p, d| {
            trim_exclude(p, d) || p == "ASSET_PROVENANCE.md"
        })?;
        problems.extend(
            self.assets_raw
                .verify(&to.join("assets-raw"), trim_exclude)?,
        );
        for forbidden in FORBIDDEN_GENERATED {
            if to.join("assets").join(forbidden).exists() {
                problems.push(format!("forbidden file present: assets/{forbidden}"));
            }
        }
        problems.sort();
        Ok(problems)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn trim_rules_match_upstream_generated_set() {
        assert!(trim_exclude("logicids.dat", false));
        assert!(trim_exclude("version.properties", false));
        assert!(trim_exclude("locales", false));
        assert!(trim_exclude("basepartnames", false));
        assert!(trim_exclude("sprites/sprites.aatls", false));
        assert!(trim_exclude("sprites/sprites.png", false));
        assert!(trim_exclude("sprites/sprites12.png", false));
        assert!(trim_exclude("sprites/fallback", true));
        assert!(trim_exclude("sprites/block_colors.png", false));
        assert!(trim_exclude("bundles/output", true));
        assert!(trim_exclude("sprites_out", true));
        assert!(trim_exclude("AGENTS.md", false));

        // Loose textures and hand-authored sources are kept.
        assert!(!trim_exclude("sprites/error.png", false));
        assert!(!trim_exclude("sprites/noise.png", false));
        assert!(!trim_exclude("sprites/planets", true));
        assert!(!trim_exclude("bundles/bundle.properties", false));
        assert!(!trim_exclude("sprites/pack.json", false));
        assert!(!trim_exclude("blocks/environment/pack.json", false));
        assert!(!trim_exclude("icons/icons.properties", false));
    }
}
