// Ported from Mindustry (https://github.com/Anuken/Mindustry) — GPL-3.0.
// SPDX-License-Identifier: GPL-3.0-only

//! `ShaderRegistry` — plan-03 `shader.index.json` consumption + fallbacks
//! (plan 16 §3.9 / M8).
//!
//! Each logical `Shaders.*` key (plus the `default`/`cubemap` helpers) is loaded
//! from the ported `client/shaders/*.gdshader` sources copied into the asset
//! tree by `mind-tools shaders build`. A missing or failed shader logs `[E]`
//! and increments the substitution counter; `shield` is nullable, matching
//! `Renderer.java:403` (a missing shield skips the composite entirely).

use std::collections::BTreeMap;

use godot::classes::{FileAccess, Shader};
use godot::obj::NewGd;
use godot::prelude::*;

use mind_core::render::shaders as core_shaders;

/// Loads and owns the ported Godot shaders.
#[derive(Default)]
pub struct ShaderRegistry {
    shaders: BTreeMap<String, Gd<Shader>>,
    missing: Vec<String>,
    substitutions: i64,
    manifest_loaded: bool,
    neutral: Option<Gd<Shader>>,
}

impl ShaderRegistry {
    /// Creates an empty registry.
    pub fn new() -> Self {
        Self::default()
    }

    /// Loads every required shader through the plan-03 index.
    ///
    /// `assets_dir` is the resolved asset root (plan 03 §3.2); when `None` the
    /// committed `res://shaders/` copy is used directly. Returns whether the
    /// index was found.
    pub fn load(&mut self, assets_dir: Option<&str>) -> bool {
        self.shaders.clear();
        self.missing.clear();
        self.substitutions = 0;
        self.manifest_loaded = false;

        let dir = assets_dir.unwrap_or("").trim_end_matches('/').to_owned();
        let manifest = if dir.is_empty() {
            String::from("res://assets/shaders/shader.index.json")
        } else {
            format!("{dir}/shaders/shader.index.json")
        };

        // Manifest → logical name → relative gdshader path. The index is
        // generated by `mind-tools shaders build` (plan 03 §6.7).
        let mut entries: BTreeMap<String, String> = BTreeMap::new();
        if FileAccess::file_exists(&manifest) {
            self.manifest_loaded = true;
            let text = FileAccess::get_file_as_string(&manifest).to_string();
            if let Ok(value) = serde_json::from_str::<serde_json::Value>(&text)
                && let Some(list) = value.get("shaders").and_then(|v| v.as_array())
            {
                for entry in list {
                    let (Some(name), Some(path)) = (
                        entry.get("name").and_then(|v| v.as_str()),
                        entry.get("gdshader").and_then(|v| v.as_str()),
                    ) else {
                        continue;
                    };
                    entries.insert(name.to_owned(), path.to_owned());
                }
            }
        } else {
            log::warn!("[shaders] index missing: {manifest}");
        }

        let mut names: Vec<&str> = core_shaders::EXPECTED
            .iter()
            .map(|entry| entry.name)
            .collect();
        names.extend_from_slice(core_shaders::AUXILIARY);

        for name in names {
            let candidates = shader_candidates(name, entries.get(name).map(String::as_str), &dir);
            let mut loaded = None;
            for path in &candidates {
                if !FileAccess::file_exists(path) {
                    continue;
                }
                let code = FileAccess::get_file_as_string(path);
                if code.is_empty() {
                    continue;
                }
                let mut shader = Shader::new_gd();
                shader.set_code(&code);
                loaded = Some(shader);
                break;
            }
            match loaded {
                Some(shader) => {
                    self.shaders.insert(name.to_owned(), shader);
                }
                None => {
                    let nullable = core_shaders::is_nullable(name);
                    log::error!(
                        "[E] [shaders] missing `{name}`{}; using neutral substitute",
                        if nullable { " (nullable)" } else { "" }
                    );
                    self.missing.push(name.to_owned());
                    self.substitutions += 1;
                }
            }
        }

        // Neutral substitute = `screenspace` (pass-through canvas blit).
        self.neutral = self.shaders.get("screenspace").cloned();
        self.manifest_loaded
    }

    /// The shader for a logical name, if loaded.
    #[allow(dead_code)] // consumed by the M3/M5 composite passes.
    pub fn get(&self, name: &str) -> Option<Gd<Shader>> {
        self.shaders.get(name).cloned()
    }

    /// Whether a shader loaded (used for the nullable `shield` skip).
    #[allow(dead_code)] // consumed by the M5 shield/buildBeam bracket.
    pub fn has(&self, name: &str) -> bool {
        self.shaders.contains_key(name)
    }

    /// Number of loaded shaders.
    pub fn loaded(&self) -> usize {
        self.shaders.len()
    }

    /// Missing-shader substitutions this session.
    pub fn substitutions(&self) -> i64 {
        self.substitutions
    }

    /// Names that fell back to the neutral shader.
    pub fn missing(&self) -> &[String] {
        &self.missing
    }

    /// Whether the plan-03 index was found.
    pub fn manifest_loaded(&self) -> bool {
        self.manifest_loaded
    }

    /// Pass-through neutral canvas shader.
    #[allow(dead_code)] // consumed by the M8 fallback path tests / M3 passes.
    pub fn neutral(&self) -> Option<Gd<Shader>> {
        self.neutral.clone()
    }
}

/// Candidate paths for a logical shader name, most-specific first.
fn shader_candidates(name: &str, manifest_rel: Option<&str>, dir: &str) -> Vec<String> {
    let mut out = Vec::new();
    if let Some(rel) = manifest_rel
        && !dir.is_empty()
    {
        out.push(format!("{dir}/{rel}"));
    }
    if !dir.is_empty() {
        out.push(format!("{dir}/shaders/godot/{name}.gdshader"));
    }
    out.push(format!("res://shaders/{name}.gdshader"));
    out
}
