// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminBanArgs {
    pub target: __sdk::Identity,
    pub reason: String,
    pub duration_secs: Option<u64>,
}

impl From<AdminBanArgs> for super::Reducer {
    fn from(args: AdminBanArgs) -> Self {
        Self::AdminBan {
            target: args.target,
            reason: args.reason,
            duration_secs: args.duration_secs,
        }
    }
}

impl __sdk::InModule for AdminBanArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_ban`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_ban {
    /// Request that the remote module invoke the reducer `admin_ban` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_ban:admin_ban_then`] to run a callback after the reducer completes.
    fn admin_ban(
        &self,
        target: __sdk::Identity,
        reason: String,
        duration_secs: Option<u64>,
    ) -> __sdk::Result<()> {
        self.admin_ban_then(target, reason, duration_secs, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_ban` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_ban_then(
        &self,
        target: __sdk::Identity,
        reason: String,
        duration_secs: Option<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_ban for super::RemoteReducers {
    fn admin_ban_then(
        &self,
        target: __sdk::Identity,
        reason: String,
        duration_secs: Option<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AdminBanArgs {
                target,
                reason,
                duration_secs,
            },
            callback,
        )
    }
}
