// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminTileOpArgs {
    pub match_id: u64,
    pub op: u8,
    pub points: Vec<i32>,
    pub arg_0: i32,
    pub arg_1: i32,
    pub arg_2: i32,
    pub name_0: Option<String>,
    pub name_1: Option<String>,
}

impl From<AdminTileOpArgs> for super::Reducer {
    fn from(args: AdminTileOpArgs) -> Self {
        Self::AdminTileOp {
            match_id: args.match_id,
            op: args.op,
            points: args.points,
            arg_0: args.arg_0,
            arg_1: args.arg_1,
            arg_2: args.arg_2,
            name_0: args.name_0,
            name_1: args.name_1,
        }
    }
}

impl __sdk::InModule for AdminTileOpArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_tile_op`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_tile_op {
    /// Request that the remote module invoke the reducer `admin_tile_op` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_tile_op:admin_tile_op_then`] to run a callback after the reducer completes.
    fn admin_tile_op(
        &self,
        match_id: u64,
        op: u8,
        points: Vec<i32>,
        arg_0: i32,
        arg_1: i32,
        arg_2: i32,
        name_0: Option<String>,
        name_1: Option<String>,
    ) -> __sdk::Result<()> {
        self.admin_tile_op_then(
            match_id,
            op,
            points,
            arg_0,
            arg_1,
            arg_2,
            name_0,
            name_1,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `admin_tile_op` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_tile_op_then(
        &self,
        match_id: u64,
        op: u8,
        points: Vec<i32>,
        arg_0: i32,
        arg_1: i32,
        arg_2: i32,
        name_0: Option<String>,
        name_1: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_tile_op for super::RemoteReducers {
    fn admin_tile_op_then(
        &self,
        match_id: u64,
        op: u8,
        points: Vec<i32>,
        arg_0: i32,
        arg_1: i32,
        arg_2: i32,
        name_0: Option<String>,
        name_1: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AdminTileOpArgs {
                match_id,
                op,
                points,
                arg_0,
                arg_1,
                arg_2,
                name_0,
                name_1,
            },
            callback,
        )
    }
}
