// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminSetConfigArgs {
    pub field: String,
    pub value: String,
}

impl From<AdminSetConfigArgs> for super::Reducer {
    fn from(args: AdminSetConfigArgs) -> Self {
        Self::AdminSetConfig {
            field: args.field,
            value: args.value,
        }
    }
}

impl __sdk::InModule for AdminSetConfigArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_set_config`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_set_config {
    /// Request that the remote module invoke the reducer `admin_set_config` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_set_config:admin_set_config_then`] to run a callback after the reducer completes.
    fn admin_set_config(&self, field: String, value: String) -> __sdk::Result<()> {
        self.admin_set_config_then(field, value, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_set_config` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_set_config_then(
        &self,
        field: String,
        value: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_set_config for super::RemoteReducers {
    fn admin_set_config_then(
        &self,
        field: String,
        value: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdminSetConfigArgs { field, value }, callback)
    }
}
