// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminKickArgs {
    pub match_id: u64,
    pub target: __sdk::Identity,
    pub reason: String,
}

impl From<AdminKickArgs> for super::Reducer {
    fn from(args: AdminKickArgs) -> Self {
        Self::AdminKick {
            match_id: args.match_id,
            target: args.target,
            reason: args.reason,
        }
    }
}

impl __sdk::InModule for AdminKickArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_kick`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_kick {
    /// Request that the remote module invoke the reducer `admin_kick` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_kick:admin_kick_then`] to run a callback after the reducer completes.
    fn admin_kick(
        &self,
        match_id: u64,
        target: __sdk::Identity,
        reason: String,
    ) -> __sdk::Result<()> {
        self.admin_kick_then(match_id, target, reason, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_kick` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_kick_then(
        &self,
        match_id: u64,
        target: __sdk::Identity,
        reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_kick for super::RemoteReducers {
    fn admin_kick_then(
        &self,
        match_id: u64,
        target: __sdk::Identity,
        reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AdminKickArgs {
                match_id,
                target,
                reason,
            },
            callback,
        )
    }
}
