// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AdminRate {
    pub identity: __sdk::Identity,
    pub window_start: __sdk::Timestamp,
    pub actions: u32,
}

impl __sdk::InModule for AdminRate {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AdminRate`.
///
/// Provides typed access to columns for query building.
pub struct AdminRateCols {
    pub identity: __sdk::__query_builder::Col<AdminRate, __sdk::Identity>,
    pub window_start: __sdk::__query_builder::Col<AdminRate, __sdk::Timestamp>,
    pub actions: __sdk::__query_builder::Col<AdminRate, u32>,
}

impl __sdk::__query_builder::HasCols for AdminRate {
    type Cols = AdminRateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AdminRateCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            window_start: __sdk::__query_builder::Col::new(table_name, "window_start"),
            actions: __sdk::__query_builder::Col::new(table_name, "actions"),
        }
    }
}

/// Indexed column accessor struct for the table `AdminRate`.
///
/// Provides typed access to indexed columns for query building.
pub struct AdminRateIxCols {
    pub identity: __sdk::__query_builder::IxCol<AdminRate, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for AdminRate {
    type IxCols = AdminRateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AdminRateIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AdminRate {}
