// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdvanceTurnArgs {
    pub campaign_id: u64,
}

impl From<AdvanceTurnArgs> for super::Reducer {
    fn from(args: AdvanceTurnArgs) -> Self {
        Self::AdvanceTurn {
            campaign_id: args.campaign_id,
        }
    }
}

impl __sdk::InModule for AdvanceTurnArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `advance_turn`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait advance_turn {
    /// Request that the remote module invoke the reducer `advance_turn` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`advance_turn:advance_turn_then`] to run a callback after the reducer completes.
    fn advance_turn(&self, campaign_id: u64) -> __sdk::Result<()> {
        self.advance_turn_then(campaign_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `advance_turn` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn advance_turn_then(
        &self,
        campaign_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl advance_turn for super::RemoteReducers {
    fn advance_turn_then(
        &self,
        campaign_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AdvanceTurnArgs { campaign_id }, callback)
    }
}
