// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_type::Player;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `all_players`.
///
/// Obtain a handle from the [`AllPlayersTableAccess::all_players`] method on [`super::RemoteTables`],
/// like `ctx.db.all_players()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.all_players().on_insert(...)`.
pub struct AllPlayersTableHandle<'ctx> {
    imp: __sdk::TableHandle<Player>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `all_players`.
pub struct AllPlayersTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AllPlayersTableAccessor {
    type Row = Player;
    type Handle<'db> = AllPlayersTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.all_players()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `all_players`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AllPlayersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AllPlayersTableHandle`], which mediates access to the table `all_players`.
    fn all_players(&self) -> AllPlayersTableHandle<'_>;
}

impl AllPlayersTableAccess for super::RemoteTables {
    fn all_players(&self) -> AllPlayersTableHandle<'_> {
        AllPlayersTableHandle {
            imp: self.imp.get_table::<Player>("all_players"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AllPlayersInsertCallbackId(__sdk::CallbackId);
pub struct AllPlayersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AllPlayersTableHandle<'ctx> {
    type Row = Player;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Player> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AllPlayersTableHandle<'ctx> {
    type Row = Player;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Player> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AllPlayersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AllPlayersInsertCallbackId {
        AllPlayersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AllPlayersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AllPlayersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AllPlayersDeleteCallbackId {
        AllPlayersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AllPlayersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AllPlayersTableHandle<'ctx> {
    type InsertCallbackId = AllPlayersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AllPlayersInsertCallbackId {
        AllPlayersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AllPlayersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AllPlayersTableHandle<'ctx> {
    type DeleteCallbackId = AllPlayersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AllPlayersDeleteCallbackId {
        AllPlayersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AllPlayersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AllPlayersUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AllPlayersTableHandle<'ctx> {
    type UpdateCallbackId = AllPlayersUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AllPlayersUpdateCallbackId {
        AllPlayersUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AllPlayersUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for AllPlayersTableHandle<'ctx> {
    type UpdateCallbackId = AllPlayersUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AllPlayersUpdateCallbackId {
        AllPlayersUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AllPlayersUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `all_players`,
/// which allows point queries on the field of the same name
/// via the [`AllPlayersIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.all_players().identity().find(...)`.
pub struct AllPlayersIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Player, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AllPlayersTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `all_players`.
    pub fn identity(&self) -> AllPlayersIdentityUnique<'ctx> {
        AllPlayersIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AllPlayersIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Player> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Player>("all_players");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Player>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Player>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Player`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait all_playersQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Player`.
    fn all_players(&self) -> __sdk::__query_builder::Table<Player>;
}

impl all_playersQueryTableAccess for __sdk::QueryTableAccessor {
    fn all_players(&self) -> __sdk::__query_builder::Table<Player> {
        __sdk::__query_builder::Table::new("all_players")
    }
}
