// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::chat_filter_type::ChatFilter;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `all_chat_filters`.
///
/// Obtain a handle from the [`AllChatFiltersTableAccess::all_chat_filters`] method on [`super::RemoteTables`],
/// like `ctx.db.all_chat_filters()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.all_chat_filters().on_insert(...)`.
pub struct AllChatFiltersTableHandle<'ctx> {
    imp: __sdk::TableHandle<ChatFilter>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `all_chat_filters`.
pub struct AllChatFiltersTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AllChatFiltersTableAccessor {
    type Row = ChatFilter;
    type Handle<'db> = AllChatFiltersTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.all_chat_filters()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `all_chat_filters`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AllChatFiltersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AllChatFiltersTableHandle`], which mediates access to the table `all_chat_filters`.
    fn all_chat_filters(&self) -> AllChatFiltersTableHandle<'_>;
}

impl AllChatFiltersTableAccess for super::RemoteTables {
    fn all_chat_filters(&self) -> AllChatFiltersTableHandle<'_> {
        AllChatFiltersTableHandle {
            imp: self.imp.get_table::<ChatFilter>("all_chat_filters"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AllChatFiltersInsertCallbackId(__sdk::CallbackId);
pub struct AllChatFiltersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AllChatFiltersTableHandle<'ctx> {
    type Row = ChatFilter;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChatFilter> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AllChatFiltersTableHandle<'ctx> {
    type Row = ChatFilter;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChatFilter> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AllChatFiltersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AllChatFiltersInsertCallbackId {
        AllChatFiltersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AllChatFiltersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AllChatFiltersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AllChatFiltersDeleteCallbackId {
        AllChatFiltersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AllChatFiltersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AllChatFiltersTableHandle<'ctx> {
    type InsertCallbackId = AllChatFiltersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AllChatFiltersInsertCallbackId {
        AllChatFiltersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AllChatFiltersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AllChatFiltersTableHandle<'ctx> {
    type DeleteCallbackId = AllChatFiltersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AllChatFiltersDeleteCallbackId {
        AllChatFiltersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AllChatFiltersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ChatFilter>("all_chat_filters");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ChatFilter>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ChatFilter>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ChatFilter`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait all_chat_filtersQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ChatFilter`.
    fn all_chat_filters(&self) -> __sdk::__query_builder::Table<ChatFilter>;
}

impl all_chat_filtersQueryTableAccess for __sdk::QueryTableAccessor {
    fn all_chat_filters(&self) -> __sdk::__query_builder::Table<ChatFilter> {
        __sdk::__query_builder::Table::new("all_chat_filters")
    }
}
