// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::authority_mode_type::AuthorityMode;
use super::gamemode_type::Gamemode;
use super::match_status_type::MatchStatus;
use super::relay_match_type::RelayMatch;
use super::visibility_type::Visibility;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `all_matches`.
///
/// Obtain a handle from the [`AllMatchesTableAccess::all_matches`] method on [`super::RemoteTables`],
/// like `ctx.db.all_matches()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.all_matches().on_insert(...)`.
pub struct AllMatchesTableHandle<'ctx> {
    imp: __sdk::TableHandle<RelayMatch>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `all_matches`.
pub struct AllMatchesTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AllMatchesTableAccessor {
    type Row = RelayMatch;
    type Handle<'db> = AllMatchesTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.all_matches()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `all_matches`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AllMatchesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AllMatchesTableHandle`], which mediates access to the table `all_matches`.
    fn all_matches(&self) -> AllMatchesTableHandle<'_>;
}

impl AllMatchesTableAccess for super::RemoteTables {
    fn all_matches(&self) -> AllMatchesTableHandle<'_> {
        AllMatchesTableHandle {
            imp: self.imp.get_table::<RelayMatch>("all_matches"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AllMatchesInsertCallbackId(__sdk::CallbackId);
pub struct AllMatchesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AllMatchesTableHandle<'ctx> {
    type Row = RelayMatch;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RelayMatch> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AllMatchesTableHandle<'ctx> {
    type Row = RelayMatch;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RelayMatch> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AllMatchesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AllMatchesInsertCallbackId {
        AllMatchesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AllMatchesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AllMatchesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AllMatchesDeleteCallbackId {
        AllMatchesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AllMatchesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AllMatchesTableHandle<'ctx> {
    type InsertCallbackId = AllMatchesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AllMatchesInsertCallbackId {
        AllMatchesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AllMatchesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AllMatchesTableHandle<'ctx> {
    type DeleteCallbackId = AllMatchesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AllMatchesDeleteCallbackId {
        AllMatchesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AllMatchesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RelayMatch>("all_matches");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RelayMatch>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RelayMatch>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RelayMatch`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait all_matchesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RelayMatch`.
    fn all_matches(&self) -> __sdk::__query_builder::Table<RelayMatch>;
}

impl all_matchesQueryTableAccess for __sdk::QueryTableAccessor {
    fn all_matches(&self) -> __sdk::__query_builder::Table<RelayMatch> {
        __sdk::__query_builder::Table::new("all_matches")
    }
}
