// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::chat_filter_type::ChatFilter;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `chat_filter`.
///
/// Obtain a handle from the [`ChatFilterTableAccess::chat_filter`] method on [`super::RemoteTables`],
/// like `ctx.db.chat_filter()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chat_filter().on_insert(...)`.
pub struct ChatFilterTableHandle<'ctx> {
    imp: __sdk::TableHandle<ChatFilter>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `chat_filter`.
pub struct ChatFilterTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ChatFilterTableAccessor {
    type Row = ChatFilter;
    type Handle<'db> = ChatFilterTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.chat_filter()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `chat_filter`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ChatFilterTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ChatFilterTableHandle`], which mediates access to the table `chat_filter`.
    fn chat_filter(&self) -> ChatFilterTableHandle<'_>;
}

impl ChatFilterTableAccess for super::RemoteTables {
    fn chat_filter(&self) -> ChatFilterTableHandle<'_> {
        ChatFilterTableHandle {
            imp: self.imp.get_table::<ChatFilter>("chat_filter"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ChatFilterInsertCallbackId(__sdk::CallbackId);
pub struct ChatFilterDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ChatFilterTableHandle<'ctx> {
    type Row = ChatFilter;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChatFilter> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ChatFilterTableHandle<'ctx> {
    type Row = ChatFilter;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ChatFilter> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ChatFilterInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChatFilterInsertCallbackId {
        ChatFilterInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChatFilterInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ChatFilterDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChatFilterDeleteCallbackId {
        ChatFilterDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChatFilterDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ChatFilterTableHandle<'ctx> {
    type InsertCallbackId = ChatFilterInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChatFilterInsertCallbackId {
        ChatFilterInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ChatFilterInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ChatFilterTableHandle<'ctx> {
    type DeleteCallbackId = ChatFilterDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ChatFilterDeleteCallbackId {
        ChatFilterDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ChatFilterDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ChatFilterUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ChatFilterTableHandle<'ctx> {
    type UpdateCallbackId = ChatFilterUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChatFilterUpdateCallbackId {
        ChatFilterUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChatFilterUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ChatFilterTableHandle<'ctx> {
    type UpdateCallbackId = ChatFilterUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ChatFilterUpdateCallbackId {
        ChatFilterUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ChatFilterUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `filter_id` unique index on the table `chat_filter`,
/// which allows point queries on the field of the same name
/// via the [`ChatFilterFilterIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.chat_filter().filter_id().find(...)`.
pub struct ChatFilterFilterIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ChatFilter, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ChatFilterTableHandle<'ctx> {
    /// Get a handle on the `filter_id` unique index on the table `chat_filter`.
    pub fn filter_id(&self) -> ChatFilterFilterIdUnique<'ctx> {
        ChatFilterFilterIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("filter_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ChatFilterFilterIdUnique<'ctx> {
    /// Find the subscribed row whose `filter_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ChatFilter> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ChatFilter>("chat_filter");
    _table.add_unique_constraint::<u64>("filter_id", |row| &row.filter_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ChatFilter>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ChatFilter>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ChatFilter`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait chat_filterQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ChatFilter`.
    fn chat_filter(&self) -> __sdk::__query_builder::Table<ChatFilter>;
}

impl chat_filterQueryTableAccess for __sdk::QueryTableAccessor {
    fn chat_filter(&self) -> __sdk::__query_builder::Table<ChatFilter> {
        __sdk::__query_builder::Table::new("chat_filter")
    }
}
