// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ClientSettings {
    pub identity: __sdk::Identity,
    pub ui_scale: f32,
    pub language: String,
    pub music_volume: f32,
    pub sfx_volume: f32,
    pub keybinds_json: String,
    pub revision: u32,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for ClientSettings {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ClientSettings`.
///
/// Provides typed access to columns for query building.
pub struct ClientSettingsCols {
    pub identity: __sdk::__query_builder::Col<ClientSettings, __sdk::Identity>,
    pub ui_scale: __sdk::__query_builder::Col<ClientSettings, f32>,
    pub language: __sdk::__query_builder::Col<ClientSettings, String>,
    pub music_volume: __sdk::__query_builder::Col<ClientSettings, f32>,
    pub sfx_volume: __sdk::__query_builder::Col<ClientSettings, f32>,
    pub keybinds_json: __sdk::__query_builder::Col<ClientSettings, String>,
    pub revision: __sdk::__query_builder::Col<ClientSettings, u32>,
    pub updated_at: __sdk::__query_builder::Col<ClientSettings, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ClientSettings {
    type Cols = ClientSettingsCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ClientSettingsCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            ui_scale: __sdk::__query_builder::Col::new(table_name, "ui_scale"),
            language: __sdk::__query_builder::Col::new(table_name, "language"),
            music_volume: __sdk::__query_builder::Col::new(table_name, "music_volume"),
            sfx_volume: __sdk::__query_builder::Col::new(table_name, "sfx_volume"),
            keybinds_json: __sdk::__query_builder::Col::new(table_name, "keybinds_json"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ClientSettings`.
///
/// Provides typed access to indexed columns for query building.
pub struct ClientSettingsIxCols {
    pub identity: __sdk::__query_builder::IxCol<ClientSettings, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for ClientSettings {
    type IxCols = ClientSettingsIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ClientSettingsIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ClientSettings {}
