// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ContentCatalog {
    pub content_id: u64,
    pub name: String,
    pub content_type: u8,
    pub source_mod: String,
}

impl __sdk::InModule for ContentCatalog {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ContentCatalog`.
///
/// Provides typed access to columns for query building.
pub struct ContentCatalogCols {
    pub content_id: __sdk::__query_builder::Col<ContentCatalog, u64>,
    pub name: __sdk::__query_builder::Col<ContentCatalog, String>,
    pub content_type: __sdk::__query_builder::Col<ContentCatalog, u8>,
    pub source_mod: __sdk::__query_builder::Col<ContentCatalog, String>,
}

impl __sdk::__query_builder::HasCols for ContentCatalog {
    type Cols = ContentCatalogCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ContentCatalogCols {
            content_id: __sdk::__query_builder::Col::new(table_name, "content_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            content_type: __sdk::__query_builder::Col::new(table_name, "content_type"),
            source_mod: __sdk::__query_builder::Col::new(table_name, "source_mod"),
        }
    }
}

/// Indexed column accessor struct for the table `ContentCatalog`.
///
/// Provides typed access to indexed columns for query building.
pub struct ContentCatalogIxCols {
    pub content_id: __sdk::__query_builder::IxCol<ContentCatalog, u64>,
    pub name: __sdk::__query_builder::IxCol<ContentCatalog, String>,
}

impl __sdk::__query_builder::HasIxCols for ContentCatalog {
    type IxCols = ContentCatalogIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ContentCatalogIxCols {
            content_id: __sdk::__query_builder::IxCol::new(table_name, "content_id"),
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ContentCatalog {}
