// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::content_catalog_type::ContentCatalog;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `content_catalog`.
///
/// Obtain a handle from the [`ContentCatalogTableAccess::content_catalog`] method on [`super::RemoteTables`],
/// like `ctx.db.content_catalog()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.content_catalog().on_insert(...)`.
pub struct ContentCatalogTableHandle<'ctx> {
    imp: __sdk::TableHandle<ContentCatalog>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `content_catalog`.
pub struct ContentCatalogTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ContentCatalogTableAccessor {
    type Row = ContentCatalog;
    type Handle<'db> = ContentCatalogTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.content_catalog()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `content_catalog`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ContentCatalogTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ContentCatalogTableHandle`], which mediates access to the table `content_catalog`.
    fn content_catalog(&self) -> ContentCatalogTableHandle<'_>;
}

impl ContentCatalogTableAccess for super::RemoteTables {
    fn content_catalog(&self) -> ContentCatalogTableHandle<'_> {
        ContentCatalogTableHandle {
            imp: self.imp.get_table::<ContentCatalog>("content_catalog"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ContentCatalogInsertCallbackId(__sdk::CallbackId);
pub struct ContentCatalogDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ContentCatalogTableHandle<'ctx> {
    type Row = ContentCatalog;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ContentCatalog> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ContentCatalogTableHandle<'ctx> {
    type Row = ContentCatalog;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ContentCatalog> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ContentCatalogInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContentCatalogInsertCallbackId {
        ContentCatalogInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ContentCatalogInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ContentCatalogDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContentCatalogDeleteCallbackId {
        ContentCatalogDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ContentCatalogDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ContentCatalogTableHandle<'ctx> {
    type InsertCallbackId = ContentCatalogInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContentCatalogInsertCallbackId {
        ContentCatalogInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ContentCatalogInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ContentCatalogTableHandle<'ctx> {
    type DeleteCallbackId = ContentCatalogDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ContentCatalogDeleteCallbackId {
        ContentCatalogDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ContentCatalogDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ContentCatalogUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ContentCatalogTableHandle<'ctx> {
    type UpdateCallbackId = ContentCatalogUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ContentCatalogUpdateCallbackId {
        ContentCatalogUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ContentCatalogUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ContentCatalogTableHandle<'ctx> {
    type UpdateCallbackId = ContentCatalogUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ContentCatalogUpdateCallbackId {
        ContentCatalogUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ContentCatalogUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `content_id` unique index on the table `content_catalog`,
/// which allows point queries on the field of the same name
/// via the [`ContentCatalogContentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.content_catalog().content_id().find(...)`.
pub struct ContentCatalogContentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ContentCatalog, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ContentCatalogTableHandle<'ctx> {
    /// Get a handle on the `content_id` unique index on the table `content_catalog`.
    pub fn content_id(&self) -> ContentCatalogContentIdUnique<'ctx> {
        ContentCatalogContentIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("content_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ContentCatalogContentIdUnique<'ctx> {
    /// Find the subscribed row whose `content_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ContentCatalog> {
        self.imp.find(col_val)
    }
}

/// Access to the `name` unique index on the table `content_catalog`,
/// which allows point queries on the field of the same name
/// via the [`ContentCatalogNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.content_catalog().name().find(...)`.
pub struct ContentCatalogNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ContentCatalog, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ContentCatalogTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `content_catalog`.
    pub fn name(&self) -> ContentCatalogNameUnique<'ctx> {
        ContentCatalogNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ContentCatalogNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<ContentCatalog> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ContentCatalog>("content_catalog");
    _table.add_unique_constraint::<u64>("content_id", |row| &row.content_id);
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ContentCatalog>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ContentCatalog>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ContentCatalog`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait content_catalogQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ContentCatalog`.
    fn content_catalog(&self) -> __sdk::__query_builder::Table<ContentCatalog>;
}

impl content_catalogQueryTableAccess for __sdk::QueryTableAccessor {
    fn content_catalog(&self) -> __sdk::__query_builder::Table<ContentCatalog> {
        __sdk::__query_builder::Table::new("content_catalog")
    }
}
