// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateMatchArgs {
    pub map_id: String,
    pub map_seed: u64,
}

impl From<CreateMatchArgs> for super::Reducer {
    fn from(args: CreateMatchArgs) -> Self {
        Self::CreateMatch {
            map_id: args.map_id,
            map_seed: args.map_seed,
        }
    }
}

impl __sdk::InModule for CreateMatchArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_match`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_match {
    /// Request that the remote module invoke the reducer `create_match` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_match:create_match_then`] to run a callback after the reducer completes.
    fn create_match(&self, map_id: String, map_seed: u64) -> __sdk::Result<()> {
        self.create_match_then(map_id, map_seed, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_match` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_match_then(
        &self,
        map_id: String,
        map_seed: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_match for super::RemoteReducers {
    fn create_match_then(
        &self,
        map_id: String,
        map_seed: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CreateMatchArgs { map_id, map_seed }, callback)
    }
}
