// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::client_settings_type::ClientSettings;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `local_client_settings`.
///
/// Obtain a handle from the [`LocalClientSettingsTableAccess::local_client_settings`] method on [`super::RemoteTables`],
/// like `ctx.db.local_client_settings()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.local_client_settings().on_insert(...)`.
pub struct LocalClientSettingsTableHandle<'ctx> {
    imp: __sdk::TableHandle<ClientSettings>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `local_client_settings`.
pub struct LocalClientSettingsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for LocalClientSettingsTableAccessor {
    type Row = ClientSettings;
    type Handle<'db> = LocalClientSettingsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.local_client_settings()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `local_client_settings`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LocalClientSettingsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LocalClientSettingsTableHandle`], which mediates access to the table `local_client_settings`.
    fn local_client_settings(&self) -> LocalClientSettingsTableHandle<'_>;
}

impl LocalClientSettingsTableAccess for super::RemoteTables {
    fn local_client_settings(&self) -> LocalClientSettingsTableHandle<'_> {
        LocalClientSettingsTableHandle {
            imp: self
                .imp
                .get_table::<ClientSettings>("local_client_settings"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LocalClientSettingsInsertCallbackId(__sdk::CallbackId);
pub struct LocalClientSettingsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for LocalClientSettingsTableHandle<'ctx> {
    type Row = ClientSettings;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ClientSettings> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for LocalClientSettingsTableHandle<'ctx> {
    type Row = ClientSettings;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ClientSettings> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LocalClientSettingsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LocalClientSettingsInsertCallbackId {
        LocalClientSettingsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LocalClientSettingsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LocalClientSettingsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LocalClientSettingsDeleteCallbackId {
        LocalClientSettingsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LocalClientSettingsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for LocalClientSettingsTableHandle<'ctx> {
    type InsertCallbackId = LocalClientSettingsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LocalClientSettingsInsertCallbackId {
        LocalClientSettingsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LocalClientSettingsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for LocalClientSettingsTableHandle<'ctx> {
    type DeleteCallbackId = LocalClientSettingsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LocalClientSettingsDeleteCallbackId {
        LocalClientSettingsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LocalClientSettingsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ClientSettings>("local_client_settings");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ClientSettings>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ClientSettings>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ClientSettings`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait local_client_settingsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ClientSettings`.
    fn local_client_settings(&self) -> __sdk::__query_builder::Table<ClientSettings>;
}

impl local_client_settingsQueryTableAccess for __sdk::QueryTableAccessor {
    fn local_client_settings(&self) -> __sdk::__query_builder::Table<ClientSettings> {
        __sdk::__query_builder::Table::new("local_client_settings")
    }
}
