// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_type::Player;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `local_player`.
///
/// Obtain a handle from the [`LocalPlayerTableAccess::local_player`] method on [`super::RemoteTables`],
/// like `ctx.db.local_player()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.local_player().on_insert(...)`.
pub struct LocalPlayerTableHandle<'ctx> {
    imp: __sdk::TableHandle<Player>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `local_player`.
pub struct LocalPlayerTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for LocalPlayerTableAccessor {
    type Row = Player;
    type Handle<'db> = LocalPlayerTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.local_player()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `local_player`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LocalPlayerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LocalPlayerTableHandle`], which mediates access to the table `local_player`.
    fn local_player(&self) -> LocalPlayerTableHandle<'_>;
}

impl LocalPlayerTableAccess for super::RemoteTables {
    fn local_player(&self) -> LocalPlayerTableHandle<'_> {
        LocalPlayerTableHandle {
            imp: self.imp.get_table::<Player>("local_player"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LocalPlayerInsertCallbackId(__sdk::CallbackId);
pub struct LocalPlayerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for LocalPlayerTableHandle<'ctx> {
    type Row = Player;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Player> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for LocalPlayerTableHandle<'ctx> {
    type Row = Player;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Player> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LocalPlayerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LocalPlayerInsertCallbackId {
        LocalPlayerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LocalPlayerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LocalPlayerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LocalPlayerDeleteCallbackId {
        LocalPlayerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LocalPlayerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for LocalPlayerTableHandle<'ctx> {
    type InsertCallbackId = LocalPlayerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LocalPlayerInsertCallbackId {
        LocalPlayerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LocalPlayerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for LocalPlayerTableHandle<'ctx> {
    type DeleteCallbackId = LocalPlayerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LocalPlayerDeleteCallbackId {
        LocalPlayerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LocalPlayerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Player>("local_player");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Player>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Player>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Player`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait local_playerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Player`.
    fn local_player(&self) -> __sdk::__query_builder::Table<Player>;
}

impl local_playerQueryTableAccess for __sdk::QueryTableAccessor {
    fn local_player(&self) -> __sdk::__query_builder::Table<Player> {
        __sdk::__query_builder::Table::new("local_player")
    }
}
