// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MatchState {
    pub state_id: u64,
    pub match_id: u64,
    pub rules_json: String,
    pub rules_epoch: u32,
    pub wave: i32,
    pub wavetime: f32,
    pub enemies: i32,
    pub paused: bool,
    pub game_over: bool,
    pub sim_tick: u64,
    pub last_command_id: u64,
    pub rng_sim: Vec<u8>,
    pub next_entity_id: i32,
    pub snapshot_id: Option<u64>,
    pub updated_by: __sdk::Identity,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for MatchState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MatchState`.
///
/// Provides typed access to columns for query building.
pub struct MatchStateCols {
    pub state_id: __sdk::__query_builder::Col<MatchState, u64>,
    pub match_id: __sdk::__query_builder::Col<MatchState, u64>,
    pub rules_json: __sdk::__query_builder::Col<MatchState, String>,
    pub rules_epoch: __sdk::__query_builder::Col<MatchState, u32>,
    pub wave: __sdk::__query_builder::Col<MatchState, i32>,
    pub wavetime: __sdk::__query_builder::Col<MatchState, f32>,
    pub enemies: __sdk::__query_builder::Col<MatchState, i32>,
    pub paused: __sdk::__query_builder::Col<MatchState, bool>,
    pub game_over: __sdk::__query_builder::Col<MatchState, bool>,
    pub sim_tick: __sdk::__query_builder::Col<MatchState, u64>,
    pub last_command_id: __sdk::__query_builder::Col<MatchState, u64>,
    pub rng_sim: __sdk::__query_builder::Col<MatchState, Vec<u8>>,
    pub next_entity_id: __sdk::__query_builder::Col<MatchState, i32>,
    pub snapshot_id: __sdk::__query_builder::Col<MatchState, Option<u64>>,
    pub updated_by: __sdk::__query_builder::Col<MatchState, __sdk::Identity>,
    pub updated_at: __sdk::__query_builder::Col<MatchState, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for MatchState {
    type Cols = MatchStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MatchStateCols {
            state_id: __sdk::__query_builder::Col::new(table_name, "state_id"),
            match_id: __sdk::__query_builder::Col::new(table_name, "match_id"),
            rules_json: __sdk::__query_builder::Col::new(table_name, "rules_json"),
            rules_epoch: __sdk::__query_builder::Col::new(table_name, "rules_epoch"),
            wave: __sdk::__query_builder::Col::new(table_name, "wave"),
            wavetime: __sdk::__query_builder::Col::new(table_name, "wavetime"),
            enemies: __sdk::__query_builder::Col::new(table_name, "enemies"),
            paused: __sdk::__query_builder::Col::new(table_name, "paused"),
            game_over: __sdk::__query_builder::Col::new(table_name, "game_over"),
            sim_tick: __sdk::__query_builder::Col::new(table_name, "sim_tick"),
            last_command_id: __sdk::__query_builder::Col::new(table_name, "last_command_id"),
            rng_sim: __sdk::__query_builder::Col::new(table_name, "rng_sim"),
            next_entity_id: __sdk::__query_builder::Col::new(table_name, "next_entity_id"),
            snapshot_id: __sdk::__query_builder::Col::new(table_name, "snapshot_id"),
            updated_by: __sdk::__query_builder::Col::new(table_name, "updated_by"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `MatchState`.
///
/// Provides typed access to indexed columns for query building.
pub struct MatchStateIxCols {
    pub match_id: __sdk::__query_builder::IxCol<MatchState, u64>,
    pub state_id: __sdk::__query_builder::IxCol<MatchState, u64>,
}

impl __sdk::__query_builder::HasIxCols for MatchState {
    type IxCols = MatchStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MatchStateIxCols {
            match_id: __sdk::__query_builder::IxCol::new(table_name, "match_id"),
            state_id: __sdk::__query_builder::IxCol::new(table_name, "state_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MatchState {}
