// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MatchSnapshotChunk {
    pub chunk_id: u64,
    pub snapshot_id: u64,
    pub chunk_index: u16,
    pub data: Vec<u8>,
}

impl __sdk::InModule for MatchSnapshotChunk {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MatchSnapshotChunk`.
///
/// Provides typed access to columns for query building.
pub struct MatchSnapshotChunkCols {
    pub chunk_id: __sdk::__query_builder::Col<MatchSnapshotChunk, u64>,
    pub snapshot_id: __sdk::__query_builder::Col<MatchSnapshotChunk, u64>,
    pub chunk_index: __sdk::__query_builder::Col<MatchSnapshotChunk, u16>,
    pub data: __sdk::__query_builder::Col<MatchSnapshotChunk, Vec<u8>>,
}

impl __sdk::__query_builder::HasCols for MatchSnapshotChunk {
    type Cols = MatchSnapshotChunkCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MatchSnapshotChunkCols {
            chunk_id: __sdk::__query_builder::Col::new(table_name, "chunk_id"),
            snapshot_id: __sdk::__query_builder::Col::new(table_name, "snapshot_id"),
            chunk_index: __sdk::__query_builder::Col::new(table_name, "chunk_index"),
            data: __sdk::__query_builder::Col::new(table_name, "data"),
        }
    }
}

/// Indexed column accessor struct for the table `MatchSnapshotChunk`.
///
/// Provides typed access to indexed columns for query building.
pub struct MatchSnapshotChunkIxCols {
    pub chunk_id: __sdk::__query_builder::IxCol<MatchSnapshotChunk, u64>,
    pub snapshot_id: __sdk::__query_builder::IxCol<MatchSnapshotChunk, u64>,
}

impl __sdk::__query_builder::HasIxCols for MatchSnapshotChunk {
    type IxCols = MatchSnapshotChunkIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MatchSnapshotChunkIxCols {
            chunk_id: __sdk::__query_builder::IxCol::new(table_name, "chunk_id"),
            snapshot_id: __sdk::__query_builder::IxCol::new(table_name, "snapshot_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MatchSnapshotChunk {}
