// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MatchSnapshotRequest {
    pub request_id: u64,
    pub match_id: u64,
    pub identity: __sdk::Identity,
    pub requested_at: __sdk::Timestamp,
}

impl __sdk::InModule for MatchSnapshotRequest {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MatchSnapshotRequest`.
///
/// Provides typed access to columns for query building.
pub struct MatchSnapshotRequestCols {
    pub request_id: __sdk::__query_builder::Col<MatchSnapshotRequest, u64>,
    pub match_id: __sdk::__query_builder::Col<MatchSnapshotRequest, u64>,
    pub identity: __sdk::__query_builder::Col<MatchSnapshotRequest, __sdk::Identity>,
    pub requested_at: __sdk::__query_builder::Col<MatchSnapshotRequest, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for MatchSnapshotRequest {
    type Cols = MatchSnapshotRequestCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MatchSnapshotRequestCols {
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            match_id: __sdk::__query_builder::Col::new(table_name, "match_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            requested_at: __sdk::__query_builder::Col::new(table_name, "requested_at"),
        }
    }
}

/// Indexed column accessor struct for the table `MatchSnapshotRequest`.
///
/// Provides typed access to indexed columns for query building.
pub struct MatchSnapshotRequestIxCols {
    pub match_id: __sdk::__query_builder::IxCol<MatchSnapshotRequest, u64>,
    pub request_id: __sdk::__query_builder::IxCol<MatchSnapshotRequest, u64>,
}

impl __sdk::__query_builder::HasIxCols for MatchSnapshotRequest {
    type IxCols = MatchSnapshotRequestIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MatchSnapshotRequestIxCols {
            match_id: __sdk::__query_builder::IxCol::new(table_name, "match_id"),
            request_id: __sdk::__query_builder::IxCol::new(table_name, "request_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MatchSnapshotRequest {}
