// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::chat_kind_type::ChatKind;
use super::match_chat_type::MatchChat;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `match_chat`.
///
/// Obtain a handle from the [`MatchChatTableAccess::match_chat`] method on [`super::RemoteTables`],
/// like `ctx.db.match_chat()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_chat().on_insert(...)`.
pub struct MatchChatTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchChat>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `match_chat`.
pub struct MatchChatTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MatchChatTableAccessor {
    type Row = MatchChat;
    type Handle<'db> = MatchChatTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.match_chat()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `match_chat`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MatchChatTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MatchChatTableHandle`], which mediates access to the table `match_chat`.
    fn match_chat(&self) -> MatchChatTableHandle<'_>;
}

impl MatchChatTableAccess for super::RemoteTables {
    fn match_chat(&self) -> MatchChatTableHandle<'_> {
        MatchChatTableHandle {
            imp: self.imp.get_table::<MatchChat>("match_chat"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MatchChatInsertCallbackId(__sdk::CallbackId);
pub struct MatchChatDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MatchChatTableHandle<'ctx> {
    type Row = MatchChat;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchChat> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MatchChatTableHandle<'ctx> {
    type Row = MatchChat;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchChat> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MatchChatInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchChatInsertCallbackId {
        MatchChatInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchChatInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MatchChatDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchChatDeleteCallbackId {
        MatchChatDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchChatDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MatchChatTableHandle<'ctx> {
    type InsertCallbackId = MatchChatInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchChatInsertCallbackId {
        MatchChatInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchChatInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MatchChatTableHandle<'ctx> {
    type DeleteCallbackId = MatchChatDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchChatDeleteCallbackId {
        MatchChatDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchChatDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MatchChatUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MatchChatTableHandle<'ctx> {
    type UpdateCallbackId = MatchChatUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchChatUpdateCallbackId {
        MatchChatUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchChatUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MatchChatTableHandle<'ctx> {
    type UpdateCallbackId = MatchChatUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchChatUpdateCallbackId {
        MatchChatUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchChatUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `chat_id` unique index on the table `match_chat`,
/// which allows point queries on the field of the same name
/// via the [`MatchChatChatIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_chat().chat_id().find(...)`.
pub struct MatchChatChatIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MatchChat, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MatchChatTableHandle<'ctx> {
    /// Get a handle on the `chat_id` unique index on the table `match_chat`.
    pub fn chat_id(&self) -> MatchChatChatIdUnique<'ctx> {
        MatchChatChatIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("chat_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MatchChatChatIdUnique<'ctx> {
    /// Find the subscribed row whose `chat_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MatchChat> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchChat>("match_chat");
    _table.add_unique_constraint::<u64>("chat_id", |row| &row.chat_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchChat>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchChat>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchChat`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait match_chatQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchChat`.
    fn match_chat(&self) -> __sdk::__query_builder::Table<MatchChat>;
}

impl match_chatQueryTableAccess for __sdk::QueryTableAccessor {
    fn match_chat(&self) -> __sdk::__query_builder::Table<MatchChat> {
        __sdk::__query_builder::Table::new("match_chat")
    }
}
