// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::chat_kind_type::ChatKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MatchChat {
    pub chat_id: u64,
    pub match_id: u64,
    pub sender: __sdk::Identity,
    pub kind: ChatKind,
    pub team: Option<u8>,
    pub text: String,
    pub sent_at: __sdk::Timestamp,
}

impl __sdk::InModule for MatchChat {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MatchChat`.
///
/// Provides typed access to columns for query building.
pub struct MatchChatCols {
    pub chat_id: __sdk::__query_builder::Col<MatchChat, u64>,
    pub match_id: __sdk::__query_builder::Col<MatchChat, u64>,
    pub sender: __sdk::__query_builder::Col<MatchChat, __sdk::Identity>,
    pub kind: __sdk::__query_builder::Col<MatchChat, ChatKind>,
    pub team: __sdk::__query_builder::Col<MatchChat, Option<u8>>,
    pub text: __sdk::__query_builder::Col<MatchChat, String>,
    pub sent_at: __sdk::__query_builder::Col<MatchChat, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for MatchChat {
    type Cols = MatchChatCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MatchChatCols {
            chat_id: __sdk::__query_builder::Col::new(table_name, "chat_id"),
            match_id: __sdk::__query_builder::Col::new(table_name, "match_id"),
            sender: __sdk::__query_builder::Col::new(table_name, "sender"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            team: __sdk::__query_builder::Col::new(table_name, "team"),
            text: __sdk::__query_builder::Col::new(table_name, "text"),
            sent_at: __sdk::__query_builder::Col::new(table_name, "sent_at"),
        }
    }
}

/// Indexed column accessor struct for the table `MatchChat`.
///
/// Provides typed access to indexed columns for query building.
pub struct MatchChatIxCols {
    pub chat_id: __sdk::__query_builder::IxCol<MatchChat, u64>,
    pub match_id: __sdk::__query_builder::IxCol<MatchChat, u64>,
}

impl __sdk::__query_builder::HasIxCols for MatchChat {
    type IxCols = MatchChatIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MatchChatIxCols {
            chat_id: __sdk::__query_builder::IxCol::new(table_name, "chat_id"),
            match_id: __sdk::__query_builder::IxCol::new(table_name, "match_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MatchChat {}
