// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MatchKick {
    pub kick_id: u64,
    pub match_id: u64,
    pub target: __sdk::Identity,
    pub reason: String,
    pub by: __sdk::Identity,
    pub at: __sdk::Timestamp,
}

impl __sdk::InModule for MatchKick {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MatchKick`.
///
/// Provides typed access to columns for query building.
pub struct MatchKickCols {
    pub kick_id: __sdk::__query_builder::Col<MatchKick, u64>,
    pub match_id: __sdk::__query_builder::Col<MatchKick, u64>,
    pub target: __sdk::__query_builder::Col<MatchKick, __sdk::Identity>,
    pub reason: __sdk::__query_builder::Col<MatchKick, String>,
    pub by: __sdk::__query_builder::Col<MatchKick, __sdk::Identity>,
    pub at: __sdk::__query_builder::Col<MatchKick, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for MatchKick {
    type Cols = MatchKickCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MatchKickCols {
            kick_id: __sdk::__query_builder::Col::new(table_name, "kick_id"),
            match_id: __sdk::__query_builder::Col::new(table_name, "match_id"),
            target: __sdk::__query_builder::Col::new(table_name, "target"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            by: __sdk::__query_builder::Col::new(table_name, "by"),
            at: __sdk::__query_builder::Col::new(table_name, "at"),
        }
    }
}

/// Indexed column accessor struct for the table `MatchKick`.
///
/// Provides typed access to indexed columns for query building.
pub struct MatchKickIxCols {
    pub kick_id: __sdk::__query_builder::IxCol<MatchKick, u64>,
    pub match_id: __sdk::__query_builder::IxCol<MatchKick, u64>,
    pub target: __sdk::__query_builder::IxCol<MatchKick, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for MatchKick {
    type IxCols = MatchKickIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MatchKickIxCols {
            kick_id: __sdk::__query_builder::IxCol::new(table_name, "kick_id"),
            match_id: __sdk::__query_builder::IxCol::new(table_name, "match_id"),
            target: __sdk::__query_builder::IxCol::new(table_name, "target"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MatchKick {}
