// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_mod_type::MatchMod;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `match_mod`.
///
/// Obtain a handle from the [`MatchModTableAccess::match_mod`] method on [`super::RemoteTables`],
/// like `ctx.db.match_mod()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_mod().on_insert(...)`.
pub struct MatchModTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchMod>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `match_mod`.
pub struct MatchModTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MatchModTableAccessor {
    type Row = MatchMod;
    type Handle<'db> = MatchModTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.match_mod()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `match_mod`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MatchModTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MatchModTableHandle`], which mediates access to the table `match_mod`.
    fn match_mod(&self) -> MatchModTableHandle<'_>;
}

impl MatchModTableAccess for super::RemoteTables {
    fn match_mod(&self) -> MatchModTableHandle<'_> {
        MatchModTableHandle {
            imp: self.imp.get_table::<MatchMod>("match_mod"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MatchModInsertCallbackId(__sdk::CallbackId);
pub struct MatchModDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MatchModTableHandle<'ctx> {
    type Row = MatchMod;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchMod> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MatchModTableHandle<'ctx> {
    type Row = MatchMod;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchMod> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MatchModInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchModInsertCallbackId {
        MatchModInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchModInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MatchModDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchModDeleteCallbackId {
        MatchModDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchModDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MatchModTableHandle<'ctx> {
    type InsertCallbackId = MatchModInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchModInsertCallbackId {
        MatchModInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchModInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MatchModTableHandle<'ctx> {
    type DeleteCallbackId = MatchModDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchModDeleteCallbackId {
        MatchModDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchModDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MatchModUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MatchModTableHandle<'ctx> {
    type UpdateCallbackId = MatchModUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchModUpdateCallbackId {
        MatchModUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchModUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MatchModTableHandle<'ctx> {
    type UpdateCallbackId = MatchModUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchModUpdateCallbackId {
        MatchModUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchModUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `match_mod_id` unique index on the table `match_mod`,
/// which allows point queries on the field of the same name
/// via the [`MatchModMatchModIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_mod().match_mod_id().find(...)`.
pub struct MatchModMatchModIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MatchMod, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MatchModTableHandle<'ctx> {
    /// Get a handle on the `match_mod_id` unique index on the table `match_mod`.
    pub fn match_mod_id(&self) -> MatchModMatchModIdUnique<'ctx> {
        MatchModMatchModIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("match_mod_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MatchModMatchModIdUnique<'ctx> {
    /// Find the subscribed row whose `match_mod_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MatchMod> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchMod>("match_mod");
    _table.add_unique_constraint::<u64>("match_mod_id", |row| &row.match_mod_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchMod>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchMod>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchMod`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait match_modQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchMod`.
    fn match_mod(&self) -> __sdk::__query_builder::Table<MatchMod>;
}

impl match_modQueryTableAccess for __sdk::QueryTableAccessor {
    fn match_mod(&self) -> __sdk::__query_builder::Table<MatchMod> {
        __sdk::__query_builder::Table::new("match_mod")
    }
}
