// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MatchPlayerState {
    pub state_id: u64,
    pub match_id: u64,
    pub identity: __sdk::Identity,
    pub seq: u32,
    pub unit_id: i32,
    pub dead: bool,
    pub x: f32,
    pub y: f32,
    pub vx: f32,
    pub vy: f32,
    pub pointer_x: f32,
    pub pointer_y: f32,
    pub rotation: f32,
    pub base_rotation: f32,
    pub mining_x: i16,
    pub mining_y: i16,
    pub boosting: bool,
    pub shooting: bool,
    pub chatting: bool,
    pub building: bool,
    pub selected_block: Option<String>,
    pub selected_rotation: u8,
    pub view_x: f32,
    pub view_y: f32,
    pub view_width: f32,
    pub view_height: f32,
    pub health: f32,
    pub shield: f32,
    pub team: u8,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for MatchPlayerState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MatchPlayerState`.
///
/// Provides typed access to columns for query building.
pub struct MatchPlayerStateCols {
    pub state_id: __sdk::__query_builder::Col<MatchPlayerState, u64>,
    pub match_id: __sdk::__query_builder::Col<MatchPlayerState, u64>,
    pub identity: __sdk::__query_builder::Col<MatchPlayerState, __sdk::Identity>,
    pub seq: __sdk::__query_builder::Col<MatchPlayerState, u32>,
    pub unit_id: __sdk::__query_builder::Col<MatchPlayerState, i32>,
    pub dead: __sdk::__query_builder::Col<MatchPlayerState, bool>,
    pub x: __sdk::__query_builder::Col<MatchPlayerState, f32>,
    pub y: __sdk::__query_builder::Col<MatchPlayerState, f32>,
    pub vx: __sdk::__query_builder::Col<MatchPlayerState, f32>,
    pub vy: __sdk::__query_builder::Col<MatchPlayerState, f32>,
    pub pointer_x: __sdk::__query_builder::Col<MatchPlayerState, f32>,
    pub pointer_y: __sdk::__query_builder::Col<MatchPlayerState, f32>,
    pub rotation: __sdk::__query_builder::Col<MatchPlayerState, f32>,
    pub base_rotation: __sdk::__query_builder::Col<MatchPlayerState, f32>,
    pub mining_x: __sdk::__query_builder::Col<MatchPlayerState, i16>,
    pub mining_y: __sdk::__query_builder::Col<MatchPlayerState, i16>,
    pub boosting: __sdk::__query_builder::Col<MatchPlayerState, bool>,
    pub shooting: __sdk::__query_builder::Col<MatchPlayerState, bool>,
    pub chatting: __sdk::__query_builder::Col<MatchPlayerState, bool>,
    pub building: __sdk::__query_builder::Col<MatchPlayerState, bool>,
    pub selected_block: __sdk::__query_builder::Col<MatchPlayerState, Option<String>>,
    pub selected_rotation: __sdk::__query_builder::Col<MatchPlayerState, u8>,
    pub view_x: __sdk::__query_builder::Col<MatchPlayerState, f32>,
    pub view_y: __sdk::__query_builder::Col<MatchPlayerState, f32>,
    pub view_width: __sdk::__query_builder::Col<MatchPlayerState, f32>,
    pub view_height: __sdk::__query_builder::Col<MatchPlayerState, f32>,
    pub health: __sdk::__query_builder::Col<MatchPlayerState, f32>,
    pub shield: __sdk::__query_builder::Col<MatchPlayerState, f32>,
    pub team: __sdk::__query_builder::Col<MatchPlayerState, u8>,
    pub updated_at: __sdk::__query_builder::Col<MatchPlayerState, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for MatchPlayerState {
    type Cols = MatchPlayerStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MatchPlayerStateCols {
            state_id: __sdk::__query_builder::Col::new(table_name, "state_id"),
            match_id: __sdk::__query_builder::Col::new(table_name, "match_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            seq: __sdk::__query_builder::Col::new(table_name, "seq"),
            unit_id: __sdk::__query_builder::Col::new(table_name, "unit_id"),
            dead: __sdk::__query_builder::Col::new(table_name, "dead"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            vx: __sdk::__query_builder::Col::new(table_name, "vx"),
            vy: __sdk::__query_builder::Col::new(table_name, "vy"),
            pointer_x: __sdk::__query_builder::Col::new(table_name, "pointer_x"),
            pointer_y: __sdk::__query_builder::Col::new(table_name, "pointer_y"),
            rotation: __sdk::__query_builder::Col::new(table_name, "rotation"),
            base_rotation: __sdk::__query_builder::Col::new(table_name, "base_rotation"),
            mining_x: __sdk::__query_builder::Col::new(table_name, "mining_x"),
            mining_y: __sdk::__query_builder::Col::new(table_name, "mining_y"),
            boosting: __sdk::__query_builder::Col::new(table_name, "boosting"),
            shooting: __sdk::__query_builder::Col::new(table_name, "shooting"),
            chatting: __sdk::__query_builder::Col::new(table_name, "chatting"),
            building: __sdk::__query_builder::Col::new(table_name, "building"),
            selected_block: __sdk::__query_builder::Col::new(table_name, "selected_block"),
            selected_rotation: __sdk::__query_builder::Col::new(table_name, "selected_rotation"),
            view_x: __sdk::__query_builder::Col::new(table_name, "view_x"),
            view_y: __sdk::__query_builder::Col::new(table_name, "view_y"),
            view_width: __sdk::__query_builder::Col::new(table_name, "view_width"),
            view_height: __sdk::__query_builder::Col::new(table_name, "view_height"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
            shield: __sdk::__query_builder::Col::new(table_name, "shield"),
            team: __sdk::__query_builder::Col::new(table_name, "team"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `MatchPlayerState`.
///
/// Provides typed access to indexed columns for query building.
pub struct MatchPlayerStateIxCols {
    pub match_id: __sdk::__query_builder::IxCol<MatchPlayerState, u64>,
    pub state_id: __sdk::__query_builder::IxCol<MatchPlayerState, u64>,
}

impl __sdk::__query_builder::HasIxCols for MatchPlayerState {
    type IxCols = MatchPlayerStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MatchPlayerStateIxCols {
            match_id: __sdk::__query_builder::IxCol::new(table_name, "match_id"),
            state_id: __sdk::__query_builder::IxCol::new(table_name, "state_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MatchPlayerState {}
