// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::snapshot_kind_type::SnapshotKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MatchSnapshot {
    pub snapshot_id: u64,
    pub match_id: u64,
    pub author: __sdk::Identity,
    pub kind: SnapshotKind,
    pub format: u32,
    pub checksum_version: u32,
    pub command_id: u64,
    pub sim_tick: u64,
    pub checksum: u64,
    pub map_id: String,
    pub map_seed: u64,
    pub map_hash: u64,
    pub build_id: String,
    pub content_hash: u64,
    pub bytes_len: u32,
    pub chunk_count: u16,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for MatchSnapshot {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MatchSnapshot`.
///
/// Provides typed access to columns for query building.
pub struct MatchSnapshotCols {
    pub snapshot_id: __sdk::__query_builder::Col<MatchSnapshot, u64>,
    pub match_id: __sdk::__query_builder::Col<MatchSnapshot, u64>,
    pub author: __sdk::__query_builder::Col<MatchSnapshot, __sdk::Identity>,
    pub kind: __sdk::__query_builder::Col<MatchSnapshot, SnapshotKind>,
    pub format: __sdk::__query_builder::Col<MatchSnapshot, u32>,
    pub checksum_version: __sdk::__query_builder::Col<MatchSnapshot, u32>,
    pub command_id: __sdk::__query_builder::Col<MatchSnapshot, u64>,
    pub sim_tick: __sdk::__query_builder::Col<MatchSnapshot, u64>,
    pub checksum: __sdk::__query_builder::Col<MatchSnapshot, u64>,
    pub map_id: __sdk::__query_builder::Col<MatchSnapshot, String>,
    pub map_seed: __sdk::__query_builder::Col<MatchSnapshot, u64>,
    pub map_hash: __sdk::__query_builder::Col<MatchSnapshot, u64>,
    pub build_id: __sdk::__query_builder::Col<MatchSnapshot, String>,
    pub content_hash: __sdk::__query_builder::Col<MatchSnapshot, u64>,
    pub bytes_len: __sdk::__query_builder::Col<MatchSnapshot, u32>,
    pub chunk_count: __sdk::__query_builder::Col<MatchSnapshot, u16>,
    pub created_at: __sdk::__query_builder::Col<MatchSnapshot, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for MatchSnapshot {
    type Cols = MatchSnapshotCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MatchSnapshotCols {
            snapshot_id: __sdk::__query_builder::Col::new(table_name, "snapshot_id"),
            match_id: __sdk::__query_builder::Col::new(table_name, "match_id"),
            author: __sdk::__query_builder::Col::new(table_name, "author"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            format: __sdk::__query_builder::Col::new(table_name, "format"),
            checksum_version: __sdk::__query_builder::Col::new(table_name, "checksum_version"),
            command_id: __sdk::__query_builder::Col::new(table_name, "command_id"),
            sim_tick: __sdk::__query_builder::Col::new(table_name, "sim_tick"),
            checksum: __sdk::__query_builder::Col::new(table_name, "checksum"),
            map_id: __sdk::__query_builder::Col::new(table_name, "map_id"),
            map_seed: __sdk::__query_builder::Col::new(table_name, "map_seed"),
            map_hash: __sdk::__query_builder::Col::new(table_name, "map_hash"),
            build_id: __sdk::__query_builder::Col::new(table_name, "build_id"),
            content_hash: __sdk::__query_builder::Col::new(table_name, "content_hash"),
            bytes_len: __sdk::__query_builder::Col::new(table_name, "bytes_len"),
            chunk_count: __sdk::__query_builder::Col::new(table_name, "chunk_count"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `MatchSnapshot`.
///
/// Provides typed access to indexed columns for query building.
pub struct MatchSnapshotIxCols {
    pub match_id: __sdk::__query_builder::IxCol<MatchSnapshot, u64>,
    pub snapshot_id: __sdk::__query_builder::IxCol<MatchSnapshot, u64>,
}

impl __sdk::__query_builder::HasIxCols for MatchSnapshot {
    type IxCols = MatchSnapshotIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MatchSnapshotIxCols {
            match_id: __sdk::__query_builder::IxCol::new(table_name, "match_id"),
            snapshot_id: __sdk::__query_builder::IxCol::new(table_name, "snapshot_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MatchSnapshot {}
