// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_plan_chunk_type::MatchPlanChunk;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `match_plan_chunk`.
///
/// Obtain a handle from the [`MatchPlanChunkTableAccess::match_plan_chunk`] method on [`super::RemoteTables`],
/// like `ctx.db.match_plan_chunk()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_plan_chunk().on_insert(...)`.
pub struct MatchPlanChunkTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchPlanChunk>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `match_plan_chunk`.
pub struct MatchPlanChunkTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MatchPlanChunkTableAccessor {
    type Row = MatchPlanChunk;
    type Handle<'db> = MatchPlanChunkTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.match_plan_chunk()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `match_plan_chunk`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MatchPlanChunkTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MatchPlanChunkTableHandle`], which mediates access to the table `match_plan_chunk`.
    fn match_plan_chunk(&self) -> MatchPlanChunkTableHandle<'_>;
}

impl MatchPlanChunkTableAccess for super::RemoteTables {
    fn match_plan_chunk(&self) -> MatchPlanChunkTableHandle<'_> {
        MatchPlanChunkTableHandle {
            imp: self.imp.get_table::<MatchPlanChunk>("match_plan_chunk"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MatchPlanChunkInsertCallbackId(__sdk::CallbackId);
pub struct MatchPlanChunkDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MatchPlanChunkTableHandle<'ctx> {
    type Row = MatchPlanChunk;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchPlanChunk> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MatchPlanChunkTableHandle<'ctx> {
    type Row = MatchPlanChunk;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchPlanChunk> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MatchPlanChunkInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchPlanChunkInsertCallbackId {
        MatchPlanChunkInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchPlanChunkInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MatchPlanChunkDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchPlanChunkDeleteCallbackId {
        MatchPlanChunkDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchPlanChunkDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MatchPlanChunkTableHandle<'ctx> {
    type InsertCallbackId = MatchPlanChunkInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchPlanChunkInsertCallbackId {
        MatchPlanChunkInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchPlanChunkInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MatchPlanChunkTableHandle<'ctx> {
    type DeleteCallbackId = MatchPlanChunkDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchPlanChunkDeleteCallbackId {
        MatchPlanChunkDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchPlanChunkDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MatchPlanChunkUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MatchPlanChunkTableHandle<'ctx> {
    type UpdateCallbackId = MatchPlanChunkUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchPlanChunkUpdateCallbackId {
        MatchPlanChunkUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchPlanChunkUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MatchPlanChunkTableHandle<'ctx> {
    type UpdateCallbackId = MatchPlanChunkUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchPlanChunkUpdateCallbackId {
        MatchPlanChunkUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchPlanChunkUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `chunk_id` unique index on the table `match_plan_chunk`,
/// which allows point queries on the field of the same name
/// via the [`MatchPlanChunkChunkIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_plan_chunk().chunk_id().find(...)`.
pub struct MatchPlanChunkChunkIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MatchPlanChunk, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MatchPlanChunkTableHandle<'ctx> {
    /// Get a handle on the `chunk_id` unique index on the table `match_plan_chunk`.
    pub fn chunk_id(&self) -> MatchPlanChunkChunkIdUnique<'ctx> {
        MatchPlanChunkChunkIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("chunk_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MatchPlanChunkChunkIdUnique<'ctx> {
    /// Find the subscribed row whose `chunk_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MatchPlanChunk> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchPlanChunk>("match_plan_chunk");
    _table.add_unique_constraint::<u64>("chunk_id", |row| &row.chunk_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchPlanChunk>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchPlanChunk>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchPlanChunk`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait match_plan_chunkQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchPlanChunk`.
    fn match_plan_chunk(&self) -> __sdk::__query_builder::Table<MatchPlanChunk>;
}

impl match_plan_chunkQueryTableAccess for __sdk::QueryTableAccessor {
    fn match_plan_chunk(&self) -> __sdk::__query_builder::Table<MatchPlanChunk> {
        __sdk::__query_builder::Table::new("match_plan_chunk")
    }
}
