// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_plan_state_type::MatchPlanState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `match_plan_state`.
///
/// Obtain a handle from the [`MatchPlanStateTableAccess::match_plan_state`] method on [`super::RemoteTables`],
/// like `ctx.db.match_plan_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_plan_state().on_insert(...)`.
pub struct MatchPlanStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchPlanState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `match_plan_state`.
pub struct MatchPlanStateTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MatchPlanStateTableAccessor {
    type Row = MatchPlanState;
    type Handle<'db> = MatchPlanStateTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.match_plan_state()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `match_plan_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MatchPlanStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MatchPlanStateTableHandle`], which mediates access to the table `match_plan_state`.
    fn match_plan_state(&self) -> MatchPlanStateTableHandle<'_>;
}

impl MatchPlanStateTableAccess for super::RemoteTables {
    fn match_plan_state(&self) -> MatchPlanStateTableHandle<'_> {
        MatchPlanStateTableHandle {
            imp: self.imp.get_table::<MatchPlanState>("match_plan_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MatchPlanStateInsertCallbackId(__sdk::CallbackId);
pub struct MatchPlanStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MatchPlanStateTableHandle<'ctx> {
    type Row = MatchPlanState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchPlanState> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MatchPlanStateTableHandle<'ctx> {
    type Row = MatchPlanState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchPlanState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MatchPlanStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchPlanStateInsertCallbackId {
        MatchPlanStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchPlanStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MatchPlanStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchPlanStateDeleteCallbackId {
        MatchPlanStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchPlanStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MatchPlanStateTableHandle<'ctx> {
    type InsertCallbackId = MatchPlanStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchPlanStateInsertCallbackId {
        MatchPlanStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchPlanStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MatchPlanStateTableHandle<'ctx> {
    type DeleteCallbackId = MatchPlanStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchPlanStateDeleteCallbackId {
        MatchPlanStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchPlanStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MatchPlanStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MatchPlanStateTableHandle<'ctx> {
    type UpdateCallbackId = MatchPlanStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchPlanStateUpdateCallbackId {
        MatchPlanStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchPlanStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MatchPlanStateTableHandle<'ctx> {
    type UpdateCallbackId = MatchPlanStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchPlanStateUpdateCallbackId {
        MatchPlanStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchPlanStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `plan_state_id` unique index on the table `match_plan_state`,
/// which allows point queries on the field of the same name
/// via the [`MatchPlanStatePlanStateIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_plan_state().plan_state_id().find(...)`.
pub struct MatchPlanStatePlanStateIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MatchPlanState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MatchPlanStateTableHandle<'ctx> {
    /// Get a handle on the `plan_state_id` unique index on the table `match_plan_state`.
    pub fn plan_state_id(&self) -> MatchPlanStatePlanStateIdUnique<'ctx> {
        MatchPlanStatePlanStateIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("plan_state_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MatchPlanStatePlanStateIdUnique<'ctx> {
    /// Find the subscribed row whose `plan_state_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MatchPlanState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchPlanState>("match_plan_state");
    _table.add_unique_constraint::<u64>("plan_state_id", |row| &row.plan_state_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchPlanState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchPlanState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchPlanState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait match_plan_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchPlanState`.
    fn match_plan_state(&self) -> __sdk::__query_builder::Table<MatchPlanState>;
}

impl match_plan_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn match_plan_state(&self) -> __sdk::__query_builder::Table<MatchPlanState> {
        __sdk::__query_builder::Table::new("match_plan_state")
    }
}
