// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MatchMod {
    pub match_mod_id: u64,
    pub match_id: u64,
    pub name: String,
    pub version: String,
    pub content_hash: u64,
}

impl __sdk::InModule for MatchMod {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MatchMod`.
///
/// Provides typed access to columns for query building.
pub struct MatchModCols {
    pub match_mod_id: __sdk::__query_builder::Col<MatchMod, u64>,
    pub match_id: __sdk::__query_builder::Col<MatchMod, u64>,
    pub name: __sdk::__query_builder::Col<MatchMod, String>,
    pub version: __sdk::__query_builder::Col<MatchMod, String>,
    pub content_hash: __sdk::__query_builder::Col<MatchMod, u64>,
}

impl __sdk::__query_builder::HasCols for MatchMod {
    type Cols = MatchModCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MatchModCols {
            match_mod_id: __sdk::__query_builder::Col::new(table_name, "match_mod_id"),
            match_id: __sdk::__query_builder::Col::new(table_name, "match_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            version: __sdk::__query_builder::Col::new(table_name, "version"),
            content_hash: __sdk::__query_builder::Col::new(table_name, "content_hash"),
        }
    }
}

/// Indexed column accessor struct for the table `MatchMod`.
///
/// Provides typed access to indexed columns for query building.
pub struct MatchModIxCols {
    pub match_id: __sdk::__query_builder::IxCol<MatchMod, u64>,
    pub match_mod_id: __sdk::__query_builder::IxCol<MatchMod, u64>,
}

impl __sdk::__query_builder::HasIxCols for MatchMod {
    type IxCols = MatchModIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MatchModIxCols {
            match_id: __sdk::__query_builder::IxCol::new(table_name, "match_id"),
            match_mod_id: __sdk::__query_builder::IxCol::new(table_name, "match_mod_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MatchMod {}
