// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_ui_event_type::MatchUiEvent;
use super::ui_event_kind_type::UiEventKind;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `match_ui_event`.
///
/// Obtain a handle from the [`MatchUiEventTableAccess::match_ui_event`] method on [`super::RemoteTables`],
/// like `ctx.db.match_ui_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_ui_event().on_insert(...)`.
pub struct MatchUiEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchUiEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `match_ui_event`.
pub struct MatchUiEventTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MatchUiEventTableAccessor {
    type Row = MatchUiEvent;
    type Handle<'db> = MatchUiEventTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.match_ui_event()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `match_ui_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MatchUiEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MatchUiEventTableHandle`], which mediates access to the table `match_ui_event`.
    fn match_ui_event(&self) -> MatchUiEventTableHandle<'_>;
}

impl MatchUiEventTableAccess for super::RemoteTables {
    fn match_ui_event(&self) -> MatchUiEventTableHandle<'_> {
        MatchUiEventTableHandle {
            imp: self.imp.get_table::<MatchUiEvent>("match_ui_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MatchUiEventInsertCallbackId(__sdk::CallbackId);
pub struct MatchUiEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MatchUiEventTableHandle<'ctx> {
    type Row = MatchUiEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchUiEvent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MatchUiEventTableHandle<'ctx> {
    type Row = MatchUiEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchUiEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MatchUiEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchUiEventInsertCallbackId {
        MatchUiEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchUiEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MatchUiEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchUiEventDeleteCallbackId {
        MatchUiEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchUiEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MatchUiEventTableHandle<'ctx> {
    type InsertCallbackId = MatchUiEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchUiEventInsertCallbackId {
        MatchUiEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchUiEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MatchUiEventTableHandle<'ctx> {
    type DeleteCallbackId = MatchUiEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchUiEventDeleteCallbackId {
        MatchUiEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchUiEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MatchUiEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MatchUiEventTableHandle<'ctx> {
    type UpdateCallbackId = MatchUiEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchUiEventUpdateCallbackId {
        MatchUiEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchUiEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MatchUiEventTableHandle<'ctx> {
    type UpdateCallbackId = MatchUiEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchUiEventUpdateCallbackId {
        MatchUiEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchUiEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `event_id` unique index on the table `match_ui_event`,
/// which allows point queries on the field of the same name
/// via the [`MatchUiEventEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_ui_event().event_id().find(...)`.
pub struct MatchUiEventEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MatchUiEvent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MatchUiEventTableHandle<'ctx> {
    /// Get a handle on the `event_id` unique index on the table `match_ui_event`.
    pub fn event_id(&self) -> MatchUiEventEventIdUnique<'ctx> {
        MatchUiEventEventIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("event_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MatchUiEventEventIdUnique<'ctx> {
    /// Find the subscribed row whose `event_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MatchUiEvent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchUiEvent>("match_ui_event");
    _table.add_unique_constraint::<u64>("event_id", |row| &row.event_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchUiEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchUiEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchUiEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait match_ui_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchUiEvent`.
    fn match_ui_event(&self) -> __sdk::__query_builder::Table<MatchUiEvent>;
}

impl match_ui_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn match_ui_event(&self) -> __sdk::__query_builder::Table<MatchUiEvent> {
        __sdk::__query_builder::Table::new("match_ui_event")
    }
}
