// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_checksum_type::MatchChecksum;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `match_checksum`.
///
/// Obtain a handle from the [`MatchChecksumTableAccess::match_checksum`] method on [`super::RemoteTables`],
/// like `ctx.db.match_checksum()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_checksum().on_insert(...)`.
pub struct MatchChecksumTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchChecksum>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `match_checksum`.
pub struct MatchChecksumTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MatchChecksumTableAccessor {
    type Row = MatchChecksum;
    type Handle<'db> = MatchChecksumTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.match_checksum()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `match_checksum`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MatchChecksumTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MatchChecksumTableHandle`], which mediates access to the table `match_checksum`.
    fn match_checksum(&self) -> MatchChecksumTableHandle<'_>;
}

impl MatchChecksumTableAccess for super::RemoteTables {
    fn match_checksum(&self) -> MatchChecksumTableHandle<'_> {
        MatchChecksumTableHandle {
            imp: self.imp.get_table::<MatchChecksum>("match_checksum"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MatchChecksumInsertCallbackId(__sdk::CallbackId);
pub struct MatchChecksumDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MatchChecksumTableHandle<'ctx> {
    type Row = MatchChecksum;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchChecksum> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MatchChecksumTableHandle<'ctx> {
    type Row = MatchChecksum;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchChecksum> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MatchChecksumInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchChecksumInsertCallbackId {
        MatchChecksumInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchChecksumInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MatchChecksumDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchChecksumDeleteCallbackId {
        MatchChecksumDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchChecksumDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MatchChecksumTableHandle<'ctx> {
    type InsertCallbackId = MatchChecksumInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchChecksumInsertCallbackId {
        MatchChecksumInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MatchChecksumInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MatchChecksumTableHandle<'ctx> {
    type DeleteCallbackId = MatchChecksumDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MatchChecksumDeleteCallbackId {
        MatchChecksumDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MatchChecksumDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MatchChecksumUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MatchChecksumTableHandle<'ctx> {
    type UpdateCallbackId = MatchChecksumUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchChecksumUpdateCallbackId {
        MatchChecksumUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchChecksumUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MatchChecksumTableHandle<'ctx> {
    type UpdateCallbackId = MatchChecksumUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MatchChecksumUpdateCallbackId {
        MatchChecksumUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MatchChecksumUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `checksum_id` unique index on the table `match_checksum`,
/// which allows point queries on the field of the same name
/// via the [`MatchChecksumChecksumIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.match_checksum().checksum_id().find(...)`.
pub struct MatchChecksumChecksumIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MatchChecksum, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MatchChecksumTableHandle<'ctx> {
    /// Get a handle on the `checksum_id` unique index on the table `match_checksum`.
    pub fn checksum_id(&self) -> MatchChecksumChecksumIdUnique<'ctx> {
        MatchChecksumChecksumIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("checksum_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MatchChecksumChecksumIdUnique<'ctx> {
    /// Find the subscribed row whose `checksum_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MatchChecksum> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchChecksum>("match_checksum");
    _table.add_unique_constraint::<u64>("checksum_id", |row| &row.checksum_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchChecksum>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchChecksum>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchChecksum`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait match_checksumQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchChecksum`.
    fn match_checksum(&self) -> __sdk::__query_builder::Table<MatchChecksum>;
}

impl match_checksumQueryTableAccess for __sdk::QueryTableAccessor {
    fn match_checksum(&self) -> __sdk::__query_builder::Table<MatchChecksum> {
        __sdk::__query_builder::Table::new("match_checksum")
    }
}
