// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.1 (commit 3d7607082ab47257adeb7c25164536511237f2b5).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod admin_identity_table;
pub mod admin_identity_type;
pub mod admin_switch_team_type;
pub mod admin_tile_op_type;
pub mod all_matches_table;
pub mod all_players_table;
pub mod audit_kind_type;
pub mod audit_log_type;
pub mod authority_mode_type;
pub mod break_block_type;
pub mod building_control_select_type;
pub mod bullet_type;
pub mod chat_filter_table;
pub mod chat_filter_type;
pub mod chat_kind_type;
pub mod chat_rate_type;
pub mod checksum_rate_type;
pub mod client_settings_table;
pub mod client_settings_type;
pub mod command_building_type;
pub mod command_kind_type;
pub mod command_rate_type;
pub mod complete_objective_type;
pub mod config_block_type;
pub mod create_match_reducer;
pub mod create_profile_reducer;
pub mod custom_type;
pub mod delete_plans_type;
pub mod gamemode_type;
pub mod inventory_type;
pub mod join_match_reducer;
pub mod leave_match_reducer;
pub mod local_client_settings_table;
pub mod local_player_profile_table;
pub mod local_player_table;
pub mod logic_client_data_type;
pub mod logic_sync_type;
pub mod maintenance_schedule_type;
pub mod match_chat_table;
pub mod match_chat_type;
pub mod match_checksum_table;
pub mod match_checksum_type;
pub mod match_command_type;
pub mod match_kick_type;
pub mod match_mod_table;
pub mod match_mod_type;
pub mod match_plan_chunk_table;
pub mod match_plan_chunk_type;
pub mod match_plan_state_table;
pub mod match_plan_state_type;
pub mod match_player_state_table;
pub mod match_player_state_type;
pub mod match_snapshot_chunk_type;
pub mod match_snapshot_request_type;
pub mod match_snapshot_table;
pub mod match_snapshot_type;
pub mod match_state_table;
pub mod match_state_type;
pub mod match_status_type;
pub mod match_ui_event_table;
pub mod match_ui_event_type;
pub mod member_role_type;
pub mod menu_builder_choose_type;
pub mod menu_choose_type;
pub mod my_kick_table;
pub mod my_match_chat_table;
pub mod my_match_checksums_table;
pub mod my_match_commands_table;
pub mod my_match_members_table;
pub mod my_match_plan_chunks_table;
pub mod my_match_plans_table;
pub mod my_match_player_states_table;
pub mod my_match_snapshot_chunks_table;
pub mod my_match_snapshot_requests_table;
pub mod my_match_snapshots_table;
pub mod my_match_state_table;
pub mod my_match_table;
pub mod my_match_ui_events_table;
pub mod my_matches_table;
pub mod my_sender_command_state_table;
pub mod payload_type;
pub mod place_block_type;
pub mod player_ban_table;
pub mod player_ban_type;
pub mod player_profile_table;
pub mod player_profile_type;
pub mod player_session_table;
pub mod player_session_type;
pub mod player_spawn_type;
pub mod player_state_rate_type;
pub mod player_state_report_type;
pub mod player_table;
pub mod player_type;
pub mod protocol_info_table;
pub mod protocol_info_type;
pub mod publish_checksum_reducer;
pub mod publish_match_state_reducer;
pub mod publish_snapshot_reducer;
pub mod publish_ui_event_reducer;
pub mod relay_config_table;
pub mod relay_config_type;
pub mod relay_match_table;
pub mod relay_match_type;
pub mod relay_member_type;
pub mod report_plan_snapshot_reducer;
pub mod report_player_state_reducer;
pub mod request_snapshot_reducer;
pub mod research_unlock_type;
pub mod rotate_type;
pub mod run_wave_type;
pub mod send_chat_reducer;
pub mod send_match_command_reducer;
pub mod sender_command_state_type;
pub mod server_config_table;
pub mod server_config_type;
pub mod set_ready_reducer;
pub mod set_rule_type;
pub mod set_rules_type;
pub mod set_username_reducer;
pub mod snapshot_kind_type;
pub mod snapshot_rate_type;
pub mod start_match_reducer;
pub mod text_input_result_type;
pub mod ui_event_kind_type;
pub mod unit_command_queue_type;
pub mod unit_command_type;
pub mod unit_control_type;
pub mod unit_stance_type;
pub mod update_client_settings_reducer;
pub mod visibility_type;
pub mod whitelist_entry_table;
pub mod whitelist_entry_type;

pub use admin_identity_table::*;
pub use admin_identity_type::AdminIdentity;
pub use admin_switch_team_type::AdminSwitchTeam;
pub use admin_tile_op_type::AdminTileOp;
pub use all_matches_table::*;
pub use all_players_table::*;
pub use audit_kind_type::AuditKind;
pub use audit_log_type::AuditLog;
pub use authority_mode_type::AuthorityMode;
pub use break_block_type::BreakBlock;
pub use building_control_select_type::BuildingControlSelect;
pub use bullet_type::Bullet;
pub use chat_filter_table::*;
pub use chat_filter_type::ChatFilter;
pub use chat_kind_type::ChatKind;
pub use chat_rate_type::ChatRate;
pub use checksum_rate_type::ChecksumRate;
pub use client_settings_table::*;
pub use client_settings_type::ClientSettings;
pub use command_building_type::CommandBuilding;
pub use command_kind_type::CommandKind;
pub use command_rate_type::CommandRate;
pub use complete_objective_type::CompleteObjective;
pub use config_block_type::ConfigBlock;
pub use create_match_reducer::create_match;
pub use create_profile_reducer::create_profile;
pub use custom_type::Custom;
pub use delete_plans_type::DeletePlans;
pub use gamemode_type::Gamemode;
pub use inventory_type::Inventory;
pub use join_match_reducer::join_match;
pub use leave_match_reducer::leave_match;
pub use local_client_settings_table::*;
pub use local_player_profile_table::*;
pub use local_player_table::*;
pub use logic_client_data_type::LogicClientData;
pub use logic_sync_type::LogicSync;
pub use maintenance_schedule_type::MaintenanceSchedule;
pub use match_chat_table::*;
pub use match_chat_type::MatchChat;
pub use match_checksum_table::*;
pub use match_checksum_type::MatchChecksum;
pub use match_command_type::MatchCommand;
pub use match_kick_type::MatchKick;
pub use match_mod_table::*;
pub use match_mod_type::MatchMod;
pub use match_plan_chunk_table::*;
pub use match_plan_chunk_type::MatchPlanChunk;
pub use match_plan_state_table::*;
pub use match_plan_state_type::MatchPlanState;
pub use match_player_state_table::*;
pub use match_player_state_type::MatchPlayerState;
pub use match_snapshot_chunk_type::MatchSnapshotChunk;
pub use match_snapshot_request_type::MatchSnapshotRequest;
pub use match_snapshot_table::*;
pub use match_snapshot_type::MatchSnapshot;
pub use match_state_table::*;
pub use match_state_type::MatchState;
pub use match_status_type::MatchStatus;
pub use match_ui_event_table::*;
pub use match_ui_event_type::MatchUiEvent;
pub use member_role_type::MemberRole;
pub use menu_builder_choose_type::MenuBuilderChoose;
pub use menu_choose_type::MenuChoose;
pub use my_kick_table::*;
pub use my_match_chat_table::*;
pub use my_match_checksums_table::*;
pub use my_match_commands_table::*;
pub use my_match_members_table::*;
pub use my_match_plan_chunks_table::*;
pub use my_match_plans_table::*;
pub use my_match_player_states_table::*;
pub use my_match_snapshot_chunks_table::*;
pub use my_match_snapshot_requests_table::*;
pub use my_match_snapshots_table::*;
pub use my_match_state_table::*;
pub use my_match_table::*;
pub use my_match_ui_events_table::*;
pub use my_matches_table::*;
pub use my_sender_command_state_table::*;
pub use payload_type::Payload;
pub use place_block_type::PlaceBlock;
pub use player_ban_table::*;
pub use player_ban_type::PlayerBan;
pub use player_profile_table::*;
pub use player_profile_type::PlayerProfile;
pub use player_session_table::*;
pub use player_session_type::PlayerSession;
pub use player_spawn_type::PlayerSpawn;
pub use player_state_rate_type::PlayerStateRate;
pub use player_state_report_type::PlayerStateReport;
pub use player_table::*;
pub use player_type::Player;
pub use protocol_info_table::*;
pub use protocol_info_type::ProtocolInfo;
pub use publish_checksum_reducer::publish_checksum;
pub use publish_match_state_reducer::publish_match_state;
pub use publish_snapshot_reducer::publish_snapshot;
pub use publish_ui_event_reducer::publish_ui_event;
pub use relay_config_table::*;
pub use relay_config_type::RelayConfig;
pub use relay_match_table::*;
pub use relay_match_type::RelayMatch;
pub use relay_member_type::RelayMember;
pub use report_plan_snapshot_reducer::report_plan_snapshot;
pub use report_player_state_reducer::report_player_state;
pub use request_snapshot_reducer::request_snapshot;
pub use research_unlock_type::ResearchUnlock;
pub use rotate_type::Rotate;
pub use run_wave_type::RunWave;
pub use send_chat_reducer::send_chat;
pub use send_match_command_reducer::send_match_command;
pub use sender_command_state_type::SenderCommandState;
pub use server_config_table::*;
pub use server_config_type::ServerConfig;
pub use set_ready_reducer::set_ready;
pub use set_rule_type::SetRule;
pub use set_rules_type::SetRules;
pub use set_username_reducer::set_username;
pub use snapshot_kind_type::SnapshotKind;
pub use snapshot_rate_type::SnapshotRate;
pub use start_match_reducer::start_match;
pub use text_input_result_type::TextInputResult;
pub use ui_event_kind_type::UiEventKind;
pub use unit_command_queue_type::UnitCommandQueue;
pub use unit_command_type::UnitCommand;
pub use unit_control_type::UnitControl;
pub use unit_stance_type::UnitStance;
pub use update_client_settings_reducer::update_client_settings;
pub use visibility_type::Visibility;
pub use whitelist_entry_table::*;
pub use whitelist_entry_type::WhitelistEntry;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    CreateMatch {
        map_id: String,
        map_seed: u64,
        mode: Gamemode,
        mode_name: String,
        visibility: Visibility,
        password: Option<String>,
        max_players: u16,
        rules_json: String,
        build_id: String,
        content_hash: u64,
        mods: Vec<String>,
    },
    CreateProfile {
        name: String,
    },
    JoinMatch {
        match_id: u64,
        password: Option<String>,
        build_id: String,
        content_hash: u64,
        role: MemberRole,
        mods: Vec<String>,
    },
    LeaveMatch {
        match_id: u64,
    },
    PublishChecksum {
        match_id: u64,
        command_id: u64,
        sim_tick: u64,
        checksum: u64,
        checksum_version: u32,
        scope: u8,
    },
    PublishMatchState {
        match_id: u64,
        wave: i32,
        wavetime: f32,
        enemies: i32,
        paused: bool,
        game_over: bool,
        sim_tick: u64,
        last_command_id: u64,
    },
    PublishSnapshot {
        match_id: u64,
        kind: SnapshotKind,
        format: u32,
        checksum_version: u32,
        command_id: u64,
        sim_tick: u64,
        checksum: u64,
        map_id: String,
        map_seed: u64,
        map_hash: u64,
        build_id: String,
        content_hash: u64,
        blob: Vec<u8>,
    },
    PublishUiEvent {
        match_id: u64,
        kind: UiEventKind,
        target: Option<__sdk::Identity>,
        payload: Vec<u8>,
    },
    ReportPlanSnapshot {
        match_id: u64,
        group_id: u32,
        chunk_index: u16,
        chunk_count: u16,
        plans_blob: Vec<u8>,
    },
    ReportPlayerState {
        match_id: u64,
        report: PlayerStateReport,
    },
    RequestSnapshot {
        match_id: u64,
    },
    SendChat {
        match_id: u64,
        kind: ChatKind,
        text: String,
    },
    SendMatchCommand {
        match_id: u64,
        client_tick: u64,
        kind: CommandKind,
    },
    SetReady {
        match_id: u64,
        ready: bool,
    },
    SetUsername {
        username: String,
    },
    StartMatch {
        match_id: u64,
        force: bool,
    },
    UpdateClientSettings {
        ui_scale: f32,
        language: String,
        music_volume: f32,
        sfx_volume: f32,
        keybinds_json: String,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::CreateMatch { .. } => "create_match",
            Reducer::CreateProfile { .. } => "create_profile",
            Reducer::JoinMatch { .. } => "join_match",
            Reducer::LeaveMatch { .. } => "leave_match",
            Reducer::PublishChecksum { .. } => "publish_checksum",
            Reducer::PublishMatchState { .. } => "publish_match_state",
            Reducer::PublishSnapshot { .. } => "publish_snapshot",
            Reducer::PublishUiEvent { .. } => "publish_ui_event",
            Reducer::ReportPlanSnapshot { .. } => "report_plan_snapshot",
            Reducer::ReportPlayerState { .. } => "report_player_state",
            Reducer::RequestSnapshot { .. } => "request_snapshot",
            Reducer::SendChat { .. } => "send_chat",
            Reducer::SendMatchCommand { .. } => "send_match_command",
            Reducer::SetReady { .. } => "set_ready",
            Reducer::SetUsername { .. } => "set_username",
            Reducer::StartMatch { .. } => "start_match",
            Reducer::UpdateClientSettings { .. } => "update_client_settings",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::CreateMatch {
                map_id,
                map_seed,
                mode,
                mode_name,
                visibility,
                password,
                max_players,
                rules_json,
                build_id,
                content_hash,
                mods,
            } => __sats::bsatn::to_vec(&create_match_reducer::CreateMatchArgs {
                map_id: map_id.clone(),
                map_seed: map_seed.clone(),
                mode: mode.clone(),
                mode_name: mode_name.clone(),
                visibility: visibility.clone(),
                password: password.clone(),
                max_players: max_players.clone(),
                rules_json: rules_json.clone(),
                build_id: build_id.clone(),
                content_hash: content_hash.clone(),
                mods: mods.clone(),
            }),
            Reducer::CreateProfile { name } => {
                __sats::bsatn::to_vec(&create_profile_reducer::CreateProfileArgs {
                    name: name.clone(),
                })
            }
            Reducer::JoinMatch {
                match_id,
                password,
                build_id,
                content_hash,
                role,
                mods,
            } => __sats::bsatn::to_vec(&join_match_reducer::JoinMatchArgs {
                match_id: match_id.clone(),
                password: password.clone(),
                build_id: build_id.clone(),
                content_hash: content_hash.clone(),
                role: role.clone(),
                mods: mods.clone(),
            }),
            Reducer::LeaveMatch { match_id } => {
                __sats::bsatn::to_vec(&leave_match_reducer::LeaveMatchArgs {
                    match_id: match_id.clone(),
                })
            }
            Reducer::PublishChecksum {
                match_id,
                command_id,
                sim_tick,
                checksum,
                checksum_version,
                scope,
            } => __sats::bsatn::to_vec(&publish_checksum_reducer::PublishChecksumArgs {
                match_id: match_id.clone(),
                command_id: command_id.clone(),
                sim_tick: sim_tick.clone(),
                checksum: checksum.clone(),
                checksum_version: checksum_version.clone(),
                scope: scope.clone(),
            }),
            Reducer::PublishMatchState {
                match_id,
                wave,
                wavetime,
                enemies,
                paused,
                game_over,
                sim_tick,
                last_command_id,
            } => __sats::bsatn::to_vec(&publish_match_state_reducer::PublishMatchStateArgs {
                match_id: match_id.clone(),
                wave: wave.clone(),
                wavetime: wavetime.clone(),
                enemies: enemies.clone(),
                paused: paused.clone(),
                game_over: game_over.clone(),
                sim_tick: sim_tick.clone(),
                last_command_id: last_command_id.clone(),
            }),
            Reducer::PublishSnapshot {
                match_id,
                kind,
                format,
                checksum_version,
                command_id,
                sim_tick,
                checksum,
                map_id,
                map_seed,
                map_hash,
                build_id,
                content_hash,
                blob,
            } => __sats::bsatn::to_vec(&publish_snapshot_reducer::PublishSnapshotArgs {
                match_id: match_id.clone(),
                kind: kind.clone(),
                format: format.clone(),
                checksum_version: checksum_version.clone(),
                command_id: command_id.clone(),
                sim_tick: sim_tick.clone(),
                checksum: checksum.clone(),
                map_id: map_id.clone(),
                map_seed: map_seed.clone(),
                map_hash: map_hash.clone(),
                build_id: build_id.clone(),
                content_hash: content_hash.clone(),
                blob: blob.clone(),
            }),
            Reducer::PublishUiEvent {
                match_id,
                kind,
                target,
                payload,
            } => __sats::bsatn::to_vec(&publish_ui_event_reducer::PublishUiEventArgs {
                match_id: match_id.clone(),
                kind: kind.clone(),
                target: target.clone(),
                payload: payload.clone(),
            }),
            Reducer::ReportPlanSnapshot {
                match_id,
                group_id,
                chunk_index,
                chunk_count,
                plans_blob,
            } => __sats::bsatn::to_vec(&report_plan_snapshot_reducer::ReportPlanSnapshotArgs {
                match_id: match_id.clone(),
                group_id: group_id.clone(),
                chunk_index: chunk_index.clone(),
                chunk_count: chunk_count.clone(),
                plans_blob: plans_blob.clone(),
            }),
            Reducer::ReportPlayerState { match_id, report } => {
                __sats::bsatn::to_vec(&report_player_state_reducer::ReportPlayerStateArgs {
                    match_id: match_id.clone(),
                    report: report.clone(),
                })
            }
            Reducer::RequestSnapshot { match_id } => {
                __sats::bsatn::to_vec(&request_snapshot_reducer::RequestSnapshotArgs {
                    match_id: match_id.clone(),
                })
            }
            Reducer::SendChat {
                match_id,
                kind,
                text,
            } => __sats::bsatn::to_vec(&send_chat_reducer::SendChatArgs {
                match_id: match_id.clone(),
                kind: kind.clone(),
                text: text.clone(),
            }),
            Reducer::SendMatchCommand {
                match_id,
                client_tick,
                kind,
            } => __sats::bsatn::to_vec(&send_match_command_reducer::SendMatchCommandArgs {
                match_id: match_id.clone(),
                client_tick: client_tick.clone(),
                kind: kind.clone(),
            }),
            Reducer::SetReady { match_id, ready } => {
                __sats::bsatn::to_vec(&set_ready_reducer::SetReadyArgs {
                    match_id: match_id.clone(),
                    ready: ready.clone(),
                })
            }
            Reducer::SetUsername { username } => {
                __sats::bsatn::to_vec(&set_username_reducer::SetUsernameArgs {
                    username: username.clone(),
                })
            }
            Reducer::StartMatch { match_id, force } => {
                __sats::bsatn::to_vec(&start_match_reducer::StartMatchArgs {
                    match_id: match_id.clone(),
                    force: force.clone(),
                })
            }
            Reducer::UpdateClientSettings {
                ui_scale,
                language,
                music_volume,
                sfx_volume,
                keybinds_json,
            } => __sats::bsatn::to_vec(&update_client_settings_reducer::UpdateClientSettingsArgs {
                ui_scale: ui_scale.clone(),
                language: language.clone(),
                music_volume: music_volume.clone(),
                sfx_volume: sfx_volume.clone(),
                keybinds_json: keybinds_json.clone(),
            }),
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    admin_identity: __sdk::TableUpdate<AdminIdentity>,
    all_matches: __sdk::TableUpdate<RelayMatch>,
    all_players: __sdk::TableUpdate<Player>,
    chat_filter: __sdk::TableUpdate<ChatFilter>,
    client_settings: __sdk::TableUpdate<ClientSettings>,
    local_client_settings: __sdk::TableUpdate<ClientSettings>,
    local_player: __sdk::TableUpdate<Player>,
    local_player_profile: __sdk::TableUpdate<PlayerProfile>,
    match_chat: __sdk::TableUpdate<MatchChat>,
    match_checksum: __sdk::TableUpdate<MatchChecksum>,
    match_mod: __sdk::TableUpdate<MatchMod>,
    match_plan_chunk: __sdk::TableUpdate<MatchPlanChunk>,
    match_plan_state: __sdk::TableUpdate<MatchPlanState>,
    match_player_state: __sdk::TableUpdate<MatchPlayerState>,
    match_snapshot: __sdk::TableUpdate<MatchSnapshot>,
    match_state: __sdk::TableUpdate<MatchState>,
    match_ui_event: __sdk::TableUpdate<MatchUiEvent>,
    my_kick: __sdk::TableUpdate<MatchKick>,
    my_match: __sdk::TableUpdate<RelayMatch>,
    my_match_chat: __sdk::TableUpdate<MatchChat>,
    my_match_checksums: __sdk::TableUpdate<MatchChecksum>,
    my_match_commands: __sdk::TableUpdate<MatchCommand>,
    my_match_members: __sdk::TableUpdate<RelayMember>,
    my_match_plan_chunks: __sdk::TableUpdate<MatchPlanChunk>,
    my_match_plans: __sdk::TableUpdate<MatchPlanState>,
    my_match_player_states: __sdk::TableUpdate<MatchPlayerState>,
    my_match_snapshot_chunks: __sdk::TableUpdate<MatchSnapshotChunk>,
    my_match_snapshot_requests: __sdk::TableUpdate<MatchSnapshotRequest>,
    my_match_snapshots: __sdk::TableUpdate<MatchSnapshot>,
    my_match_state: __sdk::TableUpdate<MatchState>,
    my_match_ui_events: __sdk::TableUpdate<MatchUiEvent>,
    my_matches: __sdk::TableUpdate<RelayMatch>,
    my_sender_command_state: __sdk::TableUpdate<SenderCommandState>,
    player: __sdk::TableUpdate<Player>,
    player_ban: __sdk::TableUpdate<PlayerBan>,
    player_profile: __sdk::TableUpdate<PlayerProfile>,
    player_session: __sdk::TableUpdate<PlayerSession>,
    protocol_info: __sdk::TableUpdate<ProtocolInfo>,
    relay_config: __sdk::TableUpdate<RelayConfig>,
    relay_match: __sdk::TableUpdate<RelayMatch>,
    server_config: __sdk::TableUpdate<ServerConfig>,
    whitelist_entry: __sdk::TableUpdate<WhitelistEntry>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "admin_identity" => db_update
                    .admin_identity
                    .append(admin_identity_table::parse_table_update(table_update)?),
                "all_matches" => db_update
                    .all_matches
                    .append(all_matches_table::parse_table_update(table_update)?),
                "all_players" => db_update
                    .all_players
                    .append(all_players_table::parse_table_update(table_update)?),
                "chat_filter" => db_update
                    .chat_filter
                    .append(chat_filter_table::parse_table_update(table_update)?),
                "client_settings" => db_update
                    .client_settings
                    .append(client_settings_table::parse_table_update(table_update)?),
                "local_client_settings" => db_update.local_client_settings.append(
                    local_client_settings_table::parse_table_update(table_update)?,
                ),
                "local_player" => db_update
                    .local_player
                    .append(local_player_table::parse_table_update(table_update)?),
                "local_player_profile" => db_update.local_player_profile.append(
                    local_player_profile_table::parse_table_update(table_update)?,
                ),
                "match_chat" => db_update
                    .match_chat
                    .append(match_chat_table::parse_table_update(table_update)?),
                "match_checksum" => db_update
                    .match_checksum
                    .append(match_checksum_table::parse_table_update(table_update)?),
                "match_mod" => db_update
                    .match_mod
                    .append(match_mod_table::parse_table_update(table_update)?),
                "match_plan_chunk" => db_update
                    .match_plan_chunk
                    .append(match_plan_chunk_table::parse_table_update(table_update)?),
                "match_plan_state" => db_update
                    .match_plan_state
                    .append(match_plan_state_table::parse_table_update(table_update)?),
                "match_player_state" => db_update
                    .match_player_state
                    .append(match_player_state_table::parse_table_update(table_update)?),
                "match_snapshot" => db_update
                    .match_snapshot
                    .append(match_snapshot_table::parse_table_update(table_update)?),
                "match_state" => db_update
                    .match_state
                    .append(match_state_table::parse_table_update(table_update)?),
                "match_ui_event" => db_update
                    .match_ui_event
                    .append(match_ui_event_table::parse_table_update(table_update)?),
                "my_kick" => db_update
                    .my_kick
                    .append(my_kick_table::parse_table_update(table_update)?),
                "my_match" => db_update
                    .my_match
                    .append(my_match_table::parse_table_update(table_update)?),
                "my_match_chat" => db_update
                    .my_match_chat
                    .append(my_match_chat_table::parse_table_update(table_update)?),
                "my_match_checksums" => db_update
                    .my_match_checksums
                    .append(my_match_checksums_table::parse_table_update(table_update)?),
                "my_match_commands" => db_update
                    .my_match_commands
                    .append(my_match_commands_table::parse_table_update(table_update)?),
                "my_match_members" => db_update
                    .my_match_members
                    .append(my_match_members_table::parse_table_update(table_update)?),
                "my_match_plan_chunks" => db_update.my_match_plan_chunks.append(
                    my_match_plan_chunks_table::parse_table_update(table_update)?,
                ),
                "my_match_plans" => db_update
                    .my_match_plans
                    .append(my_match_plans_table::parse_table_update(table_update)?),
                "my_match_player_states" => db_update.my_match_player_states.append(
                    my_match_player_states_table::parse_table_update(table_update)?,
                ),
                "my_match_snapshot_chunks" => db_update.my_match_snapshot_chunks.append(
                    my_match_snapshot_chunks_table::parse_table_update(table_update)?,
                ),
                "my_match_snapshot_requests" => db_update.my_match_snapshot_requests.append(
                    my_match_snapshot_requests_table::parse_table_update(table_update)?,
                ),
                "my_match_snapshots" => db_update
                    .my_match_snapshots
                    .append(my_match_snapshots_table::parse_table_update(table_update)?),
                "my_match_state" => db_update
                    .my_match_state
                    .append(my_match_state_table::parse_table_update(table_update)?),
                "my_match_ui_events" => db_update
                    .my_match_ui_events
                    .append(my_match_ui_events_table::parse_table_update(table_update)?),
                "my_matches" => db_update
                    .my_matches
                    .append(my_matches_table::parse_table_update(table_update)?),
                "my_sender_command_state" => db_update.my_sender_command_state.append(
                    my_sender_command_state_table::parse_table_update(table_update)?,
                ),
                "player" => db_update
                    .player
                    .append(player_table::parse_table_update(table_update)?),
                "player_ban" => db_update
                    .player_ban
                    .append(player_ban_table::parse_table_update(table_update)?),
                "player_profile" => db_update
                    .player_profile
                    .append(player_profile_table::parse_table_update(table_update)?),
                "player_session" => db_update
                    .player_session
                    .append(player_session_table::parse_table_update(table_update)?),
                "protocol_info" => db_update
                    .protocol_info
                    .append(protocol_info_table::parse_table_update(table_update)?),
                "relay_config" => db_update
                    .relay_config
                    .append(relay_config_table::parse_table_update(table_update)?),
                "relay_match" => db_update
                    .relay_match
                    .append(relay_match_table::parse_table_update(table_update)?),
                "server_config" => db_update
                    .server_config
                    .append(server_config_table::parse_table_update(table_update)?),
                "whitelist_entry" => db_update
                    .whitelist_entry
                    .append(whitelist_entry_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.admin_identity = cache
            .apply_diff_to_table::<AdminIdentity>("admin_identity", &self.admin_identity)
            .with_updates_by_pk(|row| &row.identity);
        diff.chat_filter = cache
            .apply_diff_to_table::<ChatFilter>("chat_filter", &self.chat_filter)
            .with_updates_by_pk(|row| &row.filter_id);
        diff.client_settings = cache
            .apply_diff_to_table::<ClientSettings>("client_settings", &self.client_settings)
            .with_updates_by_pk(|row| &row.identity);
        diff.match_chat = cache
            .apply_diff_to_table::<MatchChat>("match_chat", &self.match_chat)
            .with_updates_by_pk(|row| &row.chat_id);
        diff.match_checksum = cache
            .apply_diff_to_table::<MatchChecksum>("match_checksum", &self.match_checksum)
            .with_updates_by_pk(|row| &row.checksum_id);
        diff.match_mod = cache
            .apply_diff_to_table::<MatchMod>("match_mod", &self.match_mod)
            .with_updates_by_pk(|row| &row.match_mod_id);
        diff.match_plan_chunk = cache
            .apply_diff_to_table::<MatchPlanChunk>("match_plan_chunk", &self.match_plan_chunk)
            .with_updates_by_pk(|row| &row.chunk_id);
        diff.match_plan_state = cache
            .apply_diff_to_table::<MatchPlanState>("match_plan_state", &self.match_plan_state)
            .with_updates_by_pk(|row| &row.plan_state_id);
        diff.match_player_state = cache
            .apply_diff_to_table::<MatchPlayerState>("match_player_state", &self.match_player_state)
            .with_updates_by_pk(|row| &row.state_id);
        diff.match_snapshot = cache
            .apply_diff_to_table::<MatchSnapshot>("match_snapshot", &self.match_snapshot)
            .with_updates_by_pk(|row| &row.snapshot_id);
        diff.match_state = cache
            .apply_diff_to_table::<MatchState>("match_state", &self.match_state)
            .with_updates_by_pk(|row| &row.state_id);
        diff.match_ui_event = cache
            .apply_diff_to_table::<MatchUiEvent>("match_ui_event", &self.match_ui_event)
            .with_updates_by_pk(|row| &row.event_id);
        diff.player = cache
            .apply_diff_to_table::<Player>("player", &self.player)
            .with_updates_by_pk(|row| &row.identity);
        diff.player_ban = cache
            .apply_diff_to_table::<PlayerBan>("player_ban", &self.player_ban)
            .with_updates_by_pk(|row| &row.ban_id);
        diff.player_profile = cache
            .apply_diff_to_table::<PlayerProfile>("player_profile", &self.player_profile)
            .with_updates_by_pk(|row| &row.profile_id);
        diff.player_session = cache
            .apply_diff_to_table::<PlayerSession>("player_session", &self.player_session)
            .with_updates_by_pk(|row| &row.session_id);
        diff.protocol_info = cache
            .apply_diff_to_table::<ProtocolInfo>("protocol_info", &self.protocol_info)
            .with_updates_by_pk(|row| &row.id);
        diff.relay_config = cache
            .apply_diff_to_table::<RelayConfig>("relay_config", &self.relay_config)
            .with_updates_by_pk(|row| &row.id);
        diff.relay_match = cache
            .apply_diff_to_table::<RelayMatch>("relay_match", &self.relay_match)
            .with_updates_by_pk(|row| &row.match_id);
        diff.server_config = cache
            .apply_diff_to_table::<ServerConfig>("server_config", &self.server_config)
            .with_updates_by_pk(|row| &row.id);
        diff.whitelist_entry = cache
            .apply_diff_to_table::<WhitelistEntry>("whitelist_entry", &self.whitelist_entry)
            .with_updates_by_pk(|row| &row.identity);
        diff.all_matches =
            cache.apply_diff_to_table::<RelayMatch>("all_matches", &self.all_matches);
        diff.all_players = cache
            .apply_diff_to_table::<Player>("all_players", &self.all_players)
            .with_updates_by_pk(|row| &row.identity);
        diff.local_client_settings = cache.apply_diff_to_table::<ClientSettings>(
            "local_client_settings",
            &self.local_client_settings,
        );
        diff.local_player = cache.apply_diff_to_table::<Player>("local_player", &self.local_player);
        diff.local_player_profile = cache.apply_diff_to_table::<PlayerProfile>(
            "local_player_profile",
            &self.local_player_profile,
        );
        diff.my_kick = cache.apply_diff_to_table::<MatchKick>("my_kick", &self.my_kick);
        diff.my_match = cache.apply_diff_to_table::<RelayMatch>("my_match", &self.my_match);
        diff.my_match_chat =
            cache.apply_diff_to_table::<MatchChat>("my_match_chat", &self.my_match_chat);
        diff.my_match_checksums = cache
            .apply_diff_to_table::<MatchChecksum>("my_match_checksums", &self.my_match_checksums);
        diff.my_match_commands =
            cache.apply_diff_to_table::<MatchCommand>("my_match_commands", &self.my_match_commands);
        diff.my_match_members =
            cache.apply_diff_to_table::<RelayMember>("my_match_members", &self.my_match_members);
        diff.my_match_plan_chunks = cache.apply_diff_to_table::<MatchPlanChunk>(
            "my_match_plan_chunks",
            &self.my_match_plan_chunks,
        );
        diff.my_match_plans =
            cache.apply_diff_to_table::<MatchPlanState>("my_match_plans", &self.my_match_plans);
        diff.my_match_player_states = cache.apply_diff_to_table::<MatchPlayerState>(
            "my_match_player_states",
            &self.my_match_player_states,
        );
        diff.my_match_snapshot_chunks = cache.apply_diff_to_table::<MatchSnapshotChunk>(
            "my_match_snapshot_chunks",
            &self.my_match_snapshot_chunks,
        );
        diff.my_match_snapshot_requests = cache.apply_diff_to_table::<MatchSnapshotRequest>(
            "my_match_snapshot_requests",
            &self.my_match_snapshot_requests,
        );
        diff.my_match_snapshots = cache
            .apply_diff_to_table::<MatchSnapshot>("my_match_snapshots", &self.my_match_snapshots);
        diff.my_match_state =
            cache.apply_diff_to_table::<MatchState>("my_match_state", &self.my_match_state);
        diff.my_match_ui_events = cache
            .apply_diff_to_table::<MatchUiEvent>("my_match_ui_events", &self.my_match_ui_events);
        diff.my_matches = cache.apply_diff_to_table::<RelayMatch>("my_matches", &self.my_matches);
        diff.my_sender_command_state = cache.apply_diff_to_table::<SenderCommandState>(
            "my_sender_command_state",
            &self.my_sender_command_state,
        );

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "admin_identity" => db_update
                    .admin_identity
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "all_matches" => db_update
                    .all_matches
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "all_players" => db_update
                    .all_players
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "chat_filter" => db_update
                    .chat_filter
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "client_settings" => db_update
                    .client_settings
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "local_client_settings" => db_update
                    .local_client_settings
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "local_player" => db_update
                    .local_player
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "local_player_profile" => db_update
                    .local_player_profile
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "match_chat" => db_update
                    .match_chat
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "match_checksum" => db_update
                    .match_checksum
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "match_mod" => db_update
                    .match_mod
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "match_plan_chunk" => db_update
                    .match_plan_chunk
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "match_plan_state" => db_update
                    .match_plan_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "match_player_state" => db_update
                    .match_player_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "match_snapshot" => db_update
                    .match_snapshot
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "match_state" => db_update
                    .match_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "match_ui_event" => db_update
                    .match_ui_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_kick" => db_update
                    .my_kick
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_match" => db_update
                    .my_match
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_match_chat" => db_update
                    .my_match_chat
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_match_checksums" => db_update
                    .my_match_checksums
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_match_commands" => db_update
                    .my_match_commands
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_match_members" => db_update
                    .my_match_members
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_match_plan_chunks" => db_update
                    .my_match_plan_chunks
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_match_plans" => db_update
                    .my_match_plans
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_match_player_states" => db_update
                    .my_match_player_states
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_match_snapshot_chunks" => db_update
                    .my_match_snapshot_chunks
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_match_snapshot_requests" => db_update
                    .my_match_snapshot_requests
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_match_snapshots" => db_update
                    .my_match_snapshots
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_match_state" => db_update
                    .my_match_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_match_ui_events" => db_update
                    .my_match_ui_events
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_matches" => db_update
                    .my_matches
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "my_sender_command_state" => db_update
                    .my_sender_command_state
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_ban" => db_update
                    .player_ban
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_profile" => db_update
                    .player_profile
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "player_session" => db_update
                    .player_session
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "protocol_info" => db_update
                    .protocol_info
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "relay_config" => db_update
                    .relay_config
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "relay_match" => db_update
                    .relay_match
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "server_config" => db_update
                    .server_config
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "whitelist_entry" => db_update
                    .whitelist_entry
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "admin_identity" => db_update
                    .admin_identity
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "all_matches" => db_update
                    .all_matches
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "all_players" => db_update
                    .all_players
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "chat_filter" => db_update
                    .chat_filter
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "client_settings" => db_update
                    .client_settings
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "local_client_settings" => db_update
                    .local_client_settings
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "local_player" => db_update
                    .local_player
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "local_player_profile" => db_update
                    .local_player_profile
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "match_chat" => db_update
                    .match_chat
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "match_checksum" => db_update
                    .match_checksum
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "match_mod" => db_update
                    .match_mod
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "match_plan_chunk" => db_update
                    .match_plan_chunk
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "match_plan_state" => db_update
                    .match_plan_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "match_player_state" => db_update
                    .match_player_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "match_snapshot" => db_update
                    .match_snapshot
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "match_state" => db_update
                    .match_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "match_ui_event" => db_update
                    .match_ui_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_kick" => db_update
                    .my_kick
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_match" => db_update
                    .my_match
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_match_chat" => db_update
                    .my_match_chat
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_match_checksums" => db_update
                    .my_match_checksums
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_match_commands" => db_update
                    .my_match_commands
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_match_members" => db_update
                    .my_match_members
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_match_plan_chunks" => db_update
                    .my_match_plan_chunks
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_match_plans" => db_update
                    .my_match_plans
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_match_player_states" => db_update
                    .my_match_player_states
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_match_snapshot_chunks" => db_update
                    .my_match_snapshot_chunks
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_match_snapshot_requests" => db_update
                    .my_match_snapshot_requests
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_match_snapshots" => db_update
                    .my_match_snapshots
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_match_state" => db_update
                    .my_match_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_match_ui_events" => db_update
                    .my_match_ui_events
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_matches" => db_update
                    .my_matches
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "my_sender_command_state" => db_update
                    .my_sender_command_state
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player" => db_update
                    .player
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_ban" => db_update
                    .player_ban
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_profile" => db_update
                    .player_profile
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "player_session" => db_update
                    .player_session
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "protocol_info" => db_update
                    .protocol_info
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "relay_config" => db_update
                    .relay_config
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "relay_match" => db_update
                    .relay_match
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "server_config" => db_update
                    .server_config
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "whitelist_entry" => db_update
                    .whitelist_entry
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    admin_identity: __sdk::TableAppliedDiff<'r, AdminIdentity>,
    all_matches: __sdk::TableAppliedDiff<'r, RelayMatch>,
    all_players: __sdk::TableAppliedDiff<'r, Player>,
    chat_filter: __sdk::TableAppliedDiff<'r, ChatFilter>,
    client_settings: __sdk::TableAppliedDiff<'r, ClientSettings>,
    local_client_settings: __sdk::TableAppliedDiff<'r, ClientSettings>,
    local_player: __sdk::TableAppliedDiff<'r, Player>,
    local_player_profile: __sdk::TableAppliedDiff<'r, PlayerProfile>,
    match_chat: __sdk::TableAppliedDiff<'r, MatchChat>,
    match_checksum: __sdk::TableAppliedDiff<'r, MatchChecksum>,
    match_mod: __sdk::TableAppliedDiff<'r, MatchMod>,
    match_plan_chunk: __sdk::TableAppliedDiff<'r, MatchPlanChunk>,
    match_plan_state: __sdk::TableAppliedDiff<'r, MatchPlanState>,
    match_player_state: __sdk::TableAppliedDiff<'r, MatchPlayerState>,
    match_snapshot: __sdk::TableAppliedDiff<'r, MatchSnapshot>,
    match_state: __sdk::TableAppliedDiff<'r, MatchState>,
    match_ui_event: __sdk::TableAppliedDiff<'r, MatchUiEvent>,
    my_kick: __sdk::TableAppliedDiff<'r, MatchKick>,
    my_match: __sdk::TableAppliedDiff<'r, RelayMatch>,
    my_match_chat: __sdk::TableAppliedDiff<'r, MatchChat>,
    my_match_checksums: __sdk::TableAppliedDiff<'r, MatchChecksum>,
    my_match_commands: __sdk::TableAppliedDiff<'r, MatchCommand>,
    my_match_members: __sdk::TableAppliedDiff<'r, RelayMember>,
    my_match_plan_chunks: __sdk::TableAppliedDiff<'r, MatchPlanChunk>,
    my_match_plans: __sdk::TableAppliedDiff<'r, MatchPlanState>,
    my_match_player_states: __sdk::TableAppliedDiff<'r, MatchPlayerState>,
    my_match_snapshot_chunks: __sdk::TableAppliedDiff<'r, MatchSnapshotChunk>,
    my_match_snapshot_requests: __sdk::TableAppliedDiff<'r, MatchSnapshotRequest>,
    my_match_snapshots: __sdk::TableAppliedDiff<'r, MatchSnapshot>,
    my_match_state: __sdk::TableAppliedDiff<'r, MatchState>,
    my_match_ui_events: __sdk::TableAppliedDiff<'r, MatchUiEvent>,
    my_matches: __sdk::TableAppliedDiff<'r, RelayMatch>,
    my_sender_command_state: __sdk::TableAppliedDiff<'r, SenderCommandState>,
    player: __sdk::TableAppliedDiff<'r, Player>,
    player_ban: __sdk::TableAppliedDiff<'r, PlayerBan>,
    player_profile: __sdk::TableAppliedDiff<'r, PlayerProfile>,
    player_session: __sdk::TableAppliedDiff<'r, PlayerSession>,
    protocol_info: __sdk::TableAppliedDiff<'r, ProtocolInfo>,
    relay_config: __sdk::TableAppliedDiff<'r, RelayConfig>,
    relay_match: __sdk::TableAppliedDiff<'r, RelayMatch>,
    server_config: __sdk::TableAppliedDiff<'r, ServerConfig>,
    whitelist_entry: __sdk::TableAppliedDiff<'r, WhitelistEntry>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<AdminIdentity>(
            "admin_identity",
            &self.admin_identity,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RelayMatch>("all_matches", &self.all_matches, event);
        callbacks.invoke_table_row_callbacks::<Player>("all_players", &self.all_players, event);
        callbacks.invoke_table_row_callbacks::<ChatFilter>("chat_filter", &self.chat_filter, event);
        callbacks.invoke_table_row_callbacks::<ClientSettings>(
            "client_settings",
            &self.client_settings,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ClientSettings>(
            "local_client_settings",
            &self.local_client_settings,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Player>("local_player", &self.local_player, event);
        callbacks.invoke_table_row_callbacks::<PlayerProfile>(
            "local_player_profile",
            &self.local_player_profile,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchChat>("match_chat", &self.match_chat, event);
        callbacks.invoke_table_row_callbacks::<MatchChecksum>(
            "match_checksum",
            &self.match_checksum,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchMod>("match_mod", &self.match_mod, event);
        callbacks.invoke_table_row_callbacks::<MatchPlanChunk>(
            "match_plan_chunk",
            &self.match_plan_chunk,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchPlanState>(
            "match_plan_state",
            &self.match_plan_state,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchPlayerState>(
            "match_player_state",
            &self.match_player_state,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchSnapshot>(
            "match_snapshot",
            &self.match_snapshot,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchState>("match_state", &self.match_state, event);
        callbacks.invoke_table_row_callbacks::<MatchUiEvent>(
            "match_ui_event",
            &self.match_ui_event,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchKick>("my_kick", &self.my_kick, event);
        callbacks.invoke_table_row_callbacks::<RelayMatch>("my_match", &self.my_match, event);
        callbacks.invoke_table_row_callbacks::<MatchChat>(
            "my_match_chat",
            &self.my_match_chat,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchChecksum>(
            "my_match_checksums",
            &self.my_match_checksums,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchCommand>(
            "my_match_commands",
            &self.my_match_commands,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RelayMember>(
            "my_match_members",
            &self.my_match_members,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchPlanChunk>(
            "my_match_plan_chunks",
            &self.my_match_plan_chunks,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchPlanState>(
            "my_match_plans",
            &self.my_match_plans,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchPlayerState>(
            "my_match_player_states",
            &self.my_match_player_states,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchSnapshotChunk>(
            "my_match_snapshot_chunks",
            &self.my_match_snapshot_chunks,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchSnapshotRequest>(
            "my_match_snapshot_requests",
            &self.my_match_snapshot_requests,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchSnapshot>(
            "my_match_snapshots",
            &self.my_match_snapshots,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchState>(
            "my_match_state",
            &self.my_match_state,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MatchUiEvent>(
            "my_match_ui_events",
            &self.my_match_ui_events,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RelayMatch>("my_matches", &self.my_matches, event);
        callbacks.invoke_table_row_callbacks::<SenderCommandState>(
            "my_sender_command_state",
            &self.my_sender_command_state,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Player>("player", &self.player, event);
        callbacks.invoke_table_row_callbacks::<PlayerBan>("player_ban", &self.player_ban, event);
        callbacks.invoke_table_row_callbacks::<PlayerProfile>(
            "player_profile",
            &self.player_profile,
            event,
        );
        callbacks.invoke_table_row_callbacks::<PlayerSession>(
            "player_session",
            &self.player_session,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ProtocolInfo>(
            "protocol_info",
            &self.protocol_info,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RelayConfig>(
            "relay_config",
            &self.relay_config,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RelayMatch>("relay_match", &self.relay_match, event);
        callbacks.invoke_table_row_callbacks::<ServerConfig>(
            "server_config",
            &self.server_config,
            event,
        );
        callbacks.invoke_table_row_callbacks::<WhitelistEntry>(
            "whitelist_entry",
            &self.whitelist_entry,
            event,
        );
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        admin_identity_table::register_table(client_cache);
        all_matches_table::register_table(client_cache);
        all_players_table::register_table(client_cache);
        chat_filter_table::register_table(client_cache);
        client_settings_table::register_table(client_cache);
        local_client_settings_table::register_table(client_cache);
        local_player_table::register_table(client_cache);
        local_player_profile_table::register_table(client_cache);
        match_chat_table::register_table(client_cache);
        match_checksum_table::register_table(client_cache);
        match_mod_table::register_table(client_cache);
        match_plan_chunk_table::register_table(client_cache);
        match_plan_state_table::register_table(client_cache);
        match_player_state_table::register_table(client_cache);
        match_snapshot_table::register_table(client_cache);
        match_state_table::register_table(client_cache);
        match_ui_event_table::register_table(client_cache);
        my_kick_table::register_table(client_cache);
        my_match_table::register_table(client_cache);
        my_match_chat_table::register_table(client_cache);
        my_match_checksums_table::register_table(client_cache);
        my_match_commands_table::register_table(client_cache);
        my_match_members_table::register_table(client_cache);
        my_match_plan_chunks_table::register_table(client_cache);
        my_match_plans_table::register_table(client_cache);
        my_match_player_states_table::register_table(client_cache);
        my_match_snapshot_chunks_table::register_table(client_cache);
        my_match_snapshot_requests_table::register_table(client_cache);
        my_match_snapshots_table::register_table(client_cache);
        my_match_state_table::register_table(client_cache);
        my_match_ui_events_table::register_table(client_cache);
        my_matches_table::register_table(client_cache);
        my_sender_command_state_table::register_table(client_cache);
        player_table::register_table(client_cache);
        player_ban_table::register_table(client_cache);
        player_profile_table::register_table(client_cache);
        player_session_table::register_table(client_cache);
        protocol_info_table::register_table(client_cache);
        relay_config_table::register_table(client_cache);
        relay_match_table::register_table(client_cache);
        server_config_table::register_table(client_cache);
        whitelist_entry_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "admin_identity",
        "all_matches",
        "all_players",
        "chat_filter",
        "client_settings",
        "local_client_settings",
        "local_player",
        "local_player_profile",
        "match_chat",
        "match_checksum",
        "match_mod",
        "match_plan_chunk",
        "match_plan_state",
        "match_player_state",
        "match_snapshot",
        "match_state",
        "match_ui_event",
        "my_kick",
        "my_match",
        "my_match_chat",
        "my_match_checksums",
        "my_match_commands",
        "my_match_members",
        "my_match_plan_chunks",
        "my_match_plans",
        "my_match_player_states",
        "my_match_snapshot_chunks",
        "my_match_snapshot_requests",
        "my_match_snapshots",
        "my_match_state",
        "my_match_ui_events",
        "my_matches",
        "my_sender_command_state",
        "player",
        "player_ban",
        "player_profile",
        "player_session",
        "protocol_info",
        "relay_config",
        "relay_match",
        "server_config",
        "whitelist_entry",
    ];
}
