// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::campaign_type::Campaign;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_campaigns`.
///
/// Obtain a handle from the [`MyCampaignsTableAccess::my_campaigns`] method on [`super::RemoteTables`],
/// like `ctx.db.my_campaigns()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_campaigns().on_insert(...)`.
pub struct MyCampaignsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Campaign>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_campaigns`.
pub struct MyCampaignsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyCampaignsTableAccessor {
    type Row = Campaign;
    type Handle<'db> = MyCampaignsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_campaigns()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_campaigns`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyCampaignsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyCampaignsTableHandle`], which mediates access to the table `my_campaigns`.
    fn my_campaigns(&self) -> MyCampaignsTableHandle<'_>;
}

impl MyCampaignsTableAccess for super::RemoteTables {
    fn my_campaigns(&self) -> MyCampaignsTableHandle<'_> {
        MyCampaignsTableHandle {
            imp: self.imp.get_table::<Campaign>("my_campaigns"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyCampaignsInsertCallbackId(__sdk::CallbackId);
pub struct MyCampaignsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyCampaignsTableHandle<'ctx> {
    type Row = Campaign;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Campaign> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyCampaignsTableHandle<'ctx> {
    type Row = Campaign;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Campaign> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyCampaignsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyCampaignsInsertCallbackId {
        MyCampaignsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyCampaignsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyCampaignsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyCampaignsDeleteCallbackId {
        MyCampaignsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyCampaignsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyCampaignsTableHandle<'ctx> {
    type InsertCallbackId = MyCampaignsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyCampaignsInsertCallbackId {
        MyCampaignsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyCampaignsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyCampaignsTableHandle<'ctx> {
    type DeleteCallbackId = MyCampaignsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyCampaignsDeleteCallbackId {
        MyCampaignsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyCampaignsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Campaign>("my_campaigns");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Campaign>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Campaign>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Campaign`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_campaignsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Campaign`.
    fn my_campaigns(&self) -> __sdk::__query_builder::Table<Campaign>;
}

impl my_campaignsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_campaigns(&self) -> __sdk::__query_builder::Table<Campaign> {
        __sdk::__query_builder::Table::new("my_campaigns")
    }
}
