// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_kick_type::MatchKick;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_kick`.
///
/// Obtain a handle from the [`MyKickTableAccess::my_kick`] method on [`super::RemoteTables`],
/// like `ctx.db.my_kick()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_kick().on_insert(...)`.
pub struct MyKickTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchKick>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_kick`.
pub struct MyKickTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyKickTableAccessor {
    type Row = MatchKick;
    type Handle<'db> = MyKickTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_kick()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_kick`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyKickTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyKickTableHandle`], which mediates access to the table `my_kick`.
    fn my_kick(&self) -> MyKickTableHandle<'_>;
}

impl MyKickTableAccess for super::RemoteTables {
    fn my_kick(&self) -> MyKickTableHandle<'_> {
        MyKickTableHandle {
            imp: self.imp.get_table::<MatchKick>("my_kick"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyKickInsertCallbackId(__sdk::CallbackId);
pub struct MyKickDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyKickTableHandle<'ctx> {
    type Row = MatchKick;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchKick> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyKickTableHandle<'ctx> {
    type Row = MatchKick;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchKick> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyKickInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyKickInsertCallbackId {
        MyKickInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyKickInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyKickDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyKickDeleteCallbackId {
        MyKickDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyKickDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyKickTableHandle<'ctx> {
    type InsertCallbackId = MyKickInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyKickInsertCallbackId {
        MyKickInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyKickInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyKickTableHandle<'ctx> {
    type DeleteCallbackId = MyKickDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyKickDeleteCallbackId {
        MyKickDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyKickDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchKick>("my_kick");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchKick>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchKick>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchKick`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_kickQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchKick`.
    fn my_kick(&self) -> __sdk::__query_builder::Table<MatchKick>;
}

impl my_kickQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_kick(&self) -> __sdk::__query_builder::Table<MatchKick> {
        __sdk::__query_builder::Table::new("my_kick")
    }
}
