// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_ui_event_type::MatchUiEvent;
use super::ui_event_kind_type::UiEventKind;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_match_ui_events`.
///
/// Obtain a handle from the [`MyMatchUiEventsTableAccess::my_match_ui_events`] method on [`super::RemoteTables`],
/// like `ctx.db.my_match_ui_events()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_match_ui_events().on_insert(...)`.
pub struct MyMatchUiEventsTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchUiEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_match_ui_events`.
pub struct MyMatchUiEventsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyMatchUiEventsTableAccessor {
    type Row = MatchUiEvent;
    type Handle<'db> = MyMatchUiEventsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_match_ui_events()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_match_ui_events`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyMatchUiEventsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyMatchUiEventsTableHandle`], which mediates access to the table `my_match_ui_events`.
    fn my_match_ui_events(&self) -> MyMatchUiEventsTableHandle<'_>;
}

impl MyMatchUiEventsTableAccess for super::RemoteTables {
    fn my_match_ui_events(&self) -> MyMatchUiEventsTableHandle<'_> {
        MyMatchUiEventsTableHandle {
            imp: self.imp.get_table::<MatchUiEvent>("my_match_ui_events"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyMatchUiEventsInsertCallbackId(__sdk::CallbackId);
pub struct MyMatchUiEventsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyMatchUiEventsTableHandle<'ctx> {
    type Row = MatchUiEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchUiEvent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyMatchUiEventsTableHandle<'ctx> {
    type Row = MatchUiEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchUiEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyMatchUiEventsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchUiEventsInsertCallbackId {
        MyMatchUiEventsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchUiEventsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyMatchUiEventsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchUiEventsDeleteCallbackId {
        MyMatchUiEventsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchUiEventsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyMatchUiEventsTableHandle<'ctx> {
    type InsertCallbackId = MyMatchUiEventsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchUiEventsInsertCallbackId {
        MyMatchUiEventsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchUiEventsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyMatchUiEventsTableHandle<'ctx> {
    type DeleteCallbackId = MyMatchUiEventsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchUiEventsDeleteCallbackId {
        MyMatchUiEventsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchUiEventsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchUiEvent>("my_match_ui_events");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchUiEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchUiEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchUiEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_match_ui_eventsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchUiEvent`.
    fn my_match_ui_events(&self) -> __sdk::__query_builder::Table<MatchUiEvent>;
}

impl my_match_ui_eventsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_match_ui_events(&self) -> __sdk::__query_builder::Table<MatchUiEvent> {
        __sdk::__query_builder::Table::new("my_match_ui_events")
    }
}
