// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::command_kind_type::CommandKind;
use super::match_command_type::MatchCommand;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_match_commands`.
///
/// Obtain a handle from the [`MyMatchCommandsTableAccess::my_match_commands`] method on [`super::RemoteTables`],
/// like `ctx.db.my_match_commands()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_match_commands().on_insert(...)`.
pub struct MyMatchCommandsTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchCommand>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_match_commands`.
pub struct MyMatchCommandsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyMatchCommandsTableAccessor {
    type Row = MatchCommand;
    type Handle<'db> = MyMatchCommandsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_match_commands()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_match_commands`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyMatchCommandsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyMatchCommandsTableHandle`], which mediates access to the table `my_match_commands`.
    fn my_match_commands(&self) -> MyMatchCommandsTableHandle<'_>;
}

impl MyMatchCommandsTableAccess for super::RemoteTables {
    fn my_match_commands(&self) -> MyMatchCommandsTableHandle<'_> {
        MyMatchCommandsTableHandle {
            imp: self.imp.get_table::<MatchCommand>("my_match_commands"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyMatchCommandsInsertCallbackId(__sdk::CallbackId);
pub struct MyMatchCommandsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyMatchCommandsTableHandle<'ctx> {
    type Row = MatchCommand;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchCommand> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyMatchCommandsTableHandle<'ctx> {
    type Row = MatchCommand;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchCommand> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyMatchCommandsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchCommandsInsertCallbackId {
        MyMatchCommandsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchCommandsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyMatchCommandsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchCommandsDeleteCallbackId {
        MyMatchCommandsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchCommandsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyMatchCommandsTableHandle<'ctx> {
    type InsertCallbackId = MyMatchCommandsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchCommandsInsertCallbackId {
        MyMatchCommandsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchCommandsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyMatchCommandsTableHandle<'ctx> {
    type DeleteCallbackId = MyMatchCommandsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchCommandsDeleteCallbackId {
        MyMatchCommandsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchCommandsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchCommand>("my_match_commands");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchCommand>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchCommand>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchCommand`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_match_commandsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchCommand`.
    fn my_match_commands(&self) -> __sdk::__query_builder::Table<MatchCommand>;
}

impl my_match_commandsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_match_commands(&self) -> __sdk::__query_builder::Table<MatchCommand> {
        __sdk::__query_builder::Table::new("my_match_commands")
    }
}
