// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::member_role_type::MemberRole;
use super::relay_member_type::RelayMember;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_match_members`.
///
/// Obtain a handle from the [`MyMatchMembersTableAccess::my_match_members`] method on [`super::RemoteTables`],
/// like `ctx.db.my_match_members()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_match_members().on_insert(...)`.
pub struct MyMatchMembersTableHandle<'ctx> {
    imp: __sdk::TableHandle<RelayMember>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_match_members`.
pub struct MyMatchMembersTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyMatchMembersTableAccessor {
    type Row = RelayMember;
    type Handle<'db> = MyMatchMembersTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_match_members()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_match_members`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyMatchMembersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyMatchMembersTableHandle`], which mediates access to the table `my_match_members`.
    fn my_match_members(&self) -> MyMatchMembersTableHandle<'_>;
}

impl MyMatchMembersTableAccess for super::RemoteTables {
    fn my_match_members(&self) -> MyMatchMembersTableHandle<'_> {
        MyMatchMembersTableHandle {
            imp: self.imp.get_table::<RelayMember>("my_match_members"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyMatchMembersInsertCallbackId(__sdk::CallbackId);
pub struct MyMatchMembersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyMatchMembersTableHandle<'ctx> {
    type Row = RelayMember;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RelayMember> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyMatchMembersTableHandle<'ctx> {
    type Row = RelayMember;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RelayMember> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyMatchMembersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchMembersInsertCallbackId {
        MyMatchMembersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchMembersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyMatchMembersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchMembersDeleteCallbackId {
        MyMatchMembersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchMembersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyMatchMembersTableHandle<'ctx> {
    type InsertCallbackId = MyMatchMembersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchMembersInsertCallbackId {
        MyMatchMembersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchMembersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyMatchMembersTableHandle<'ctx> {
    type DeleteCallbackId = MyMatchMembersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchMembersDeleteCallbackId {
        MyMatchMembersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchMembersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RelayMember>("my_match_members");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RelayMember>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RelayMember>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RelayMember`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_match_membersQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RelayMember`.
    fn my_match_members(&self) -> __sdk::__query_builder::Table<RelayMember>;
}

impl my_match_membersQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_match_members(&self) -> __sdk::__query_builder::Table<RelayMember> {
        __sdk::__query_builder::Table::new("my_match_members")
    }
}
