// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_snapshot_type::MatchSnapshot;
use super::snapshot_kind_type::SnapshotKind;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_match_snapshots`.
///
/// Obtain a handle from the [`MyMatchSnapshotsTableAccess::my_match_snapshots`] method on [`super::RemoteTables`],
/// like `ctx.db.my_match_snapshots()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_match_snapshots().on_insert(...)`.
pub struct MyMatchSnapshotsTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchSnapshot>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_match_snapshots`.
pub struct MyMatchSnapshotsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyMatchSnapshotsTableAccessor {
    type Row = MatchSnapshot;
    type Handle<'db> = MyMatchSnapshotsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_match_snapshots()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_match_snapshots`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyMatchSnapshotsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyMatchSnapshotsTableHandle`], which mediates access to the table `my_match_snapshots`.
    fn my_match_snapshots(&self) -> MyMatchSnapshotsTableHandle<'_>;
}

impl MyMatchSnapshotsTableAccess for super::RemoteTables {
    fn my_match_snapshots(&self) -> MyMatchSnapshotsTableHandle<'_> {
        MyMatchSnapshotsTableHandle {
            imp: self.imp.get_table::<MatchSnapshot>("my_match_snapshots"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyMatchSnapshotsInsertCallbackId(__sdk::CallbackId);
pub struct MyMatchSnapshotsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyMatchSnapshotsTableHandle<'ctx> {
    type Row = MatchSnapshot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchSnapshot> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyMatchSnapshotsTableHandle<'ctx> {
    type Row = MatchSnapshot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchSnapshot> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyMatchSnapshotsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchSnapshotsInsertCallbackId {
        MyMatchSnapshotsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchSnapshotsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyMatchSnapshotsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchSnapshotsDeleteCallbackId {
        MyMatchSnapshotsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchSnapshotsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyMatchSnapshotsTableHandle<'ctx> {
    type InsertCallbackId = MyMatchSnapshotsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchSnapshotsInsertCallbackId {
        MyMatchSnapshotsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchSnapshotsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyMatchSnapshotsTableHandle<'ctx> {
    type DeleteCallbackId = MyMatchSnapshotsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchSnapshotsDeleteCallbackId {
        MyMatchSnapshotsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchSnapshotsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchSnapshot>("my_match_snapshots");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchSnapshot>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchSnapshot>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchSnapshot`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_match_snapshotsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchSnapshot`.
    fn my_match_snapshots(&self) -> __sdk::__query_builder::Table<MatchSnapshot>;
}

impl my_match_snapshotsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_match_snapshots(&self) -> __sdk::__query_builder::Table<MatchSnapshot> {
        __sdk::__query_builder::Table::new("my_match_snapshots")
    }
}
