// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_checksum_type::MatchChecksum;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_match_checksums`.
///
/// Obtain a handle from the [`MyMatchChecksumsTableAccess::my_match_checksums`] method on [`super::RemoteTables`],
/// like `ctx.db.my_match_checksums()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_match_checksums().on_insert(...)`.
pub struct MyMatchChecksumsTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchChecksum>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_match_checksums`.
pub struct MyMatchChecksumsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyMatchChecksumsTableAccessor {
    type Row = MatchChecksum;
    type Handle<'db> = MyMatchChecksumsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_match_checksums()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_match_checksums`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyMatchChecksumsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyMatchChecksumsTableHandle`], which mediates access to the table `my_match_checksums`.
    fn my_match_checksums(&self) -> MyMatchChecksumsTableHandle<'_>;
}

impl MyMatchChecksumsTableAccess for super::RemoteTables {
    fn my_match_checksums(&self) -> MyMatchChecksumsTableHandle<'_> {
        MyMatchChecksumsTableHandle {
            imp: self.imp.get_table::<MatchChecksum>("my_match_checksums"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyMatchChecksumsInsertCallbackId(__sdk::CallbackId);
pub struct MyMatchChecksumsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyMatchChecksumsTableHandle<'ctx> {
    type Row = MatchChecksum;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchChecksum> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyMatchChecksumsTableHandle<'ctx> {
    type Row = MatchChecksum;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchChecksum> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyMatchChecksumsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchChecksumsInsertCallbackId {
        MyMatchChecksumsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchChecksumsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyMatchChecksumsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchChecksumsDeleteCallbackId {
        MyMatchChecksumsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchChecksumsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyMatchChecksumsTableHandle<'ctx> {
    type InsertCallbackId = MyMatchChecksumsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchChecksumsInsertCallbackId {
        MyMatchChecksumsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchChecksumsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyMatchChecksumsTableHandle<'ctx> {
    type DeleteCallbackId = MyMatchChecksumsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchChecksumsDeleteCallbackId {
        MyMatchChecksumsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchChecksumsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchChecksum>("my_match_checksums");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchChecksum>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchChecksum>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchChecksum`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_match_checksumsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchChecksum`.
    fn my_match_checksums(&self) -> __sdk::__query_builder::Table<MatchChecksum>;
}

impl my_match_checksumsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_match_checksums(&self) -> __sdk::__query_builder::Table<MatchChecksum> {
        __sdk::__query_builder::Table::new("my_match_checksums")
    }
}
