// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_snapshot_request_type::MatchSnapshotRequest;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_match_snapshot_requests`.
///
/// Obtain a handle from the [`MyMatchSnapshotRequestsTableAccess::my_match_snapshot_requests`] method on [`super::RemoteTables`],
/// like `ctx.db.my_match_snapshot_requests()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_match_snapshot_requests().on_insert(...)`.
pub struct MyMatchSnapshotRequestsTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchSnapshotRequest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_match_snapshot_requests`.
pub struct MyMatchSnapshotRequestsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyMatchSnapshotRequestsTableAccessor {
    type Row = MatchSnapshotRequest;
    type Handle<'db> = MyMatchSnapshotRequestsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_match_snapshot_requests()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_match_snapshot_requests`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyMatchSnapshotRequestsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyMatchSnapshotRequestsTableHandle`], which mediates access to the table `my_match_snapshot_requests`.
    fn my_match_snapshot_requests(&self) -> MyMatchSnapshotRequestsTableHandle<'_>;
}

impl MyMatchSnapshotRequestsTableAccess for super::RemoteTables {
    fn my_match_snapshot_requests(&self) -> MyMatchSnapshotRequestsTableHandle<'_> {
        MyMatchSnapshotRequestsTableHandle {
            imp: self
                .imp
                .get_table::<MatchSnapshotRequest>("my_match_snapshot_requests"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyMatchSnapshotRequestsInsertCallbackId(__sdk::CallbackId);
pub struct MyMatchSnapshotRequestsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyMatchSnapshotRequestsTableHandle<'ctx> {
    type Row = MatchSnapshotRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchSnapshotRequest> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyMatchSnapshotRequestsTableHandle<'ctx> {
    type Row = MatchSnapshotRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchSnapshotRequest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyMatchSnapshotRequestsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchSnapshotRequestsInsertCallbackId {
        MyMatchSnapshotRequestsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchSnapshotRequestsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyMatchSnapshotRequestsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchSnapshotRequestsDeleteCallbackId {
        MyMatchSnapshotRequestsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchSnapshotRequestsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyMatchSnapshotRequestsTableHandle<'ctx> {
    type InsertCallbackId = MyMatchSnapshotRequestsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchSnapshotRequestsInsertCallbackId {
        MyMatchSnapshotRequestsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchSnapshotRequestsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyMatchSnapshotRequestsTableHandle<'ctx> {
    type DeleteCallbackId = MyMatchSnapshotRequestsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchSnapshotRequestsDeleteCallbackId {
        MyMatchSnapshotRequestsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchSnapshotRequestsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<MatchSnapshotRequest>("my_match_snapshot_requests");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchSnapshotRequest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchSnapshotRequest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchSnapshotRequest`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_match_snapshot_requestsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchSnapshotRequest`.
    fn my_match_snapshot_requests(&self) -> __sdk::__query_builder::Table<MatchSnapshotRequest>;
}

impl my_match_snapshot_requestsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_match_snapshot_requests(&self) -> __sdk::__query_builder::Table<MatchSnapshotRequest> {
        __sdk::__query_builder::Table::new("my_match_snapshot_requests")
    }
}
