// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_snapshot_chunk_type::MatchSnapshotChunk;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_match_snapshot_chunks`.
///
/// Obtain a handle from the [`MyMatchSnapshotChunksTableAccess::my_match_snapshot_chunks`] method on [`super::RemoteTables`],
/// like `ctx.db.my_match_snapshot_chunks()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_match_snapshot_chunks().on_insert(...)`.
pub struct MyMatchSnapshotChunksTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchSnapshotChunk>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_match_snapshot_chunks`.
pub struct MyMatchSnapshotChunksTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyMatchSnapshotChunksTableAccessor {
    type Row = MatchSnapshotChunk;
    type Handle<'db> = MyMatchSnapshotChunksTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_match_snapshot_chunks()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_match_snapshot_chunks`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyMatchSnapshotChunksTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyMatchSnapshotChunksTableHandle`], which mediates access to the table `my_match_snapshot_chunks`.
    fn my_match_snapshot_chunks(&self) -> MyMatchSnapshotChunksTableHandle<'_>;
}

impl MyMatchSnapshotChunksTableAccess for super::RemoteTables {
    fn my_match_snapshot_chunks(&self) -> MyMatchSnapshotChunksTableHandle<'_> {
        MyMatchSnapshotChunksTableHandle {
            imp: self
                .imp
                .get_table::<MatchSnapshotChunk>("my_match_snapshot_chunks"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyMatchSnapshotChunksInsertCallbackId(__sdk::CallbackId);
pub struct MyMatchSnapshotChunksDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyMatchSnapshotChunksTableHandle<'ctx> {
    type Row = MatchSnapshotChunk;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchSnapshotChunk> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyMatchSnapshotChunksTableHandle<'ctx> {
    type Row = MatchSnapshotChunk;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchSnapshotChunk> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyMatchSnapshotChunksInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchSnapshotChunksInsertCallbackId {
        MyMatchSnapshotChunksInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchSnapshotChunksInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyMatchSnapshotChunksDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchSnapshotChunksDeleteCallbackId {
        MyMatchSnapshotChunksDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchSnapshotChunksDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyMatchSnapshotChunksTableHandle<'ctx> {
    type InsertCallbackId = MyMatchSnapshotChunksInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchSnapshotChunksInsertCallbackId {
        MyMatchSnapshotChunksInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchSnapshotChunksInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyMatchSnapshotChunksTableHandle<'ctx> {
    type DeleteCallbackId = MyMatchSnapshotChunksDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchSnapshotChunksDeleteCallbackId {
        MyMatchSnapshotChunksDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchSnapshotChunksDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchSnapshotChunk>("my_match_snapshot_chunks");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchSnapshotChunk>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchSnapshotChunk>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchSnapshotChunk`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_match_snapshot_chunksQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchSnapshotChunk`.
    fn my_match_snapshot_chunks(&self) -> __sdk::__query_builder::Table<MatchSnapshotChunk>;
}

impl my_match_snapshot_chunksQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_match_snapshot_chunks(&self) -> __sdk::__query_builder::Table<MatchSnapshotChunk> {
        __sdk::__query_builder::Table::new("my_match_snapshot_chunks")
    }
}
