// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::match_plan_state_type::MatchPlanState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_match_plans`.
///
/// Obtain a handle from the [`MyMatchPlansTableAccess::my_match_plans`] method on [`super::RemoteTables`],
/// like `ctx.db.my_match_plans()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_match_plans().on_insert(...)`.
pub struct MyMatchPlansTableHandle<'ctx> {
    imp: __sdk::TableHandle<MatchPlanState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_match_plans`.
pub struct MyMatchPlansTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyMatchPlansTableAccessor {
    type Row = MatchPlanState;
    type Handle<'db> = MyMatchPlansTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_match_plans()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_match_plans`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyMatchPlansTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyMatchPlansTableHandle`], which mediates access to the table `my_match_plans`.
    fn my_match_plans(&self) -> MyMatchPlansTableHandle<'_>;
}

impl MyMatchPlansTableAccess for super::RemoteTables {
    fn my_match_plans(&self) -> MyMatchPlansTableHandle<'_> {
        MyMatchPlansTableHandle {
            imp: self.imp.get_table::<MatchPlanState>("my_match_plans"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyMatchPlansInsertCallbackId(__sdk::CallbackId);
pub struct MyMatchPlansDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyMatchPlansTableHandle<'ctx> {
    type Row = MatchPlanState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchPlanState> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyMatchPlansTableHandle<'ctx> {
    type Row = MatchPlanState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MatchPlanState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyMatchPlansInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchPlansInsertCallbackId {
        MyMatchPlansInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchPlansInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyMatchPlansDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchPlansDeleteCallbackId {
        MyMatchPlansDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchPlansDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyMatchPlansTableHandle<'ctx> {
    type InsertCallbackId = MyMatchPlansInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchPlansInsertCallbackId {
        MyMatchPlansInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchPlansInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyMatchPlansTableHandle<'ctx> {
    type DeleteCallbackId = MyMatchPlansDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchPlansDeleteCallbackId {
        MyMatchPlansDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchPlansDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MatchPlanState>("my_match_plans");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MatchPlanState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MatchPlanState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MatchPlanState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_match_plansQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MatchPlanState`.
    fn my_match_plans(&self) -> __sdk::__query_builder::Table<MatchPlanState>;
}

impl my_match_plansQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_match_plans(&self) -> __sdk::__query_builder::Table<MatchPlanState> {
        __sdk::__query_builder::Table::new("my_match_plans")
    }
}
