// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::authority_mode_type::AuthorityMode;
use super::match_status_type::MatchStatus;
use super::relay_match_type::RelayMatch;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_match`.
///
/// Obtain a handle from the [`MyMatchTableAccess::my_match`] method on [`super::RemoteTables`],
/// like `ctx.db.my_match()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_match().on_insert(...)`.
pub struct MyMatchTableHandle<'ctx> {
    imp: __sdk::TableHandle<RelayMatch>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `my_match`.
pub struct MyMatchTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MyMatchTableAccessor {
    type Row = RelayMatch;
    type Handle<'db> = MyMatchTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.my_match()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_match`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyMatchTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyMatchTableHandle`], which mediates access to the table `my_match`.
    fn my_match(&self) -> MyMatchTableHandle<'_>;
}

impl MyMatchTableAccess for super::RemoteTables {
    fn my_match(&self) -> MyMatchTableHandle<'_> {
        MyMatchTableHandle {
            imp: self.imp.get_table::<RelayMatch>("my_match"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyMatchInsertCallbackId(__sdk::CallbackId);
pub struct MyMatchDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MyMatchTableHandle<'ctx> {
    type Row = RelayMatch;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RelayMatch> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MyMatchTableHandle<'ctx> {
    type Row = RelayMatch;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RelayMatch> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyMatchInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchInsertCallbackId {
        MyMatchInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyMatchDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchDeleteCallbackId {
        MyMatchDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MyMatchTableHandle<'ctx> {
    type InsertCallbackId = MyMatchInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchInsertCallbackId {
        MyMatchInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMatchInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MyMatchTableHandle<'ctx> {
    type DeleteCallbackId = MyMatchDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMatchDeleteCallbackId {
        MyMatchDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMatchDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RelayMatch>("my_match");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RelayMatch>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RelayMatch>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RelayMatch`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_matchQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RelayMatch`.
    fn my_match(&self) -> __sdk::__query_builder::Table<RelayMatch>;
}

impl my_matchQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_match(&self) -> __sdk::__query_builder::Table<RelayMatch> {
        __sdk::__query_builder::Table::new("my_match")
    }
}
