// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerStateReport {
    pub seq: u32,
    pub unit_id: i32,
    pub dead: bool,
    pub x: f32,
    pub y: f32,
    pub vx: f32,
    pub vy: f32,
    pub pointer_x: f32,
    pub pointer_y: f32,
    pub rotation: f32,
    pub base_rotation: f32,
    pub mining_x: i16,
    pub mining_y: i16,
    pub boosting: bool,
    pub shooting: bool,
    pub chatting: bool,
    pub building: bool,
    pub selected_block: Option<String>,
    pub selected_rotation: u8,
    pub view_x: f32,
    pub view_y: f32,
    pub view_width: f32,
    pub view_height: f32,
    pub health: f32,
    pub shield: f32,
    pub team: u8,
}

impl __sdk::InModule for PlayerStateReport {
    type Module = super::RemoteModule;
}
