// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PublishMatchStateArgs {
    pub match_id: u64,
    pub wave: i32,
    pub wavetime: f32,
    pub enemies: i32,
    pub paused: bool,
    pub game_over: bool,
    pub sim_tick: u64,
    pub last_command_id: u64,
}

impl From<PublishMatchStateArgs> for super::Reducer {
    fn from(args: PublishMatchStateArgs) -> Self {
        Self::PublishMatchState {
            match_id: args.match_id,
            wave: args.wave,
            wavetime: args.wavetime,
            enemies: args.enemies,
            paused: args.paused,
            game_over: args.game_over,
            sim_tick: args.sim_tick,
            last_command_id: args.last_command_id,
        }
    }
}

impl __sdk::InModule for PublishMatchStateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `publish_match_state`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait publish_match_state {
    /// Request that the remote module invoke the reducer `publish_match_state` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`publish_match_state:publish_match_state_then`] to run a callback after the reducer completes.
    fn publish_match_state(
        &self,
        match_id: u64,
        wave: i32,
        wavetime: f32,
        enemies: i32,
        paused: bool,
        game_over: bool,
        sim_tick: u64,
        last_command_id: u64,
    ) -> __sdk::Result<()> {
        self.publish_match_state_then(
            match_id,
            wave,
            wavetime,
            enemies,
            paused,
            game_over,
            sim_tick,
            last_command_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `publish_match_state` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn publish_match_state_then(
        &self,
        match_id: u64,
        wave: i32,
        wavetime: f32,
        enemies: i32,
        paused: bool,
        game_over: bool,
        sim_tick: u64,
        last_command_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl publish_match_state for super::RemoteReducers {
    fn publish_match_state_then(
        &self,
        match_id: u64,
        wave: i32,
        wavetime: f32,
        enemies: i32,
        paused: bool,
        game_over: bool,
        sim_tick: u64,
        last_command_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PublishMatchStateArgs {
                match_id,
                wave,
                wavetime,
                enemies,
                paused,
                game_over,
                sim_tick,
                last_command_id,
            },
            callback,
        )
    }
}
