// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ui_event_kind_type::UiEventKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PublishUiEventArgs {
    pub match_id: u64,
    pub kind: UiEventKind,
    pub target: Option<__sdk::Identity>,
    pub payload: Vec<u8>,
}

impl From<PublishUiEventArgs> for super::Reducer {
    fn from(args: PublishUiEventArgs) -> Self {
        Self::PublishUiEvent {
            match_id: args.match_id,
            kind: args.kind,
            target: args.target,
            payload: args.payload,
        }
    }
}

impl __sdk::InModule for PublishUiEventArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `publish_ui_event`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait publish_ui_event {
    /// Request that the remote module invoke the reducer `publish_ui_event` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`publish_ui_event:publish_ui_event_then`] to run a callback after the reducer completes.
    fn publish_ui_event(
        &self,
        match_id: u64,
        kind: UiEventKind,
        target: Option<__sdk::Identity>,
        payload: Vec<u8>,
    ) -> __sdk::Result<()> {
        self.publish_ui_event_then(match_id, kind, target, payload, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `publish_ui_event` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn publish_ui_event_then(
        &self,
        match_id: u64,
        kind: UiEventKind,
        target: Option<__sdk::Identity>,
        payload: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl publish_ui_event for super::RemoteReducers {
    fn publish_ui_event_then(
        &self,
        match_id: u64,
        kind: UiEventKind,
        target: Option<__sdk::Identity>,
        payload: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PublishUiEventArgs {
                match_id,
                kind,
                target,
                payload,
            },
            callback,
        )
    }
}
