// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::snapshot_kind_type::SnapshotKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PublishSnapshotArgs {
    pub match_id: u64,
    pub kind: SnapshotKind,
    pub format: u32,
    pub checksum_version: u32,
    pub command_id: u64,
    pub sim_tick: u64,
    pub checksum: u64,
    pub map_id: String,
    pub map_seed: u64,
    pub map_hash: u64,
    pub build_id: String,
    pub content_hash: u64,
    pub blob: Vec<u8>,
}

impl From<PublishSnapshotArgs> for super::Reducer {
    fn from(args: PublishSnapshotArgs) -> Self {
        Self::PublishSnapshot {
            match_id: args.match_id,
            kind: args.kind,
            format: args.format,
            checksum_version: args.checksum_version,
            command_id: args.command_id,
            sim_tick: args.sim_tick,
            checksum: args.checksum,
            map_id: args.map_id,
            map_seed: args.map_seed,
            map_hash: args.map_hash,
            build_id: args.build_id,
            content_hash: args.content_hash,
            blob: args.blob,
        }
    }
}

impl __sdk::InModule for PublishSnapshotArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `publish_snapshot`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait publish_snapshot {
    /// Request that the remote module invoke the reducer `publish_snapshot` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`publish_snapshot:publish_snapshot_then`] to run a callback after the reducer completes.
    fn publish_snapshot(
        &self,
        match_id: u64,
        kind: SnapshotKind,
        format: u32,
        checksum_version: u32,
        command_id: u64,
        sim_tick: u64,
        checksum: u64,
        map_id: String,
        map_seed: u64,
        map_hash: u64,
        build_id: String,
        content_hash: u64,
        blob: Vec<u8>,
    ) -> __sdk::Result<()> {
        self.publish_snapshot_then(
            match_id,
            kind,
            format,
            checksum_version,
            command_id,
            sim_tick,
            checksum,
            map_id,
            map_seed,
            map_hash,
            build_id,
            content_hash,
            blob,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `publish_snapshot` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn publish_snapshot_then(
        &self,
        match_id: u64,
        kind: SnapshotKind,
        format: u32,
        checksum_version: u32,
        command_id: u64,
        sim_tick: u64,
        checksum: u64,
        map_id: String,
        map_seed: u64,
        map_hash: u64,
        build_id: String,
        content_hash: u64,
        blob: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl publish_snapshot for super::RemoteReducers {
    fn publish_snapshot_then(
        &self,
        match_id: u64,
        kind: SnapshotKind,
        format: u32,
        checksum_version: u32,
        command_id: u64,
        sim_tick: u64,
        checksum: u64,
        map_id: String,
        map_seed: u64,
        map_hash: u64,
        build_id: String,
        content_hash: u64,
        blob: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PublishSnapshotArgs {
                match_id,
                kind,
                format,
                checksum_version,
                command_id,
                sim_tick,
                checksum,
                map_id,
                map_seed,
                map_hash,
                build_id,
                content_hash,
                blob,
            },
            callback,
        )
    }
}
