// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RelayMember {
    pub member_id: u64,
    pub match_id: u64,
    pub identity: __sdk::Identity,
    pub joined_at: __sdk::Timestamp,
}

impl __sdk::InModule for RelayMember {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RelayMember`.
///
/// Provides typed access to columns for query building.
pub struct RelayMemberCols {
    pub member_id: __sdk::__query_builder::Col<RelayMember, u64>,
    pub match_id: __sdk::__query_builder::Col<RelayMember, u64>,
    pub identity: __sdk::__query_builder::Col<RelayMember, __sdk::Identity>,
    pub joined_at: __sdk::__query_builder::Col<RelayMember, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for RelayMember {
    type Cols = RelayMemberCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RelayMemberCols {
            member_id: __sdk::__query_builder::Col::new(table_name, "member_id"),
            match_id: __sdk::__query_builder::Col::new(table_name, "match_id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            joined_at: __sdk::__query_builder::Col::new(table_name, "joined_at"),
        }
    }
}

/// Indexed column accessor struct for the table `RelayMember`.
///
/// Provides typed access to indexed columns for query building.
pub struct RelayMemberIxCols {
    pub match_id: __sdk::__query_builder::IxCol<RelayMember, u64>,
    pub member_id: __sdk::__query_builder::IxCol<RelayMember, u64>,
}

impl __sdk::__query_builder::HasIxCols for RelayMember {
    type IxCols = RelayMemberIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RelayMemberIxCols {
            match_id: __sdk::__query_builder::IxCol::new(table_name, "match_id"),
            member_id: __sdk::__query_builder::IxCol::new(table_name, "member_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RelayMember {}
