// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::relay_config_type::RelayConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `relay_config`.
///
/// Obtain a handle from the [`RelayConfigTableAccess::relay_config`] method on [`super::RemoteTables`],
/// like `ctx.db.relay_config()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.relay_config().on_insert(...)`.
pub struct RelayConfigTableHandle<'ctx> {
    imp: __sdk::TableHandle<RelayConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `relay_config`.
pub struct RelayConfigTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for RelayConfigTableAccessor {
    type Row = RelayConfig;
    type Handle<'db> = RelayConfigTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.relay_config()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `relay_config`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RelayConfigTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RelayConfigTableHandle`], which mediates access to the table `relay_config`.
    fn relay_config(&self) -> RelayConfigTableHandle<'_>;
}

impl RelayConfigTableAccess for super::RemoteTables {
    fn relay_config(&self) -> RelayConfigTableHandle<'_> {
        RelayConfigTableHandle {
            imp: self.imp.get_table::<RelayConfig>("relay_config"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RelayConfigInsertCallbackId(__sdk::CallbackId);
pub struct RelayConfigDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for RelayConfigTableHandle<'ctx> {
    type Row = RelayConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RelayConfig> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for RelayConfigTableHandle<'ctx> {
    type Row = RelayConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RelayConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RelayConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RelayConfigInsertCallbackId {
        RelayConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RelayConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RelayConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RelayConfigDeleteCallbackId {
        RelayConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RelayConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for RelayConfigTableHandle<'ctx> {
    type InsertCallbackId = RelayConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RelayConfigInsertCallbackId {
        RelayConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RelayConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for RelayConfigTableHandle<'ctx> {
    type DeleteCallbackId = RelayConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RelayConfigDeleteCallbackId {
        RelayConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RelayConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RelayConfigUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RelayConfigTableHandle<'ctx> {
    type UpdateCallbackId = RelayConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RelayConfigUpdateCallbackId {
        RelayConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RelayConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for RelayConfigTableHandle<'ctx> {
    type UpdateCallbackId = RelayConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RelayConfigUpdateCallbackId {
        RelayConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RelayConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `relay_config`,
/// which allows point queries on the field of the same name
/// via the [`RelayConfigIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.relay_config().id().find(...)`.
pub struct RelayConfigIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RelayConfig, u8>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RelayConfigTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `relay_config`.
    pub fn id(&self) -> RelayConfigIdUnique<'ctx> {
        RelayConfigIdUnique {
            imp: self.imp.get_unique_constraint::<u8>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RelayConfigIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u8) -> Option<RelayConfig> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RelayConfig>("relay_config");
    _table.add_unique_constraint::<u8>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RelayConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RelayConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RelayConfig`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait relay_configQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RelayConfig`.
    fn relay_config(&self) -> __sdk::__query_builder::Table<RelayConfig>;
}

impl relay_configQueryTableAccess for __sdk::QueryTableAccessor {
    fn relay_config(&self) -> __sdk::__query_builder::Table<RelayConfig> {
        __sdk::__query_builder::Table::new("relay_config")
    }
}
