// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RelayConfig {
    pub id: u8,
    pub commands_per_second: u32,
    pub command_rate_window_ms: u32,
    pub max_commit_commands_per_transaction: u32,
    pub default_map_width_tiles: i32,
    pub default_map_height_tiles: i32,
}

impl __sdk::InModule for RelayConfig {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RelayConfig`.
///
/// Provides typed access to columns for query building.
pub struct RelayConfigCols {
    pub id: __sdk::__query_builder::Col<RelayConfig, u8>,
    pub commands_per_second: __sdk::__query_builder::Col<RelayConfig, u32>,
    pub command_rate_window_ms: __sdk::__query_builder::Col<RelayConfig, u32>,
    pub max_commit_commands_per_transaction: __sdk::__query_builder::Col<RelayConfig, u32>,
    pub default_map_width_tiles: __sdk::__query_builder::Col<RelayConfig, i32>,
    pub default_map_height_tiles: __sdk::__query_builder::Col<RelayConfig, i32>,
}

impl __sdk::__query_builder::HasCols for RelayConfig {
    type Cols = RelayConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RelayConfigCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            commands_per_second: __sdk::__query_builder::Col::new(
                table_name,
                "commands_per_second",
            ),
            command_rate_window_ms: __sdk::__query_builder::Col::new(
                table_name,
                "command_rate_window_ms",
            ),
            max_commit_commands_per_transaction: __sdk::__query_builder::Col::new(
                table_name,
                "max_commit_commands_per_transaction",
            ),
            default_map_width_tiles: __sdk::__query_builder::Col::new(
                table_name,
                "default_map_width_tiles",
            ),
            default_map_height_tiles: __sdk::__query_builder::Col::new(
                table_name,
                "default_map_height_tiles",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `RelayConfig`.
///
/// Provides typed access to indexed columns for query building.
pub struct RelayConfigIxCols {
    pub id: __sdk::__query_builder::IxCol<RelayConfig, u8>,
}

impl __sdk::__query_builder::HasIxCols for RelayConfig {
    type IxCols = RelayConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RelayConfigIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RelayConfig {}
