// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_state_report_type::PlayerStateReport;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReportPlayerStateArgs {
    pub match_id: u64,
    pub report: PlayerStateReport,
}

impl From<ReportPlayerStateArgs> for super::Reducer {
    fn from(args: ReportPlayerStateArgs) -> Self {
        Self::ReportPlayerState {
            match_id: args.match_id,
            report: args.report,
        }
    }
}

impl __sdk::InModule for ReportPlayerStateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `report_player_state`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait report_player_state {
    /// Request that the remote module invoke the reducer `report_player_state` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`report_player_state:report_player_state_then`] to run a callback after the reducer completes.
    fn report_player_state(&self, match_id: u64, report: PlayerStateReport) -> __sdk::Result<()> {
        self.report_player_state_then(match_id, report, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `report_player_state` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn report_player_state_then(
        &self,
        match_id: u64,
        report: PlayerStateReport,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl report_player_state for super::RemoteReducers {
    fn report_player_state_then(
        &self,
        match_id: u64,
        report: PlayerStateReport,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ReportPlayerStateArgs { match_id, report }, callback)
    }
}
