// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReportPlanSnapshotArgs {
    pub match_id: u64,
    pub group_id: u32,
    pub chunk_index: u16,
    pub chunk_count: u16,
    pub plans_blob: Vec<u8>,
}

impl From<ReportPlanSnapshotArgs> for super::Reducer {
    fn from(args: ReportPlanSnapshotArgs) -> Self {
        Self::ReportPlanSnapshot {
            match_id: args.match_id,
            group_id: args.group_id,
            chunk_index: args.chunk_index,
            chunk_count: args.chunk_count,
            plans_blob: args.plans_blob,
        }
    }
}

impl __sdk::InModule for ReportPlanSnapshotArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `report_plan_snapshot`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait report_plan_snapshot {
    /// Request that the remote module invoke the reducer `report_plan_snapshot` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`report_plan_snapshot:report_plan_snapshot_then`] to run a callback after the reducer completes.
    fn report_plan_snapshot(
        &self,
        match_id: u64,
        group_id: u32,
        chunk_index: u16,
        chunk_count: u16,
        plans_blob: Vec<u8>,
    ) -> __sdk::Result<()> {
        self.report_plan_snapshot_then(
            match_id,
            group_id,
            chunk_index,
            chunk_count,
            plans_blob,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `report_plan_snapshot` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn report_plan_snapshot_then(
        &self,
        match_id: u64,
        group_id: u32,
        chunk_index: u16,
        chunk_count: u16,
        plans_blob: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl report_plan_snapshot for super::RemoteReducers {
    fn report_plan_snapshot_then(
        &self,
        match_id: u64,
        group_id: u32,
        chunk_index: u16,
        chunk_count: u16,
        plans_blob: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ReportPlanSnapshotArgs {
                match_id,
                group_id,
                chunk_index,
                chunk_count,
                plans_blob,
            },
            callback,
        )
    }
}
