// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestSnapshotArgs {
    pub match_id: u64,
}

impl From<RequestSnapshotArgs> for super::Reducer {
    fn from(args: RequestSnapshotArgs) -> Self {
        Self::RequestSnapshot {
            match_id: args.match_id,
        }
    }
}

impl __sdk::InModule for RequestSnapshotArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_snapshot`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_snapshot {
    /// Request that the remote module invoke the reducer `request_snapshot` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_snapshot:request_snapshot_then`] to run a callback after the reducer completes.
    fn request_snapshot(&self, match_id: u64) -> __sdk::Result<()> {
        self.request_snapshot_then(match_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `request_snapshot` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_snapshot_then(
        &self,
        match_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl request_snapshot for super::RemoteReducers {
    fn request_snapshot_then(
        &self,
        match_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RequestSnapshotArgs { match_id }, callback)
    }
}
