// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SaveSectorInfoArgs {
    pub campaign_id: u64,
    pub planet: String,
    pub sector_id: u32,
    pub info_json: String,
    pub wave: i32,
    pub win_wave: i32,
    pub waves: bool,
    pub attack: bool,
    pub minutes_captured: f32,
    pub playtime: u64,
    pub spawn_position: i32,
    pub last_preset_name: String,
    pub was_captured: bool,
}

impl From<SaveSectorInfoArgs> for super::Reducer {
    fn from(args: SaveSectorInfoArgs) -> Self {
        Self::SaveSectorInfo {
            campaign_id: args.campaign_id,
            planet: args.planet,
            sector_id: args.sector_id,
            info_json: args.info_json,
            wave: args.wave,
            win_wave: args.win_wave,
            waves: args.waves,
            attack: args.attack,
            minutes_captured: args.minutes_captured,
            playtime: args.playtime,
            spawn_position: args.spawn_position,
            last_preset_name: args.last_preset_name,
            was_captured: args.was_captured,
        }
    }
}

impl __sdk::InModule for SaveSectorInfoArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `save_sector_info`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait save_sector_info {
    /// Request that the remote module invoke the reducer `save_sector_info` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`save_sector_info:save_sector_info_then`] to run a callback after the reducer completes.
    fn save_sector_info(
        &self,
        campaign_id: u64,
        planet: String,
        sector_id: u32,
        info_json: String,
        wave: i32,
        win_wave: i32,
        waves: bool,
        attack: bool,
        minutes_captured: f32,
        playtime: u64,
        spawn_position: i32,
        last_preset_name: String,
        was_captured: bool,
    ) -> __sdk::Result<()> {
        self.save_sector_info_then(
            campaign_id,
            planet,
            sector_id,
            info_json,
            wave,
            win_wave,
            waves,
            attack,
            minutes_captured,
            playtime,
            spawn_position,
            last_preset_name,
            was_captured,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `save_sector_info` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn save_sector_info_then(
        &self,
        campaign_id: u64,
        planet: String,
        sector_id: u32,
        info_json: String,
        wave: i32,
        win_wave: i32,
        waves: bool,
        attack: bool,
        minutes_captured: f32,
        playtime: u64,
        spawn_position: i32,
        last_preset_name: String,
        was_captured: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl save_sector_info for super::RemoteReducers {
    fn save_sector_info_then(
        &self,
        campaign_id: u64,
        planet: String,
        sector_id: u32,
        info_json: String,
        wave: i32,
        win_wave: i32,
        waves: bool,
        attack: bool,
        minutes_captured: f32,
        playtime: u64,
        spawn_position: i32,
        last_preset_name: String,
        was_captured: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SaveSectorInfoArgs {
                campaign_id,
                planet,
                sector_id,
                info_json,
                wave,
                win_wave,
                waves,
                attack,
                minutes_captured,
                playtime,
                spawn_position,
                last_preset_name,
                was_captured,
            },
            callback,
        )
    }
}
