// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Schematic {
    pub schematic_id: u64,
    pub owner: __sdk::Identity,
    pub name: String,
    pub base_64: String,
    pub tags_json: String,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for Schematic {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Schematic`.
///
/// Provides typed access to columns for query building.
pub struct SchematicCols {
    pub schematic_id: __sdk::__query_builder::Col<Schematic, u64>,
    pub owner: __sdk::__query_builder::Col<Schematic, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<Schematic, String>,
    pub base_64: __sdk::__query_builder::Col<Schematic, String>,
    pub tags_json: __sdk::__query_builder::Col<Schematic, String>,
    pub created_at: __sdk::__query_builder::Col<Schematic, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<Schematic, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Schematic {
    type Cols = SchematicCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SchematicCols {
            schematic_id: __sdk::__query_builder::Col::new(table_name, "schematic_id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            base_64: __sdk::__query_builder::Col::new(table_name, "base_64"),
            tags_json: __sdk::__query_builder::Col::new(table_name, "tags_json"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Schematic`.
///
/// Provides typed access to indexed columns for query building.
pub struct SchematicIxCols {
    pub schematic_id: __sdk::__query_builder::IxCol<Schematic, u64>,
}

impl __sdk::__query_builder::HasIxCols for Schematic {
    type IxCols = SchematicIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SchematicIxCols {
            schematic_id: __sdk::__query_builder::IxCol::new(table_name, "schematic_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Schematic {}
