// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SectorInfo {
    pub sector_row_id: u64,
    pub campaign_id: u64,
    pub planet: String,
    pub sector_id: u32,
    pub info_json: String,
    pub wave: i32,
    pub win_wave: i32,
    pub waves: bool,
    pub attack: bool,
    pub minutes_captured: f32,
    pub playtime: u64,
    pub spawn_position: i32,
    pub last_preset_name: String,
    pub was_captured: bool,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for SectorInfo {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SectorInfo`.
///
/// Provides typed access to columns for query building.
pub struct SectorInfoCols {
    pub sector_row_id: __sdk::__query_builder::Col<SectorInfo, u64>,
    pub campaign_id: __sdk::__query_builder::Col<SectorInfo, u64>,
    pub planet: __sdk::__query_builder::Col<SectorInfo, String>,
    pub sector_id: __sdk::__query_builder::Col<SectorInfo, u32>,
    pub info_json: __sdk::__query_builder::Col<SectorInfo, String>,
    pub wave: __sdk::__query_builder::Col<SectorInfo, i32>,
    pub win_wave: __sdk::__query_builder::Col<SectorInfo, i32>,
    pub waves: __sdk::__query_builder::Col<SectorInfo, bool>,
    pub attack: __sdk::__query_builder::Col<SectorInfo, bool>,
    pub minutes_captured: __sdk::__query_builder::Col<SectorInfo, f32>,
    pub playtime: __sdk::__query_builder::Col<SectorInfo, u64>,
    pub spawn_position: __sdk::__query_builder::Col<SectorInfo, i32>,
    pub last_preset_name: __sdk::__query_builder::Col<SectorInfo, String>,
    pub was_captured: __sdk::__query_builder::Col<SectorInfo, bool>,
    pub updated_at: __sdk::__query_builder::Col<SectorInfo, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SectorInfo {
    type Cols = SectorInfoCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SectorInfoCols {
            sector_row_id: __sdk::__query_builder::Col::new(table_name, "sector_row_id"),
            campaign_id: __sdk::__query_builder::Col::new(table_name, "campaign_id"),
            planet: __sdk::__query_builder::Col::new(table_name, "planet"),
            sector_id: __sdk::__query_builder::Col::new(table_name, "sector_id"),
            info_json: __sdk::__query_builder::Col::new(table_name, "info_json"),
            wave: __sdk::__query_builder::Col::new(table_name, "wave"),
            win_wave: __sdk::__query_builder::Col::new(table_name, "win_wave"),
            waves: __sdk::__query_builder::Col::new(table_name, "waves"),
            attack: __sdk::__query_builder::Col::new(table_name, "attack"),
            minutes_captured: __sdk::__query_builder::Col::new(table_name, "minutes_captured"),
            playtime: __sdk::__query_builder::Col::new(table_name, "playtime"),
            spawn_position: __sdk::__query_builder::Col::new(table_name, "spawn_position"),
            last_preset_name: __sdk::__query_builder::Col::new(table_name, "last_preset_name"),
            was_captured: __sdk::__query_builder::Col::new(table_name, "was_captured"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SectorInfo`.
///
/// Provides typed access to indexed columns for query building.
pub struct SectorInfoIxCols {
    pub sector_row_id: __sdk::__query_builder::IxCol<SectorInfo, u64>,
}

impl __sdk::__query_builder::HasIxCols for SectorInfo {
    type IxCols = SectorInfoIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SectorInfoIxCols {
            sector_row_id: __sdk::__query_builder::IxCol::new(table_name, "sector_row_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SectorInfo {}
