// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sector_info_type::SectorInfo;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sector_info`.
///
/// Obtain a handle from the [`SectorInfoTableAccess::sector_info`] method on [`super::RemoteTables`],
/// like `ctx.db.sector_info()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sector_info().on_insert(...)`.
pub struct SectorInfoTableHandle<'ctx> {
    imp: __sdk::TableHandle<SectorInfo>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `sector_info`.
pub struct SectorInfoTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SectorInfoTableAccessor {
    type Row = SectorInfo;
    type Handle<'db> = SectorInfoTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.sector_info()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sector_info`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SectorInfoTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SectorInfoTableHandle`], which mediates access to the table `sector_info`.
    fn sector_info(&self) -> SectorInfoTableHandle<'_>;
}

impl SectorInfoTableAccess for super::RemoteTables {
    fn sector_info(&self) -> SectorInfoTableHandle<'_> {
        SectorInfoTableHandle {
            imp: self.imp.get_table::<SectorInfo>("sector_info"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SectorInfoInsertCallbackId(__sdk::CallbackId);
pub struct SectorInfoDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SectorInfoTableHandle<'ctx> {
    type Row = SectorInfo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SectorInfo> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SectorInfoTableHandle<'ctx> {
    type Row = SectorInfo;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SectorInfo> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SectorInfoInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SectorInfoInsertCallbackId {
        SectorInfoInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SectorInfoInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SectorInfoDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SectorInfoDeleteCallbackId {
        SectorInfoDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SectorInfoDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SectorInfoTableHandle<'ctx> {
    type InsertCallbackId = SectorInfoInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SectorInfoInsertCallbackId {
        SectorInfoInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SectorInfoInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SectorInfoTableHandle<'ctx> {
    type DeleteCallbackId = SectorInfoDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SectorInfoDeleteCallbackId {
        SectorInfoDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SectorInfoDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SectorInfoUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SectorInfoTableHandle<'ctx> {
    type UpdateCallbackId = SectorInfoUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SectorInfoUpdateCallbackId {
        SectorInfoUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SectorInfoUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SectorInfoTableHandle<'ctx> {
    type UpdateCallbackId = SectorInfoUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SectorInfoUpdateCallbackId {
        SectorInfoUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SectorInfoUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `sector_row_id` unique index on the table `sector_info`,
/// which allows point queries on the field of the same name
/// via the [`SectorInfoSectorRowIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sector_info().sector_row_id().find(...)`.
pub struct SectorInfoSectorRowIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SectorInfo, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SectorInfoTableHandle<'ctx> {
    /// Get a handle on the `sector_row_id` unique index on the table `sector_info`.
    pub fn sector_row_id(&self) -> SectorInfoSectorRowIdUnique<'ctx> {
        SectorInfoSectorRowIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("sector_row_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SectorInfoSectorRowIdUnique<'ctx> {
    /// Find the subscribed row whose `sector_row_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SectorInfo> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SectorInfo>("sector_info");
    _table.add_unique_constraint::<u64>("sector_row_id", |row| &row.sector_row_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SectorInfo>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SectorInfo>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SectorInfo`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sector_infoQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SectorInfo`.
    fn sector_info(&self) -> __sdk::__query_builder::Table<SectorInfo>;
}

impl sector_infoQueryTableAccess for __sdk::QueryTableAccessor {
    fn sector_info(&self) -> __sdk::__query_builder::Table<SectorInfo> {
        __sdk::__query_builder::Table::new("sector_info")
    }
}
