// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SenderCommandState {
    pub identity: __sdk::Identity,
    pub last_accepted_seq: u64,
    pub last_accepted_command_id: u64,
    pub reject_count: u32,
    pub last_gap_at: Option<__sdk::Timestamp>,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for SenderCommandState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SenderCommandState`.
///
/// Provides typed access to columns for query building.
pub struct SenderCommandStateCols {
    pub identity: __sdk::__query_builder::Col<SenderCommandState, __sdk::Identity>,
    pub last_accepted_seq: __sdk::__query_builder::Col<SenderCommandState, u64>,
    pub last_accepted_command_id: __sdk::__query_builder::Col<SenderCommandState, u64>,
    pub reject_count: __sdk::__query_builder::Col<SenderCommandState, u32>,
    pub last_gap_at: __sdk::__query_builder::Col<SenderCommandState, Option<__sdk::Timestamp>>,
    pub updated_at: __sdk::__query_builder::Col<SenderCommandState, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SenderCommandState {
    type Cols = SenderCommandStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SenderCommandStateCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            last_accepted_seq: __sdk::__query_builder::Col::new(table_name, "last_accepted_seq"),
            last_accepted_command_id: __sdk::__query_builder::Col::new(
                table_name,
                "last_accepted_command_id",
            ),
            reject_count: __sdk::__query_builder::Col::new(table_name, "reject_count"),
            last_gap_at: __sdk::__query_builder::Col::new(table_name, "last_gap_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SenderCommandState`.
///
/// Provides typed access to indexed columns for query building.
pub struct SenderCommandStateIxCols {
    pub identity: __sdk::__query_builder::IxCol<SenderCommandState, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for SenderCommandState {
    type IxCols = SenderCommandStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SenderCommandStateIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SenderCommandState {}
