// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::command_kind_type::CommandKind;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SendMatchCommandArgs {
    pub match_id: u64,
    pub client_tick: u64,
    pub kind: CommandKind,
}

impl From<SendMatchCommandArgs> for super::Reducer {
    fn from(args: SendMatchCommandArgs) -> Self {
        Self::SendMatchCommand {
            match_id: args.match_id,
            client_tick: args.client_tick,
            kind: args.kind,
        }
    }
}

impl __sdk::InModule for SendMatchCommandArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `send_match_command`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait send_match_command {
    /// Request that the remote module invoke the reducer `send_match_command` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`send_match_command:send_match_command_then`] to run a callback after the reducer completes.
    fn send_match_command(
        &self,
        match_id: u64,
        client_tick: u64,
        kind: CommandKind,
    ) -> __sdk::Result<()> {
        self.send_match_command_then(match_id, client_tick, kind, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `send_match_command` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn send_match_command_then(
        &self,
        match_id: u64,
        client_tick: u64,
        kind: CommandKind,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl send_match_command for super::RemoteReducers {
    fn send_match_command_then(
        &self,
        match_id: u64,
        client_tick: u64,
        kind: CommandKind,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SendMatchCommandArgs {
                match_id,
                client_tick,
                kind,
            },
            callback,
        )
    }
}
