// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::server_config_type::ServerConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `server_config`.
///
/// Obtain a handle from the [`ServerConfigTableAccess::server_config`] method on [`super::RemoteTables`],
/// like `ctx.db.server_config()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.server_config().on_insert(...)`.
pub struct ServerConfigTableHandle<'ctx> {
    imp: __sdk::TableHandle<ServerConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `server_config`.
pub struct ServerConfigTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ServerConfigTableAccessor {
    type Row = ServerConfig;
    type Handle<'db> = ServerConfigTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.server_config()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `server_config`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ServerConfigTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ServerConfigTableHandle`], which mediates access to the table `server_config`.
    fn server_config(&self) -> ServerConfigTableHandle<'_>;
}

impl ServerConfigTableAccess for super::RemoteTables {
    fn server_config(&self) -> ServerConfigTableHandle<'_> {
        ServerConfigTableHandle {
            imp: self.imp.get_table::<ServerConfig>("server_config"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ServerConfigInsertCallbackId(__sdk::CallbackId);
pub struct ServerConfigDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ServerConfigTableHandle<'ctx> {
    type Row = ServerConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ServerConfig> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ServerConfigTableHandle<'ctx> {
    type Row = ServerConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ServerConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ServerConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerConfigInsertCallbackId {
        ServerConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ServerConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ServerConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerConfigDeleteCallbackId {
        ServerConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ServerConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ServerConfigTableHandle<'ctx> {
    type InsertCallbackId = ServerConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerConfigInsertCallbackId {
        ServerConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ServerConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ServerConfigTableHandle<'ctx> {
    type DeleteCallbackId = ServerConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ServerConfigDeleteCallbackId {
        ServerConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ServerConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ServerConfigUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ServerConfigTableHandle<'ctx> {
    type UpdateCallbackId = ServerConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ServerConfigUpdateCallbackId {
        ServerConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ServerConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for ServerConfigTableHandle<'ctx> {
    type UpdateCallbackId = ServerConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ServerConfigUpdateCallbackId {
        ServerConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ServerConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `server_config`,
/// which allows point queries on the field of the same name
/// via the [`ServerConfigIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.server_config().id().find(...)`.
pub struct ServerConfigIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ServerConfig, u8>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ServerConfigTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `server_config`.
    pub fn id(&self) -> ServerConfigIdUnique<'ctx> {
        ServerConfigIdUnique {
            imp: self.imp.get_unique_constraint::<u8>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ServerConfigIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u8) -> Option<ServerConfig> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ServerConfig>("server_config");
    _table.add_unique_constraint::<u8>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ServerConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ServerConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ServerConfig`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait server_configQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ServerConfig`.
    fn server_config(&self) -> __sdk::__query_builder::Table<ServerConfig>;
}

impl server_configQueryTableAccess for __sdk::QueryTableAccessor {
    fn server_config(&self) -> __sdk::__query_builder::Table<ServerConfig> {
        __sdk::__query_builder::Table::new("server_config")
    }
}
