// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetUnlockArgs {
    pub campaign_id: u64,
    pub content_name: String,
    pub unlocked: bool,
    pub requirements_json: String,
}

impl From<SetUnlockArgs> for super::Reducer {
    fn from(args: SetUnlockArgs) -> Self {
        Self::SetUnlock {
            campaign_id: args.campaign_id,
            content_name: args.content_name,
            unlocked: args.unlocked,
            requirements_json: args.requirements_json,
        }
    }
}

impl __sdk::InModule for SetUnlockArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_unlock`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_unlock {
    /// Request that the remote module invoke the reducer `set_unlock` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_unlock:set_unlock_then`] to run a callback after the reducer completes.
    fn set_unlock(
        &self,
        campaign_id: u64,
        content_name: String,
        unlocked: bool,
        requirements_json: String,
    ) -> __sdk::Result<()> {
        self.set_unlock_then(
            campaign_id,
            content_name,
            unlocked,
            requirements_json,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `set_unlock` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_unlock_then(
        &self,
        campaign_id: u64,
        content_name: String,
        unlocked: bool,
        requirements_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_unlock for super::RemoteReducers {
    fn set_unlock_then(
        &self,
        campaign_id: u64,
        content_name: String,
        unlocked: bool,
        requirements_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetUnlockArgs {
                campaign_id,
                content_name,
                unlocked,
                requirements_json,
            },
            callback,
        )
    }
}
