// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StartMatchArgs {
    pub match_id: u64,
    pub force: bool,
}

impl From<StartMatchArgs> for super::Reducer {
    fn from(args: StartMatchArgs) -> Self {
        Self::StartMatch {
            match_id: args.match_id,
            force: args.force,
        }
    }
}

impl __sdk::InModule for StartMatchArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `start_match`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait start_match {
    /// Request that the remote module invoke the reducer `start_match` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`start_match:start_match_then`] to run a callback after the reducer completes.
    fn start_match(&self, match_id: u64, force: bool) -> __sdk::Result<()> {
        self.start_match_then(match_id, force, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `start_match` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn start_match_then(
        &self,
        match_id: u64,
        force: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl start_match for super::RemoteReducers {
    fn start_match_then(
        &self,
        match_id: u64,
        force: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(StartMatchArgs { match_id, force }, callback)
    }
}
