// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Unlock {
    pub unlock_id: u64,
    pub campaign_id: u64,
    pub content_name: String,
    pub unlocked: bool,
    pub requirements_json: String,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for Unlock {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Unlock`.
///
/// Provides typed access to columns for query building.
pub struct UnlockCols {
    pub unlock_id: __sdk::__query_builder::Col<Unlock, u64>,
    pub campaign_id: __sdk::__query_builder::Col<Unlock, u64>,
    pub content_name: __sdk::__query_builder::Col<Unlock, String>,
    pub unlocked: __sdk::__query_builder::Col<Unlock, bool>,
    pub requirements_json: __sdk::__query_builder::Col<Unlock, String>,
    pub updated_at: __sdk::__query_builder::Col<Unlock, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Unlock {
    type Cols = UnlockCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UnlockCols {
            unlock_id: __sdk::__query_builder::Col::new(table_name, "unlock_id"),
            campaign_id: __sdk::__query_builder::Col::new(table_name, "campaign_id"),
            content_name: __sdk::__query_builder::Col::new(table_name, "content_name"),
            unlocked: __sdk::__query_builder::Col::new(table_name, "unlocked"),
            requirements_json: __sdk::__query_builder::Col::new(table_name, "requirements_json"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Unlock`.
///
/// Provides typed access to indexed columns for query building.
pub struct UnlockIxCols {
    pub unlock_id: __sdk::__query_builder::IxCol<Unlock, u64>,
}

impl __sdk::__query_builder::HasIxCols for Unlock {
    type IxCols = UnlockIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UnlockIxCols {
            unlock_id: __sdk::__query_builder::IxCol::new(table_name, "unlock_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Unlock {}
