// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateClientSettingsArgs {
    pub ui_scale: f32,
    pub language: String,
    pub music_volume: f32,
    pub sfx_volume: f32,
    pub keybinds_json: String,
}

impl From<UpdateClientSettingsArgs> for super::Reducer {
    fn from(args: UpdateClientSettingsArgs) -> Self {
        Self::UpdateClientSettings {
            ui_scale: args.ui_scale,
            language: args.language,
            music_volume: args.music_volume,
            sfx_volume: args.sfx_volume,
            keybinds_json: args.keybinds_json,
        }
    }
}

impl __sdk::InModule for UpdateClientSettingsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_client_settings`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_client_settings {
    /// Request that the remote module invoke the reducer `update_client_settings` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_client_settings:update_client_settings_then`] to run a callback after the reducer completes.
    fn update_client_settings(
        &self,
        ui_scale: f32,
        language: String,
        music_volume: f32,
        sfx_volume: f32,
        keybinds_json: String,
    ) -> __sdk::Result<()> {
        self.update_client_settings_then(
            ui_scale,
            language,
            music_volume,
            sfx_volume,
            keybinds_json,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `update_client_settings` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_client_settings_then(
        &self,
        ui_scale: f32,
        language: String,
        music_volume: f32,
        sfx_volume: f32,
        keybinds_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_client_settings for super::RemoteReducers {
    fn update_client_settings_then(
        &self,
        ui_scale: f32,
        language: String,
        music_volume: f32,
        sfx_volume: f32,
        keybinds_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateClientSettingsArgs {
                ui_scale,
                language,
                music_volume,
                sfx_volume,
                keybinds_json,
            },
            callback,
        )
    }
}
