// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::whitelist_entry_type::WhitelistEntry;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `whitelist_entry`.
///
/// Obtain a handle from the [`WhitelistEntryTableAccess::whitelist_entry`] method on [`super::RemoteTables`],
/// like `ctx.db.whitelist_entry()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.whitelist_entry().on_insert(...)`.
pub struct WhitelistEntryTableHandle<'ctx> {
    imp: __sdk::TableHandle<WhitelistEntry>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `whitelist_entry`.
pub struct WhitelistEntryTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for WhitelistEntryTableAccessor {
    type Row = WhitelistEntry;
    type Handle<'db> = WhitelistEntryTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.whitelist_entry()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `whitelist_entry`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WhitelistEntryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WhitelistEntryTableHandle`], which mediates access to the table `whitelist_entry`.
    fn whitelist_entry(&self) -> WhitelistEntryTableHandle<'_>;
}

impl WhitelistEntryTableAccess for super::RemoteTables {
    fn whitelist_entry(&self) -> WhitelistEntryTableHandle<'_> {
        WhitelistEntryTableHandle {
            imp: self.imp.get_table::<WhitelistEntry>("whitelist_entry"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WhitelistEntryInsertCallbackId(__sdk::CallbackId);
pub struct WhitelistEntryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for WhitelistEntryTableHandle<'ctx> {
    type Row = WhitelistEntry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WhitelistEntry> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for WhitelistEntryTableHandle<'ctx> {
    type Row = WhitelistEntry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WhitelistEntry> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WhitelistEntryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WhitelistEntryInsertCallbackId {
        WhitelistEntryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WhitelistEntryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WhitelistEntryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WhitelistEntryDeleteCallbackId {
        WhitelistEntryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WhitelistEntryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for WhitelistEntryTableHandle<'ctx> {
    type InsertCallbackId = WhitelistEntryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WhitelistEntryInsertCallbackId {
        WhitelistEntryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WhitelistEntryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for WhitelistEntryTableHandle<'ctx> {
    type DeleteCallbackId = WhitelistEntryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WhitelistEntryDeleteCallbackId {
        WhitelistEntryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WhitelistEntryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WhitelistEntryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WhitelistEntryTableHandle<'ctx> {
    type UpdateCallbackId = WhitelistEntryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WhitelistEntryUpdateCallbackId {
        WhitelistEntryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WhitelistEntryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for WhitelistEntryTableHandle<'ctx> {
    type UpdateCallbackId = WhitelistEntryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WhitelistEntryUpdateCallbackId {
        WhitelistEntryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WhitelistEntryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `whitelist_entry`,
/// which allows point queries on the field of the same name
/// via the [`WhitelistEntryIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.whitelist_entry().identity().find(...)`.
pub struct WhitelistEntryIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WhitelistEntry, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WhitelistEntryTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `whitelist_entry`.
    pub fn identity(&self) -> WhitelistEntryIdentityUnique<'ctx> {
        WhitelistEntryIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WhitelistEntryIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<WhitelistEntry> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WhitelistEntry>("whitelist_entry");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WhitelistEntry>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WhitelistEntry>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WhitelistEntry`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait whitelist_entryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WhitelistEntry`.
    fn whitelist_entry(&self) -> __sdk::__query_builder::Table<WhitelistEntry>;
}

impl whitelist_entryQueryTableAccess for __sdk::QueryTableAccessor {
    fn whitelist_entry(&self) -> __sdk::__query_builder::Table<WhitelistEntry> {
        __sdk::__query_builder::Table::new("whitelist_entry")
    }
}
