// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WhitelistEntry {
    pub identity: __sdk::Identity,
    pub added_by: __sdk::Identity,
    pub added_at: __sdk::Timestamp,
}

impl __sdk::InModule for WhitelistEntry {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WhitelistEntry`.
///
/// Provides typed access to columns for query building.
pub struct WhitelistEntryCols {
    pub identity: __sdk::__query_builder::Col<WhitelistEntry, __sdk::Identity>,
    pub added_by: __sdk::__query_builder::Col<WhitelistEntry, __sdk::Identity>,
    pub added_at: __sdk::__query_builder::Col<WhitelistEntry, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for WhitelistEntry {
    type Cols = WhitelistEntryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WhitelistEntryCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            added_by: __sdk::__query_builder::Col::new(table_name, "added_by"),
            added_at: __sdk::__query_builder::Col::new(table_name, "added_at"),
        }
    }
}

/// Indexed column accessor struct for the table `WhitelistEntry`.
///
/// Provides typed access to indexed columns for query building.
pub struct WhitelistEntryIxCols {
    pub added_at: __sdk::__query_builder::IxCol<WhitelistEntry, __sdk::Timestamp>,
    pub identity: __sdk::__query_builder::IxCol<WhitelistEntry, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for WhitelistEntry {
    type IxCols = WhitelistEntryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WhitelistEntryIxCols {
            added_at: __sdk::__query_builder::IxCol::new(table_name, "added_at"),
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WhitelistEntry {}
