// SPDX-License-Identifier: GPL-3.0-only
// Ported from Mindustry (https://github.com/Anuken/Mindustry) — GPL-3.0.
// `tools/build.gradle` `pack` task (migration/copy semantics) — see plan 03 §3.5.

//! `mind-tools migrate` — one-time vendoring of the upstream asset trees.
//!
//! Copies `core/assets` → `assets/` and `core/assets-raw` → `assets-raw/`
//! with the generated-file trim list from [`mind_atlas::migrate`], then writes
//! `build/assets/migration_manifest.json` and `assets/ASSET_PROVENANCE.md`
//! (plan 03 M0; vendoring decision NUD-11).

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};
use mind_atlas::migrate::{self, MigrationManifest};

/// Manifest path relative to the repo root (gitignored `build/` tree).
pub const MIGRATION_MANIFEST: &str = "build/assets/migration_manifest.json";

/// Runs the migration (or, with `check`, the verification). Returns the number
/// of copied files (0 in check mode).
pub fn run(from: &Path, to: &Path, check: bool) -> Result<u64> {
    let manifest_path = to.join(MIGRATION_MANIFEST);
    if check {
        let manifest = MigrationManifest::read(&manifest_path)
            .with_context(|| format!("reading {}", manifest_path.display()))?;
        let problems = manifest.verify(to)?;
        if problems.is_empty() {
            println!(
                "migrate-check: OK ({} files verified)",
                manifest.file_count()
            );
            return Ok(0);
        }
        for problem in &problems {
            eprintln!("migrate-check: {problem}");
        }
        bail!("migrate-check failed with {} problem(s)", problems.len());
    }

    let src_assets = from.join("core/assets");
    let src_raw = from.join("core/assets-raw");
    if !src_assets.is_dir() {
        bail!(
            "upstream `core/assets` not found at {}",
            src_assets.display()
        );
    }
    if !src_raw.is_dir() {
        bail!(
            "upstream `core/assets-raw` not found at {}",
            src_raw.display()
        );
    }
    let dst_assets = to.join("assets");
    let dst_raw = to.join("assets-raw");

    let commit = git_line(from, &["rev-parse", "HEAD"]).unwrap_or_else(|| String::from("unknown"));
    let commit_date =
        git_line(from, &["log", "-1", "--format=%cs"]).unwrap_or_else(|| String::from("unknown"));

    // Clean mirror: wipe the destination trees (pack outputs are regenerated by
    // `mind-tools pack`; every other byte comes from upstream).
    wipe(&dst_assets)?;
    wipe(&dst_raw)?;

    let mut copied = 0u64;
    copy_tree(&src_assets, &dst_assets, &mut copied)
        .with_context(|| format!("copying {}", src_assets.display()))?;
    copy_tree(&src_raw, &dst_raw, &mut copied)
        .with_context(|| format!("copying {}", src_raw.display()))?;

    let manifest = MigrationManifest::build(to, commit.clone())?;
    manifest.write(&manifest_path)?;
    write_provenance(
        &dst_assets.join("ASSET_PROVENANCE.md"),
        from,
        &commit,
        &commit_date,
        &manifest,
    )?;

    println!(
        "migrate: copied {copied} files (assets: {}, assets-raw: {}), tree_hash {}",
        manifest.assets.files.len(),
        manifest.assets_raw.files.len(),
        manifest.tree_hash()
    );
    Ok(copied)
}

fn wipe(dir: &Path) -> Result<()> {
    if dir.exists() {
        fs::remove_dir_all(dir).with_context(|| format!("wiping {}", dir.display()))?;
    }
    fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
    Ok(())
}

fn copy_tree(src: &Path, dst: &Path, copied: &mut u64) -> Result<()> {
    copy_tree_at(src, src, dst, copied)
}

fn copy_tree_at(root: &Path, dir: &Path, dst: &Path, copied: &mut u64) -> Result<()> {
    let mut entries: Vec<PathBuf> = fs::read_dir(dir)?
        .map(|entry| entry.map(|e| e.path()))
        .collect::<std::io::Result<_>>()?;
    entries.sort();
    for path in entries {
        let rel = path
            .strip_prefix(root)
            .with_context(|| format!("stripping {}", path.display()))?
            .to_string_lossy()
            .replace('\\', "/");
        let is_dir = path.is_dir();
        if migrate::trim_exclude(&rel, is_dir) {
            continue;
        }
        let target = dst.join(&rel);
        if is_dir {
            copy_tree_at(root, &path, dst, copied)?;
        } else if path.is_file() {
            if let Some(parent) = target.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::copy(&path, &target)
                .with_context(|| format!("copying {} -> {}", path.display(), target.display()))?;
            *copied += 1;
        }
    }
    Ok(())
}

fn git_line(dir: &Path, args: &[&str]) -> Option<String> {
    let output = Command::new("git")
        .arg("-C")
        .arg(dir)
        .args(args)
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    String::from_utf8(output.stdout)
        .ok()
        .map(|text| text.trim().to_owned())
}

fn write_provenance(
    path: &Path,
    from: &Path,
    commit: &str,
    commit_date: &str,
    manifest: &MigrationManifest,
) -> Result<()> {
    let text = format!(
        "# Asset provenance (plan 03 M0)\n\
         \n\
         This tree is vendored from the upstream Mindustry checkout by\n\
         `mind-tools migrate` (NUD-11; see `03_ASSETS_IMPLEMENTATION_PLAN.md`).\n\
         Mindustry is GPL-3.0 (<https://github.com/Anuken/Mindustry>); the port\n\
         keeps region names, bundle keys and file paths byte-identical.\n\
         \n\
         - Source: `{from}` (`core/assets` -> `assets/`, `core/assets-raw` -> `assets-raw/`)\n\
         - Upstream commit: `{commit}` ({commit_date})\n\
         - Migrated file count: {count}\n\
         - Input tree sha256: `{hash}`\n\
         - Manifest: `build/assets/migration_manifest.json` (regenerate with\n\
           `mind-tools migrate --from $MIND_UPSTREAM --to .`; verify with\n\
           `mind-headless assets migrate-check`)\n\
         \n\
         Trimmed (never vendored; see `mind-atlas/src/migrate.rs`): `logicids.dat`,\n\
         `version.properties`, `locales`, `basepartnames`, `sprites.aatls`, generated\n\
         `sprites/sprites*.png` pages, `sprites/fallback/`, `sprites/block_colors.png`,\n\
         `bundles/output/`, `cache/`, `sprites_out/`, upstream `AGENTS.md` files.\n\
         Generated atlas pages/manifests under `assets/sprites/` are produced by\n\
         `mind-tools pack` and are gitignored.\n",
        from = from.display(),
        count = manifest.file_count(),
        hash = manifest.tree_hash(),
    );
    fs::write(path, text).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}
